### ISSUE TITLE
Please have docker image for ARM64

### ISSUE THREAD

**Issue by truongsinh** [garethgeorge/backrest#102]
Currently, docker image is only available for AMD64

**Comment by garethgeorge** [comment]
Definitely something we can do. Does setting the platform e.g. --platform linux/amd64 work currently as a workaround?

Linking the config for this for my own reference, https://goreleaser.com/cookbooks/multi-platform-docker-images/

**Comment by truongsinh** [comment]
The workaround you mentioned does not work, because there is not container image for ARMD64. For example, looking at https://hub.docker.com/r/garethgeorge/backrest/tags , OS/ARCH only has linux/amd64. But looking at https://hub.docker.com/_/golang/tags , we can see lots of other archs, one of which is linux/arm64/v8. My current workaround is to use the AMD64 image, but build another image on top, by copying the binary (from the release, for example https://github.com/garethgeorge/backrest/releases/tag/v0.12.2). Among the downsides, I cannot "docker exec -it <container_name> /bin/sh", because all the GNU utilities are of amd64 arch.

**Comment by garethgeorge** [comment]
Done in https://github.com/garethgeorge/backrest/pull/105

**Comment by garethgeorge** [comment]
Now available on https://hub.docker.com/r/garethgeorge/backrest/tags , I don't have an arm device to test on so please let me know if that works for you.
