### ISSUE TITLE
Basic http authentication for SSO

### ISSUE THREAD

**Issue by Janhouse** [garethgeorge/backrest#110]
Would be great if basic http authentication could be used to authenticate users.

With SSO systems like [Authentik you can use forward-auth](https://goauthentik.io/docs/providers/proxy/forward_auth) to [delegate authentication](https://doc.traefik.io/traefik/middlewares/http/forwardauth/) to the SSO system.
It can then send custom headers to the application which can use those headers to authenticate as a specific user.

In forward-auth scenario either a custom `x-forwarded-username` header can be used (which is injected by the forward-auth mechanism), or a basic http authentication could be used (credentials are injected by the forward-auth mechannism).

Backrest seems to use bearer authentication which [would not work with Authentik](https://goauthentik.io/docs/providers/proxy/header_authentication#sending-authentication).
So either supporting basic auth or defining header with the username would be great addition to support SSO forward-auth.

**Comment by garethgeorge** [comment]
Sgtm, this can be supported by backrest. Happy to accept a PR if that’s something you’re interested in. I probably lean a bit in the direction of adding a basic auth mode (as opposed to bearer) mode.
