### ISSUE TITLE
Project settings: Add support for running a script to produce a list of excluded files

### ISSUE THREAD

**Issue by dhilgarth** [garethgeorge/backrest#116]
**Is your feature request related to a problem? Please describe.**
I'm getting item errors on [Junctions](https://ss64.com/nt/mklink.html) that point to non-existent folders. 

**Describe the solution you'd like**
I would like a way to exclude them from the backup

**Additional context**
I'm on Windows. Those junctions are a result of Terraform downloading its providers, i.e. those Junctions are part of the providers package.
See #115 for a screenshot which shows some filenames.
Related: https://github.com/restic/restic/issues/1062

**Comment by garethgeorge** [comment]
From reading that thread I’m not seeing that restic ever added support for this. Ideally this is something to tackle upstream in restic and then enable using repo flags to pass extra cli arguments to restic. 

Can you add an exclude matching the name patterns for the specific items causing issues on your system?

**Comment by dhilgarth** [comment]
I've actually taken the suggestion from fd0 and created a script that lists all of the files that should be excluded.
If I could specify this script in the project - instead of a fixed list of globs - that would solve the issue as well be in line with how fd0 suggests doing this.

**Comment by garethgeorge** [comment]
Gotcha, I think this is good feature for pre-backup hooks + repo level flags (which need work, these don't work for flags that include values at the moment e.g. --exclude-file).

A good way to support this would be a pre-backup hook that runs a script to generate your excludes file, and then to include that in set of flags used for each backup command run on the repo.

**Comment by dhilgarth** [comment]
Sounds good, thanks!

**Comment by garethgeorge** [comment]
Command hooks and per-plan flag overrides are available in the last few releases -- closing this for now. Feel free to ping if you're still looking for a workaround on this issue.

**Comment by ayancey** [comment]
Would like to add, as this is annoying me too: On Windows, restic runs into a recursive loop because of the [Application Data junction](https://answers.microsoft.com/en-us/windows/forum/all/infinite-application-data-folders-and-subfolders/e5c13e20-2271-4329-bde8-c93cb1988139)
