### ISSUE TITLE
Inconsistent behavior when opening plans

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#125]
When we open the Backrest interface for the 1st time (i.e. opening on a new tab/page refresh), when we click on one of the plans, we see the 4 last backup entries expanded, plus the next scheduled backup. All older backups are closed. Here's an example:
![image](https://github.com/garethgeorge/backrest/assets/62859/40fe3e18-9665-4e11-afe4-73100d6626a2)

But when we select another plan, all backup entries are closed:
![image](https://github.com/garethgeorge/backrest/assets/62859/1a9d064b-9da3-4ef4-9646-fb29afdc85ca)

It would be nice to have a consistent behavior.

**Comment by garethgeorge** [comment]
I've noticed this behavior too, it's a bug with the underlying UI framework. I'll try to come up with a workaround since it definitely can add a lot of clicks.

**Comment by garethgeorge** [comment]
Managed to track this down, will be fixed in the the next release by https://github.com/garethgeorge/backrest/commit/d7ca35b66f61c12360905e98b775e3256210176e
