### ISSUE TITLE
Inconsistent Hook trigger names

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#127]
The hook trigger names appear differently when we add a new hook to a plan/repo than when we edit a plan/repo with hooks aready defined.
The hooks list looks like this:
![image](https://github.com/garethgeorge/backrest/assets/62859/8d343aa0-b691-4501-9abd-bbffbc2ecb6c)

And it still looks ok after we select them:
![image](https://github.com/garethgeorge/backrest/assets/62859/470dbacd-1ee2-4ab7-a2fd-858a24568249)

But when we edit an existing plan/repo with hooks already defined, it looks differently:
![image](https://github.com/garethgeorge/backrest/assets/62859/5e18ebe1-3f54-4c50-9b0d-ac7d4e1d9c2b)

Although the items on the list still look ok, but it does not identify the already selected ones:
![image](https://github.com/garethgeorge/backrest/assets/62859/bdca2e3f-d5be-4c5a-8852-560d60b497ba)

This means that we can select the same hook again:
![image](https://github.com/garethgeorge/backrest/assets/62859/2d3dd786-2019-4ddf-8b6b-b6533cb227ad)

Saving the new selections saves the duplication. When we edit the plan/repo again, we can see the duplication:
![image](https://github.com/garethgeorge/backrest/assets/62859/7bbfdb18-f0a6-449e-9ea9-d467a3ea592b)

When trying to delete some of the entries, somehow the list of selected triggers keeps increasing:
![image](https://github.com/garethgeorge/backrest/assets/62859/1dcad35d-3e22-4b52-a2ad-668a7f6eb1a7)

Although it seems they are not all saved.

Even if duplicate entries are selected they are only triggered once.

**Comment by garethgeorge** [comment]
thanks for the detailed report and for catching this. I’ll go ahead and get a patch out with the next release (I may just make all of the names consistently use the capitalized form as it’s pretty understandable and that’s the raw value that’s used in the config so it may be least error prone).

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/releases/tag/v0.17.0 .
