### ISSUE TITLE
Impractical excludes

### ISSUE THREAD

**Issue by ArthurusDent** [garethgeorge/backrest#131]
**Is your feature request related to a problem? Please describe.**

Please correct me if I'm wrong. From what I see when adding a new plan, you can add paths to files and directories to exclude. 

These are the restic parameters that seem to be used:
--exclude
--iexclude

My problem is that I'm using quite a long exclude file (33 lines):

`/dev/*
/home/*/.gvfs/*
/home/*/.cache/*
/home/*/.local/share/baloo/*
/home/*/.local/share/kiwix/*
/home/*/.local/share/Trash/*
/home/*/Downloads/*
/home/*/dwhelper/*
/home/*/remnote/*
/home/*/snap/brave/common/.cache/BraveSoftware/Brave-Browser/Default/Cache/Cache_Data/*
/home/*/snap/brave/common/.cache/BraveSoftware/Brave-Browser/Default/Code\ Cache/js/*
/home/*/snap/chromium/common/chromium/Default/Cache/Cache_Data/*
/home/*/snap/chromium/common/chromium/Default/Code\ Cache/js/*
/home/*/snap/discord/*/.config/discord/Cache/*
/home/*/snap/discord/*/.config/discord/Code\ Cache/*
/home/*/snap/discord/*/.config/discord/GPUCache/*
/home/*/snap/firefox/common/.cache/*
/home/*/StudioProjects/*
/home/*/Syncthing/*
/home/*/Torrents/*
/home/*/VirtualBox\ VMs/*
/media/*
/mnt/*
/proc/*
/root/.cache/*
/run/*
/sys/*
/tmp/*
/var/cache/apt/archives/*
/var/lib/snapd/cache
/var/lock/*
/var/run/*
/var/temp/*`

Adding 33 lines with the available single line dialogue is kind of cumbersome. 

**Describe the solution you'd like**

Would it make sense to switch to 
--exclude-file
--iexclude-file

and give the user a box to input text?

**Comment by garethgeorge** [comment]
Hey, I think this is very reasonable. I think I’ll aim to support this (and other general restic flags) by fixing the flags options at the repo level and by adding flag overrides at the plan level.

**Comment by garethgeorge** [comment]
Added a "Backup Flags" property to the plan configuration where arbitrary flags can be speified. Try creating an exclude file and then specifying it as a backup flag e.g. 

```
--exclude-file <path to your file>
``` 

In the UI
