### ISSUE TITLE
Duplicate actions on the Repo/Plan Operation List

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#132]
Hi Gareth,

I have a repo configured with 6 plans:

- 2 plans run every day
- 4 plans run once per month, on the 1st

When looking at the Operation List view from the repo and plan, the 4 plans that run one per month show 7 planned task entries each:
![image](https://github.com/garethgeorge/backrest/assets/62859/b2c1928b-58f1-48ab-9ea8-73328a4050b7)

As you can see, only the entry at the bottom as the cancel operation.

Looking at the plan Tree View I can see only one entry, so I guess the issue on the Operation List is cosmetic.
![image](https://github.com/garethgeorge/backrest/assets/62859/43fedcab-0723-4db1-bc98-d63c8517fa94)

The plans scheduled everyday are showing correctly:
![image](https://github.com/garethgeorge/backrest/assets/62859/b3f1bc27-5ecf-4a57-a756-1748d97397f8)

**Comment by garethgeorge** [comment]
Hey — I’ve noticed this too and you’re right that it’s a UI error. Those operations have a special “cancelled” status from rescheduling that should be hidden by the UI (and is in tree view but isn’t in the list view).

**Comment by garethgeorge** [comment]
Significantly refactored the UI's handling of operation events in the latest release, I think this should be resolved now.

**Comment by Danstiv** [comment]
Steps to reproduce:
1. Set Clock for schedule to Last Run Time.
2. Put the system to sleep.
3. Wait for the backup time, plus a couple of minutes.
4. Awaken the system.

After that, 2 backups will be performed.
Should i open separate issue for that?
