### ISSUE TITLE
Windows executable ignores command line parameters

### ISSUE THREAD

**Issue by hello-world-dot-c** [garethgeorge/backrest#134]
Using the backrest.exe from https://github.com/garethgeorge/backrest/releases/download/v0.13.0/backrest_Windows_x86_64.zip, I started it with a full command line

`backrest.exe -config-file string C:\restic\backrest\config.json -data-dir string C:\restic\backrest\data -restic-cmd string C:\restic\restic.exe`

since I already have the latest version installed there. Nevertheless, it completely ignored all options, insisted on downloading and installing the same version as C:\Program Files (x86)\restic\restic-0.16.4.exe and used the default locations for data and config under AppData. This does not match with the expected behaviour as given by the -help option:

```
C:\restic\backrest>backrest.exe -help
Usage of backrest.exe:
  -bind-address string
        address to bind to, defaults to :9898. Use 127.0.0.1:9898 to listen only on localhost. Overrides BACKREST_PORT environment variable.
  -config-file string
        path to config file, defaults to XDG_CONFIG_HOME/backrest/config.json. Overrides BACKREST_CONFIG environment variable.
  -data-dir string
        path to data directory, defaults to XDG_DATA_HOME/.local/backrest. Overrides BACKREST_DATA environment variable.
  -restic-cmd string
        path to restic binary, defaults to a backrest managed version of restic. Overrides BACKREST_RESTIC_COMMAND environment variable.
```

**Comment by garethgeorge** [comment]
Hi, I'm a bit surprised that the flag parsing library didn't give you an error there! You shouldn't be including "string" in your command line, the right command will be something like 

```
backrest.exe -config-file C:\restic\backrest\config.json -data-dir C:\restic\backrest\data -restic-cmd C:\restic\restic.exe
```

Try giving that a go.

**Comment by hello-world-dot-c** [comment]
Duh! Yes, works. Thanks, case closed.
