### ISSUE TITLE
Stats not displaying 

### ISSUE THREAD

**Issue by gtlfilms** [garethgeorge/backrest#136]
There's no stats displayed even tho i have multiple backups..I'm running 0.13.0 in docker.

There is no error messages in docker log..When i press the index snapshots button i get the log below.

![Screenshot 2024-02-28 145720](https://github.com/garethgeorge/backrest/assets/24412811/2ccf405f-6eb3-404e-b20c-cac27a8c2385)

One thing i did notice in the logs is the plan "data" is actually my repo.

I think i'm having the same issues as https://github.com/garethgeorge/backrest/issues/87#issue-2134199711

**Comment by garethgeorge** [comment]
The latest release overhauls stats handling, stats should be generated after each prune operation now. Additionally, I've added a "Compute Stats" button on the repo page to allow forcing a refresh at any time.

**Comment by PaddyPat** [comment]
Yes and they are displayed in white font on white background ;-) I see only headlines if I mark all ..

**Comment by wookash** [comment]
yup, this is how I see them
![image](https://github.com/garethgeorge/backrest/assets/222462/81988810-2c6e-45f6-8833-d7e4fbf9b2c2)

**Comment by garethgeorge** [comment]
That's pretty funny -- and also definitely needs fixing. I did actually add some logic to try to set a color theme for the charts 
 that matches the UI theme so it's weird that it's not matching. I'll do some debugging tonight.

**Comment by modem** [comment]
The text seems to be written in white. This is what I see:
![image](https://github.com/garethgeorge/backrest/assets/62859/d1092048-e3fa-480e-804a-d3ab0f295289)

And if I select everything, I can see the text:
![image](https://github.com/garethgeorge/backrest/assets/62859/2d0c4c54-574b-48d4-bd00-94b798156ede)

**Comment by modem** [comment]
Btw, not all data is visible, this backup runs everyday, but the last point is on the 23rd, and the previous seems to be on the 14th.

Also, on mouse hover, we can see a tooltip with the last value.
![image](https://github.com/garethgeorge/backrest/assets/62859/f43dc642-da5b-4014-9db8-e6970adbdcb3)

Not sure this is intended or not, but personally  I think the tooltip should show the data from the point where we put the mouse over.

**Comment by wookash** [comment]
Correct. This is a screen from my mobile, dark mode enabled in the phone

![image](https://github.com/garethgeorge/backrest/assets/222462/8dfef84a-c7f5-4fe3-99f7-9d8f05a2982e)

**Comment by modem** [comment]
The more I look, the more I see things to improve...

In some charts, the Y axis does not show the entire values. See this example below for Total Size and Blob Count:
![image](https://github.com/garethgeorge/backrest/assets/62859/2808126d-418c-407c-b7be-fc349582ce3f)


The Total Size Y axis should also mention the unit used. Currently it seems to be MB.

And what is the meaning of the Compression Ration value? 1.5 means what exactly? 
If the calculation is backup size / total size, or (total size-backup size)/total size, I expected this value to be less than 1, and since it's a ratio should be in percentage.

**Comment by modem** [comment]
> Correct. This is a screen from my mobile, dark mode enabled in the phone
> 
On a desktop computer I see no way to set the screen to dark mode, unless this is automatic from the operating system.

**Comment by garethgeorge** [comment]
Thanks for all the screenshots -- and yep right now there isn't a way to toggle the color theme. I think in a minor patch release I'll want to address this themeing issue and also add an explicit color theme button to the UI (right now it's taken from the system preferences) which will also make it easier for me to test and catch these bugs prior to release.

**Comment by garethgeorge** [comment]
Sorry this took a while to get to -- now fixed in 0.15.0 !

**Comment by wookash** [comment]
hi @garethgeorge, I've just tested and 0.15.0 shows me this:

<img width="2169" alt="image" src="https://github.com/garethgeorge/backrest/assets/222462/6ea18e69-cc4e-4310-b4f9-65a05efc8c2d">

**Comment by modem** [comment]
I also don't see any change.
![image](https://github.com/garethgeorge/backrest/assets/62859/7c3a67e1-97dc-4448-a41e-bd38d9f77e2d)

Tried with Firefox, Chrome and Edge, all showing the same.

**Comment by wookash** [comment]
I actually liked the stats displayed as text and not graphs so if it’s easier to make it work - I’d vote for it

**Comment by ovizii** [comment]
> I also don't see any change. ![image](https://private-user-images.githubusercontent.com/62859/314475335-7c3a67e1-97dc-4448-a41e-bd38d9f77e2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzEyMTcsIm5iZiI6MTcxMTAzMDkxNywicGF0aCI6Ii82Mjg1OS8zMTQ0NzUzMzUtN2MzYTY3ZTEtOTdkYy00NDQ4LWE0MWUtYmQzOGQ5Zjc3ZTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZTNlOWYwMGY3NDczZjgwNzBlMTdlM2Q1YWJkMjAwMDkxNWNiYWU5MWQ0NjlhODdhNzJiNTFiZmFjYzlhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bF8noUaQacNtfMW_SrdNqNM9Yca52SOeTERKeCNuOc)
> 
> Tried with Firefox, Chrome and Edge, all showing the same.

Me neither. Changing browser and cleaning cache didn't help or maybe there's something else I am overlooking?
