### ISSUE TITLE
Experience Features: Support for reordering plans

### ISSUE THREAD

**Issue by oneisall8955** [garethgeorge/backrest#139]
**Describe the solution you'd like**
I hope that each plan in the plan list supports adjusting the order. This can be achieved by dragging elements or manually configuring the order weight.

**Additional context**
![image](https://github.com/garethgeorge/backrest/assets/44989283/ebcf789f-3d8f-4dae-9e9c-5e9af3a7d7e3)

As shown in the picture, I want to adjust the plan acme_local under the plan bitwarden_local

**Comment by garethgeorge** [comment]
Hmm, imo I'm not sure if drag and drop custom ordering is something that backrest should be aiming to support, but I do consider it a bug that the order is arbitrary right now. What would you think of always displaying plans and repos in sorted order? 

At the moment, you can edit the order by manually editing the order of the entries in the config.json and then restarting backrest.

**Comment by oneisall8955** [comment]
Thanks for the reply, I reordered it by editing the config.json file and it works great.
Also, sorting the plans might just be my personal hobby, as I want to show the plans in different repository order, e.g. the local repository is in front and s3 is below
