### ISSUE TITLE
Add tzdata to alpine docker image

### ISSUE THREAD

**Issue by causalmask** [garethgeorge/backrest#140]
I'd recommend adding the alpine package 'tzdata' in Dockerfile.alpine so that it's easy to set the timezone via the 'TZ' environment variable.  Otherwise all the backup scheduling times are shown in UTC.

**Comment by oneisall8955** [comment]
Highly recommended

**Comment by garethgeorge** [comment]
Hey, thanks for including a suggested fix! Added in https://github.com/garethgeorge/backrest/commit/0e94f308cde40059f9c4104ed21f8c701a349c57

**Comment by causalmask** [comment]
Much appreciated. :)
