### ISSUE TITLE
Allow empty password when registering repo

### ISSUE THREAD

**Issue by Nathoufresh** [garethgeorge/backrest#147]
When using an rclone mount, the password may be specified in the rclone.conf directly. In that case, the password given in the user interface when registering the repo isn't used, but an error is thrown if the field is empty. I had to pass a random string to make it work.

Backrest should detect the cases when a password may not be needed and go a step further before throwing an error.

I'm new to restic and backrest so I might have misunderstood things.

**Comment by garethgeorge** [comment]
Can you link the restic docs w.r.t. this behavior? It's not something I'm aware of -- are you sure that restic is using the rclone password to encrypt the repo.

My understanding is that rclone credentials would be for connecting to your storage whereas the restic password will encrypt your data where it is stored on the remote. Be very sure you're aware which one is being used as it's possible your data is being encrypted with the password you set (and you'll want to save that password somewhere!).

**Comment by Nathoufresh** [comment]
Well, you're right! I didn't know the backups were encrypted by default with restic. Perhaps a helpful tooltip explaining the purpose of this password field or directing users to the restic documentation could be beneficial.

**Comment by garethgeorge** [comment]
Great, that seemed most likely :) hope you have your password saved somewhere now in that case!!
