### ISSUE TITLE
Access denied error on Windows

### ISSUE THREAD

**Issue by RobProductions** [garethgeorge/backrest#148]
**Describe the bug**
When I try to run my backup manually with the "backup now" option or via schedule, the process fails and I get an error ending with "unable to save snapshot: Access is denied". Here's the full snippet:

```
error: repo.Backup for repo "c-documents-repo": failed to backup: command "C:\\Program Files (x86)/restic/restic-0.16.4.exe backup --json --exclude-caches -o sftp.args=-oBatchMode=yes C:\\Users\\Matt\\Documents --tag plan:c-documents-plan" failed: exit code 1: backup failed
processing command output: no summary event found
Process STDOUT: 
{"message_type":"error","error":{},"during":"archival","item":""}
{"message_type":"error","error":{},"during":"archival","item":""}
{"message_type":"error","error":{},"during":"archival","item":""}
{"message_type":"error","error":{},"during":"archival","item":""}
Fatal: unable to save snapshot: Access is denied.
```

**To Reproduce**
I created a repo just fine which is hosted on my NAS device and checked that it was created in the file system - it was. Then I added a plan and hit the "backup now" button to test that it would work but then it immediately failed. No matter what I try I can't seem to get it to succeed. This is the JSON config for the plan:

```json
{
  "id": "c-documents-plan",
  "repo": "c-documents-repo",
  "paths": [
    "C:\\Users\\Matt\\Documents"
  ],
  "excludes": [],
  "iexcludes": [],
  "cron": "0 18 * * *",
  "retention": {
    "keepLastN": 4
  }
}
```

What's strange is that it actually worked properly earlier today when I set up a test plan but is now suddenly not working. I did quit and relaunch the server a few times in order to test stuff, so maybe that was the cause? I am running backrest from a call command in Windows Terminal for convenience but I also verified that the error still happens when I run the regular .exe file.

**Expected behavior**
It should succeed. I thought that it might be the fault of the location the repo is hosted in (my NAS device) but that doesn't make sense considering it worked fine earlier in the day. I double checked the folder permissions in Windows and added Full Control to "Everyone" just in case but it made no difference. Then to be really sure I copied the command from the error, pasted it into the cmd (with "restic" instead of the full program files path to restic exe), and added the -r flag with my repo path (which is through the network and to the NAS) and then it started to run properly. I'm thinking there must be something strange happening with how backrest runs the restic command that causes this error, right? 

**Screenshots**
![image](https://github.com/garethgeorge/backrest/assets/11141862/46acb163-ee62-4674-8495-401495ab6e65)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Firefox
 - Backrest Version: 0.14.0

**Additional context**
Been really loving the look and feel of this app so far, it seems perfect for my use case but unfortunately can't seem to get it to work properly. Any idea what might be going wrong? I searched for a while about this in restic-related forums but can't find anything recent. Also the fact that it worked from restic CLI makes me think there's a quirk in the app instead. Appreciate the help!

**Comment by Badassito** [comment]
I think I ran into the same issue. Try running it as admin

**Comment by RobProductions** [comment]
> Try running it as admin

Thanks, you're right; I actually found out yesterday that running it as admin gets around the issue but because of that I have a second problem, I can't get the task scheduler to open my .bat file (which calls the server) with admin mode in Windows Terminal. For some reason without admin privileges task scheduler will default to opening my .bat file in Windows Terminal but with privileges it will default to opening it with regular Command Prompt. I tried some solutions where command prompt opens Windows Terminal via `start` but it seems to crash, and even then I'm not sure if admin privileges will carry over. 

Those are all windows-specific annoyances but I wouldn't have to do all this in the first place if it worked correctly without admin mode. I'm a little confused why the restic CLI doesn't need it but backrest does. Tried looking through the source code but I've never used Go before and it's a little hard to track down how it calls restic.

The reason I want it in Windows Terminal is because Terminal has a feature that lets you minimize the console to the system tray and that's really helpful for keeping the server hidden so I don't accidentally close it. If the compiled .exe for backrest had this feature I could just run it directly from scheduler with admin, but since that appears to be command line program it can't do that. I can double click it the backrest .exe and it will open in Windows Terminal but in order for it to start minimized I'd have to run it through a shortcut or prepend it with a minimize command in a .bat file. When I run it through a shortcut suddenly it opens in Command Prompt again and not Windows Terminal. So it's seeming impossible or absurdly complex to open it like this from task scheduler. 

One last thing I could do is find some other program that can force backrest.exe to minimize to system tray which also works with task scheduler and admin mode, so I will look into that. Or I could accept some way for backrest to run completely hidden and only stopped via task manager or task scheduler controls, but that's a bit less ideal. Hope that wasn't too much of a rant but I've been banging my head against for many hours and can't seem to find any clean solution :')

**Comment by RobProductions** [comment]
Update: Can't believe I forgot about this but the task scheduler itself has a "hidden" option that also works with admin mode so although it's not perfect as I can no longer see the output of backrest.exe, this will work for now to run it in the background. I just had backrest.exe run without any other batch file or minimizing code.

![image](https://github.com/garethgeorge/backrest/assets/11141862/328351c2-57bd-44e7-ae5d-1a34d4a974e4)

That said, it might still be neat to remove the admin requirement as it would open up more options for running it on Windows, but for now I'm happy that it's finally working :)

**Comment by garethgeorge** [comment]
Nice, glad you were able to work around this! Admin actually isn't required after the first run if you're not accessing anything protected.

Windows permissions aren't a space I'm very knowledgeable about so I blanket recommend admin to work through this but generally speaking you should be able to lock things down a bit :)

**Comment by RobProductions** [comment]
> Admin actually isn't required after the first run if you're not accessing anything protected.

That's the issue though, this wasn't the first run, and nothing here should've been protected :( Something Windows-specific was causing an issue in this circumstance so maybe this could instead be turned into a future enhancement in order to get it functionally on par with the Linux version? Doesn't matter much for me now that I got it running this way but it may have some consequence down the line for someone else. Fixing it would let you remove this:

> warning: If you get filesystem errors you may need to run Backrest as administrator for full filesystem access.

from the Readme and make it simpler to run for newcomers
