### ISSUE TITLE
Add an option for breaking/stopping plan execution when a hook fails.

### ISSUE THREAD

**Issue by sdluxeon** [garethgeorge/backrest#150]
**Is your feature request related to a problem? Please describe.**
In my current workflow, I need to stop some services and containers before running the backup plan. I am trying to do this with a hook script and it generally works. The problem is that if hook script fails, the backup plan continues as scheduled. which may result in backing up corrupted filles & databases. (e.g. performing a backup during a write). 

**Describe the solution you'd like**
There are several solutions:
- Adding another type of hook which when fails the plan execution stops (duplicati does this with --run-script-before-required, but I really dont like it)
- Require all hooks to exit with code 0, otherwise the plan stops (which is bad, because failed notifications should not stop backups)
- Add another option(e.g.. checkbox) for hooks, where it can be specified that the hook is "Required Successful". When the checkbox is selected the plan will fail and not perform the backup when the hook fails.

**Additional context**
Being able to setup a timeout for the hook would also be nice, but this can be handled in the scripts.

**Comment by garethgeorge** [comment]
Hmm, pretty interesting use case & this makes a lot of sense to me. It’ll probably take me a while to get to this as I have a bit of a backlog of bug fixes, but I think #3 sounds like my preferred solution. I’ll aim to implement that when I have a bit of bandwidth or would be happy to take it as a contribution.

**Comment by garethgeorge** [comment]
Implemented in https://github.com/garethgeorge/backrest/commit/d8924db9754e4decf5ac7ea84730644d8da8ce2e
