### ISSUE TITLE
Using a SSO system instead of local authetication

### ISSUE THREAD

**Issue by jazzdd86** [garethgeorge/backrest#151]
I use authentik as SSO system and it would be nice to disable the backrest auth system completly.
As there is no user rights system used by Backrest the authentication is only used to prevent unautorized use.

Therefore I could use authentik to authenticate a user and verify the user is allowed to enter Backrest.

If the user successfully authenticated against authentik there should be no additional login used by Backrest itself.

**Comment by garethgeorge** [comment]
Ill aim to add some native support for disabling with. At the moment you may be anble to work around it by adding a user explicitly with the default credentials. These are user: “default” and password: “password”.

**Comment by Janhouse** [comment]
@jazzdd86 it is already possible and I am using it with Traefik forward-auth and Authentik. When adding basic auth, it logs you in automatically.

Here is more information:
https://github.com/garethgeorge/backrest/pull/129#issuecomment-2002676689

@garethgeorge this should probably be added to readme/wiki

**Comment by jazzdd86** [comment]
Hi @Janhouse, the default user and password approach @garethgeorge suggested works fine, but I tried your instructions for foward auth through authentik. But this doesn't work for me.
I always get the message in the backrest logs: auth middleware blocked bad JWT: user not found
and website shows: Unauthorized (No Authorization Header) for URL https://domain/v1.Backrest/GetOperationEvents

**Comment by Janhouse** [comment]
@jazzdd86 if it complains about no authorization header then it is not added. Depending on the http server you use, you might have to [add `authorization` header to whitelist](https://doc.traefik.io/traefik/middlewares/http/forwardauth/#authresponseheaders) of headers that can be added by forward-auth.

I use [Traefik](https://doc.traefik.io/traefik/middlewares/http/forwardauth/#authresponseheaders) with Docker labels so I have:

```
- "traefik.http.middlewares.auth-traefik.forwardauth.authResponseHeaders=authorization,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version"
```

**Comment by jazzdd86** [comment]
omg, that was too easy....thanks for the hint. It works like a charm now. As you mentioned, would be great to add this SSO information to the wiki
thanks for the great work guys
