### ISSUE TITLE
Option to copy an existing plan to create a new one

### ISSUE THREAD

**Issue by tixwho** [garethgeorge/backrest#152]
Just installed backrest yesterday, it's abosolutely amazing! My only complaint about the previous backrest is how hard to navitage through the documents and learn about what has been done -- Backrest solved it such a perfect way, thank you so much!

I'm suggecsting to add a button next to the plan item (probably foldable? I'm not an UI expert) so that we can use the established content as a template to create new one. It can save some time entering repetitive blocks, like notification type, backup flags, etc., and can also avoid increased chance of typos if you we had to start over again.

Again, thanks for the amazing contribution!

**Comment by garethgeorge** [comment]
Glad this is working well for you!

The easy way to duplicate a plan right now would be to stop backrest and copy it manually in the config.json which is intended to be reasonably easy for humans to edit. 

For shared config properties you might also look at using repo flags to provide an excludes file e.g. `--exclude-file=path-to-an-excludes-file.txt` to share exclusion rules between multiple plans.

**Comment by garethgeorge** [comment]
Closing as there's a good workaround here, let me know if you still have questions.
