### ISSUE TITLE
Compression progress int64 vs float64 JSON parsing error

### ISSUE THREAD

**Issue by mescanne** [garethgeorge/backrest#154]
**Describe the bug**
Stats from existing repository could not be extracted.

Error:
Error: get stats: stats for repo b2: command "/data/restic-0.16.4 stats --json --mode=raw-data -o sftp.args=-oBatchMode=yes" failed: command output is not valid JSON: json: cannot unmarshal number 54.40977174932906 into Go struct field RepoStats.compression_progress of type int64
Process STDOUT: 
{"total_size":1080346194514,"total_uncompressed_size":1091443795460,"compression_ratio":1.0190433559675918,"compression_progress":54.40977174932906,"compression_space_saving":1.016781715390369,"total_blob_count":2529304,"snapshots_count":68}

The compression_progress type in restic itself is float64 [here](https://github.com/plumbeo/restic/blob/a6f83e0011239c064fc8632b74f1c8c5c3450792/cmd/restic/cmd_stats.go#L316C2-L316C21), but within backrest it is an int64 type.

**Expected behavior**
Value extracted from the JSON.

**Desktop (please complete the following information):**
Deployed in docker with latest release (on this day).

**Comment by garethgeorge** [comment]
Thanks! Not sure why I haven't seen this in my runs of it, I'll go ahead and fix this to be consistent.

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/releases/tag/v0.15.0

**Comment by mescanne** [comment]
Much thanks for the fix!

Some context that may explain it -- I already have separately managed restic backup through cron, so my experimentation with backrest was to inspect the current backups rather than creating some new ones. So running the statistics independently is what I tried and got the error.

I'll continue experimentation -- very much looking forward to having a UI to manage backups!
