### ISSUE TITLE
Time appears inconsistent 

### ISSUE THREAD

**Issue by cmaxwe** [garethgeorge/backrest#162]
**Describe the bug**
Using a docker-compose install if I setup a plan to backup on x day at 11:00 then view the tree view it will have a different time.

I suspect this is using the browser time zone for showing the tree view and the image time zone when setting the plan.

**To Reproduce**
1. Go to Plan
2. Set a time
3. Save the change
4. Tree view is displayed with the next backup and the time is different

**Expected behavior**
I expect the times to be the same.

**Additional context**
I tried mapping my /etc/timezone to the /etc/localtime in the image but that didn't fix the problem. Maybe needs to be a docker environment variable?

**Comment by mitchplze** [comment]
I think there's a related issue, where times in the 12:00:00-12:59:59 (twelve noon) range are being incorrectly labeled as "AM" when they are actually PM. These two jobs are ~1 hour apart, but time is showing wrong: 

<img width="461" alt="image" src="https://github.com/garethgeorge/backrest/assets/25162574/1dffae89-a47e-4a62-9e70-a86c81906043">

**Comment by garethgeorge** [comment]
Fixed  AM / PM formatted incorrectly and updated the default image to now use alpine which fixes the timezone issue.

**Comment by ovizii** [comment]
Would you mind having a look if this is related? I am on backrest 0.16.0 and set up another plan today for 4am.

![image](https://github.com/garethgeorge/backrest/assets/837902/2b74d1a5-91f3-4b93-8500-ff6618ae261b)

And yet it is planned for 6am? 

![image](https://github.com/garethgeorge/backrest/assets/837902/2d23022b-26dc-45ae-874b-f91ed1d79279)

entering the backrest container:
```
date
Tue Apr  2 09:50:55 UTC 2024
```
on the host:
```
date
Tue  2 Apr 11:51:45 CEST 2024
```

in docker-compose.yml I tried:
```
      - /etc/timezone:/etc/timezone
      - /etc/timezone:/etc/localtime
```
but none of those worked.
