### ISSUE TITLE
error: forget

### ISSUE THREAD

**Issue by wookash** [garethgeorge/backrest#164]
**Describe the bug**
When running a backup I get this error: 

error: forget: get snapshots for repo xxxx: command "/backup/restic-0.16.4 forget --json -o sftp.args=-oBatchMode=yes --tag plan:xxxx --group-by tag" failed: command output is not valid JSON: unexpected end of JSON input

**To Reproduce**
run backup

**Expected behavior**
No error, successful backup

**Desktop (please complete the following information):**
docker, backrest 0.15.0

**Comment by davide93** [comment]
Same as:
https://github.com/garethgeorge/backrest/issues/160

Fixed in the latest release:
https://github.com/garethgeorge/backrest/releases/tag/v0.15.1
