### ISSUE TITLE
sftp custom port ignored

### ISSUE THREAD

**Issue by alexdelprete** [garethgeorge/backrest#165]
**Describe the bug**
I'm trying to set a custom port (2222) as destination sftp, but backrest ignores it and always uses default port (22).

**To Reproduce**
Create new Restic repo like this:
![image](https://github.com/garethgeorge/backrest/assets/7027842/4fa3a158-a10a-44c7-b347-87a27836a4df)

**Expected behavior**
I expect backrest to access sftp via custom port 2222 as per restic docs (see screenshot below).

**Screenshots**
restic docs:
![image](https://github.com/garethgeorge/backrest/assets/7027842/7439e450-d632-4c8a-9dfb-d4b50ec5ed55)

**Desktop (please complete the following information):**
 - OS: docker with ubuntu 22.04
 - Browser: Edge
 - Backrest Version: 0.15.1

**Comment by garethgeorge** [comment]
Hey! Looks like this may actually be a known restic issue, does https://forum.restic.net/t/how-to-use-a-custom-sftp-port/5321 look like its describing the same problem you’re running into?

**Comment by alexdelprete** [comment]
That was it. My bad, I was using sftp: instead of sftp:// (URL syntax). Thanks for the hint. :)

Now I'm stuck on the identity file to be used: I generated a key pair and placed them in /data. How do I tell backrest to use that specific identity file? If I put them in $HOME/.ssh they would be deleted when I recreate the container.

**Comment by alexdelprete** [comment]
Ok, I had to use flags:

```
-o sftp.command="ssh -i /data/id_ed25519 -o "ControlMaster=no" -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -p 2222 user@host.domain.net -s sftp"
```

Also: the generated key is without passphrase because with passphrase it always failed, it seems there's no ssh-agent inside the container that caches it. Can you confirm this?

**Comment by alexdelprete** [comment]
With a custom config file it's even better, here's the json config:

```json
{
  "id": "MyResticRepo",
  "uri": "sftp:MyNAS:/backup/restic-repo",
  "env": [
    "RESTIC_PASSWORD_FILE=/config/MyBackup.pw"
  ],
  "flags": [
    "--option sftp.command=\"ssh -F /config/MyNAS.config MyNAS -s sftp\"",
    "--password-file /config/MyBackup.pw"
  ],
  "prunePolicy": {
    "maxFrequencyDays": 7,
    "maxUnusedPercent": 25
  }
}
```

And here's the MyNAS.config:

```console
Host OSILifeNAS
    Hostname myhost.domain.net
    Port 2222
    User myuser
    IdentityFile /config/backrest_id_ed25519
    StrictHostKeyChecking no
    ControlMaster no
    UserKnownHostsFile /dev/null

```

I wanted to use the flag `--password-file` for the repo password, but backrest complained that I had to either specify a password or use the env var `RESTIC_PASSWORD_FILE`. It seemed to ignore the flag `--password-file`. Is it a bug?

**Comment by alexdelprete** [comment]
Another issue: I had to add Loglevel ERROR to the ssh config file, otherwise backups would fail because of ssh warning:

```console
error: repo.Backup for repo "MyResticRepo": failed to get snapshots for plan: get snapshots for plan "MyRemoteBackup": command "/data/restic-0.16.4 snapshots --json --option sftp.command=ssh -F /config/MyNAS.config MyNAS -s sftp --tag plan:MyRemoteBackup" failed: command output is not valid JSON: invalid character 's' looking for beginning of value
Process STDOUT: 
subprocess ssh: Warning: Permanently added '[myhost.domain.net]:2222' (ED25519) to the list of known hosts.
```

**Comment by garethgeorge** [comment]
Hey, thanks for documenting your path debugging this. I think backrest used to set `ssh -o "BatchMode yes"` as one of the options which minimizes log level for SSH and causes the process to fail immediately if no key is found (instead of dropping into an interactive mode).

**Comment by alexdelprete** [comment]
I'll add BatchMode yes to the MyNAS.config file, thanks for the suggestion.

Also many thanks for creating BackRest. I love it. The only concern I have is that for the average user, setting it up in passwordless SSH mode won't be an easy task. Hope they find this thread. :)

**Comment by alexdelprete** [comment]
Excellent idea George. :)

**Comment by Glideh** [comment]
Thanks @alexdelprete for pointing out the SFTP args.

I personally had this error using the `sftp.command` flag option

> cannot specify both sftp.command and sftp.args options

So I used the `sftp.args` one instead

```yml
{
  "id": "MyResticRepo",
  "uri": "sftp:MyServer:/backup",
  "flags": [
    "-o sftp.args=\"-F /ssh/config\""
  ]
# ...
}
```

**Comment by alexdelprete** [comment]
> personally had this error using the `sftp.command` flag option

I didn't use `sftp.args`. Makes sense they conflict though. :)

**Comment by Glideh** [comment]
So why didn't it conflict for you ?

**Comment by alexdelprete** [comment]
> So why didn't it conflict for you ?

Like I wrote before: I didn't use sftp.args, I only used sftp.command, so no conflict.

> Anyway `sftp.args` seems more straightforward for me

I prefer to specify the entire command.

**Comment by garethgeorge** [comment]
My familiarity with sftp and restic isn't the best (it's not something i use personally) -- just for my understanding, it sounds like you're both running into an issue where backrest doesn't detect sftp.command is provided and adds it's own `sftp.args` arguments which conflict with the command you're trying to run? 

Probably coming from these lines https://github.com/garethgeorge/backrest/blob/72cf45be83ee8e97c4c154874ffc34f0ee95a037/internal/orchestrator/repo/repo.go#L67-L72

It's possible there's something to fix here -- likely as easy as updating that condition to check for sftp.command's presence (not just sftp.args).

**Comment by alexdelprete** [comment]
> just for my understanding, it sounds like you're both running into an issue where backrest doesn't detect sftp.command is provided and adds it's own `sftp.args` arguments which conflict with the command you're trying to run?

Nope, I'm not having any conflict problem with this config:

```json
    {
      "id":  "ResticRepo",
      "uri":  "sftp:NAS:/backup/restic-repo",
      "env":  [
        "RESTIC_PASSWORD_FILE=/config/EnhanceBackup.pw"
      ],
      "flags":  [
        "--option sftp.command=\"ssh -F /config/NAS.config NAS -s sftp\""
      ],
      "prunePolicy":  {
        "maxFrequencyDays":  7,
        "maxUnusedPercent":  25
      }
    }
```

**Comment by alexdelprete** [comment]
Documentation is clear, `sftp.command` and `sftp.args` are _mutually exclusive_:

![image](https://github.com/garethgeorge/backrest/assets/7027842/5dc2d07a-a138-4d53-b0c2-a6745ff181c4)

**Comment by garethgeorge** [comment]
Ah, good. The behavior that the args are ignored if command is set sounds like the current behavior isn’t necessarily an error then, thanks for providing the docs snippet.

**Comment by Glideh** [comment]
Thanks for your answer @garethgeorge, I do have this conflict error only by specifying the `sftp.command` option (not with `sftp.args` like I said before @alexdelprete)

![image](https://github.com/garethgeorge/backrest/assets/1119270/39d2178f-04b3-4988-926b-7b299b55a30e)

I'm using the latest docker build from 11 days ago.
It's ok for me because I'm finally using `sftp.args` which I prefer since I don't need to rewrite the whole SSH command.

**Comment by alexdelprete** [comment]
> I'm using the latest docker build from 11 days ago.

Ok, I understand what's happening, I think:

- I thought you were using both sftp.command and sftp.args (my bad)
- I was using an "old" version, and I didn't notice this issue
- Now I've upgraded and I noticed the issue. So I reverted to sftp.args.

Problem is that while I bypassed the conflict issue (there's indeed a bug) by using sftp.args, upgrading to v1.1.0 is causing me many more severe issues: I can't complete any operation. :(

I tried starting backup manually:

```console
error: failed to initialize repo: init failed: command "/bin/restic-0.16.4 init --json --option sftp.args=-F /config/NAS.config NAS" failed: command "/bin/restic-0.16.4 init --json --option sftp.args=-F /config/OSILifeNAS.config NAS" failed: exit status 1
```

I logged into the container to test the command:

```console
backrest:/# /bin/restic-0.16.4 init --json --option sftp.args=-F /config/NAS.config NAS
Fatal: the init command expects no arguments, only options - please see `restic help init` for usage and flags
```

@garethgeorge Gareth, can you shed some light on this?

**Comment by alexdelprete** [comment]
Ok, it was the last parameter (NAS), that worked fine with sftp.command. Now I made a step ahead, but there's another issue:

```console
error: failed to get snapshots for plan: get snapshots for plan "EnhanceRemoteBackup": command "/bin/restic-0.16.4 snapshots --json --option sftp.args=-F /config/NAS.config --tag plan:EnhanceRemoteBackup,created-by:vps-backrest" failed: command output is not valid JSON: invalid character 's' looking for beginning of value
```

I ran the command from the container:

```
backrest:/# /bin/restic-0.16.4 snapshots --json --option sftp.args=-F /config/NAS.config --tag plan:EnhanceRemoteBackup,created-by:vps-backrest
Fatal: Please specify repository location (-r or --repository-file)
```

In the command output on the UI I see this:

```
error: failed to get snapshots for plan: get snapshots for plan "EnhanceRemoteBackup": command "/bin/restic-0.16.4 snapshots --json --option sftp.args=-F /config/NAS.config --tag plan:EnhanceRemoteBackup,created-by:vps-backrest" failed: command output is not valid JSON: invalid character 's' looking for beginning of value
```

Check and Prune works...backup doesn't.

**Comment by garethgeorge** [comment]
If providing custom SFTP args it's quite important that you still include batchmode in the flags. Any output printed by the SSH process breaks backrest's ability to parse the output from restic.

**Comment by alexdelprete** [comment]
> it's quite important that you still include batchmode in the flags

Wasn't that automatically added in case it's missing?

Anyway, I added it like this, is it ok?

`--option sftp.args="-F /config/OSILifeNAS.config -o BatchMode=yes"`

**Comment by alexdelprete** [comment]
Here's the error on the backup after adding batchmode option:

```console
error: failed to get snapshots for plan: get snapshots for plan "EnhanceRemoteBackup": command "/bin/restic-0.16.4 snapshots --json --option sftp.args=-F /config/NAS.config -o BatchMode=yes --tag plan:EnhanceRemoteBackup,created-by:vps-backrest" failed: command output is not valid JSON: invalid character 's' looking for beginning of value
Output:
subprocess ssh: Warning: Permanently added '[nas.domain.net]:2121' (ED25519) to the list of known hosts.
```

**Comment by alexdelprete** [comment]
> It's possible there's something to fix here -- likely as easy as updating that condition to check for sftp.command's presence (not just sftp.args).

Gareth, re-reading that docs section, sftp.args should simply ignored when sftp.command is also provided. So basically sftp.command prevales over sftp.args, but there should be no conflict error generated.

Also, from your code snippet, I see "sftp.args=-oBatchMode=yes" but shouldn't there be a space after the -o? "sftp.args=-o BatchMode=yes"

**Comment by garethgeorge** [comment]
Agreed -- if this is failing the operation it sounds like an inconsistency w/restic's behavior vs documentation. That said, we can definitely work around this in backrest.

Re: the formatting, I think ssh may be fine with or without the space there.

More broadly, this bug has me thinking a bit about how backrest should be doing it's output parsing from restic. I'll give some thought to improving my ability to capture and log non-JSON output before restic reaches the JSON (machine readable) part of it's status output. Ideally this is something that should be surfaced in the operation in the UI, but shouldn't necessarily fail the operation unless the JSON itself is missing, invalid, or the restic command exits with a non-zero status.

**Comment by alexdelprete** [comment]
I agree with you. Right now I don't have a clear understanding of why with latest versions of backrest my operations are failing.

I'll wait for updates in order to understand better. Thanks for the feedback.
