### ISSUE TITLE
Prune / Forget in backup job fails with error

### ISSUE THREAD

**Issue by ArjenR** [garethgeorge/backrest#167]
**Describe the bug**
Backup jobs fail in the prune stage with error:
failed: command output is not valid JSON: unexpected end of JSON input

**To Reproduce**
1. Build container. I use my Dockerfile with restic provided by alpine and backrest is installed within the container to prevent apparmor issues and to be able to create containers with versions of an application.
```
FROM alpine:latest

ARG ARCHITECTURE=Linux_x86_64
ARG RELEASE=v0.15.0
ARG REPOSITORY_URL=https://github.com/garethgeorge/backrest/releases/download

RUN apk --no-cache add ca-certificates curl bash openssh restic rclone tzdata && \
    mkdir -p /tmp

RUN (wget -O - ${REPOSITORY_URL}/${RELEASE}/backrest_${ARCHITECTURE}.tar.gz | tar -xzf - backrest -C /)

ENV BACKREST_RESTIC_COMMAND=/usr/bin/restic
ENTRYPOINT ["/backrest"]
```
2. Run backup job manually or by schedule.
3. Backup fase runs and completes.
5. Pruning stops immediately with the error:
```
error: forget: get snapshots for repo tank02: command "/usr/bin/restic forget --json --compression max -o sftp.args=-oBatchMode=yes --tag plan:<<my_plan>> --group-by tag" failed: command output is not valid JSON: unexpected end of JSON input
```
The path to the repository is missing in the command.

**Desktop (please complete the following information):**
 - OS: OpenSuse MicroOs
 - firefox, but not relevant
 - Backrest Version 0.15.0
 - restic version: restic 0.16.2 compiled with go1.21.8 on linux/amd64

**Additional context**
Manually running prune works and perfectly.

Running the command as it is in the error message results in:
`Fatal: Please specify repository location (-r or --repository-file)`

Adding `- r /<<path to my repository>>`  I am asked for the repository password. When the password is entered there is no message and the command ends without message.

**Comment by garethgeorge** [comment]
Hey, please update to the latest version (0.15.1) — this is a known issue that I put a patch out for.

**Comment by ArjenR** [comment]
Oops missed that. 

I (finally) found the url to be able to easily pull latest release instead of a specific version. Should make my life more easy. But why Github has a different url for latest and a specific version surprises me.

**Comment by ArjenR** [comment]
closing
