### ISSUE TITLE
SFTP backup: backup succeded, I can restore, but I can't find my files on remote server. Are they in the wrong place?

### ISSUE THREAD

**Issue by jeanpaulrh** [garethgeorge/backrest#169]
**Describe the bug**
I'm trying backrest to replace borg. So I setup a remote SFTP repository and tried to backup some files (200 Gb) to it.
After a few attempts (due to connectivity issues) the first backup completed.
I tried to start a new one and it completed in seconds, since no files were changed.
I tried to restore a file and it restored successfully.
So I log in to the remote server to find out how much space did the backup take and I couldn't find those files.
The repository is defined in this way:

`sftp://borg@192.168.3.3:/mnt/datastore/pbs-datastore/restic/al14`

So I would exprect to find my files in:
`/mnt/datastore/pbs-datastore/restic/al14`

Instead I found them under

`/home/borg/mnt/datastore/pbs-datastore/restic/al14`

Which is wrong to me since after the ip address and the : I have the full path beginning with '/'

**To Reproduce**
Create an SFTP repository, backup, find where files are stored on the remote host

**Expected behavior**
The path should be considered absolute if a '/' is find after 'user@host:'

**Desktop (please complete the following information):**
Backrest running on Freenas.
Backrest version 0.15.1

Edit: I tried to add the repository with a double slash at the beginning of the path and it seems to fix the problem.
I think it should be looked into anyway because the restic docs say that a single trailing slash identifies an absolute path.

**Comment by garethgeorge** [comment]
Hmm, I've seen some errors of this type recently. I think this is mostly a restic usage issue as backrest doesn't handle the URI -- it forwards it unchanged to restic.

But it is a goal of backrest to make this as useable as possible. If there's a good regex that captures correct sftp connection strings I'd be happy to add that to the UI's validation.

**Comment by jeanpaulrh** [comment]
I don't know... I was afraid it was restic fault and not yours... I read on restic docs [here](https://restic.readthedocs.io/en/v0.13.1/030_preparing_a_new_repo.html#sftp) that the syntax is `sftp:user@host:/srv/restic-repo ` but a little bit down I read also that when a non standrd port is used the syntax requires a double slash:
`sftp://user@[::1]:2222//srv/restic-repo`
So I suspect that even with the standard port 22 the same regexp is used by restic under the hood, hence the error.
Should I file a bug report in restic?

**Comment by garethgeorge** [comment]
Hmm, restic may not be using a regex at all, but this is a really strange limitation. I'm a bit unsure whether there's something to fix in backrest here, it sounds like there are two different modes in which restic is parsing the URL depending on whether slashes are prefixed (and both seem valid). From scanning through the related issues I'd not be confident w.r.t. adding validation to backrest as I suspect there's a lot of complexity w.r.t. what admissible URIs are. 

I think I'll probably leave the action item on this bug to be documentation related, I need to add a wiki section with guidance (and common pitfalls) for configuring each of the builtin config formats and probably rclone.
