### ISSUE TITLE
Does backrest support base_url?

### ISSUE THREAD

**Issue by gardiol** [garethgeorge/backrest#173]
I want to host backrest on my home server on a URL like 

`https://comsole.mydomain.com/backrest`

the raitonale is that i am putting all system-management related services behind the same sub-domain for logical organization and practical reasons.

Would backrest work or it must be hosted on root?

**Comment by garethgeorge** [comment]
Hey, backrest doesn't support but you might try using url rewriting to strip the prefix from your forwarded requests and see if backrest works, but I suspect you'll run into problems with the absolute path that backrest expects for the API here https://github.com/garethgeorge/backrest/blob/main/webui/src/api.ts#L27. If you do hit an error, give a ping here and I'll get out a PR to fix that to use a relative path which I'm hoping is the only change that's needed.

**Comment by garethgeorge** [comment]
Looks like there's a bit more to it, but I expect that https://github.com/garethgeorge/backrest/commit/ac7f24ed04679ed6cc3ea779325c0e0b49c9f526 will make backrest work happily regardless of the path you serve it at. All paths to its assets and for its API requests should be relative to its serving location in the next release.

**Comment by gardiol** [comment]
That's amazing! Thank you, eager to try!

**Comment by garethgeorge** [comment]
Available in latest release https://github.com/garethgeorge/backrest/releases v0.16.0 ! Give this bug a ping if you run into any issues

**Comment by gardiol** [comment]
Just tried it with the following NGINX setup (for future reference):


```
        location /backrest/ {
                proxy_pass http://127.0.0.1:9898/;
                proxy_set_header Connection $http_connection;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Host $host;
                proxy_set_header Authorization "";
        }
```

And it works perfectly!
Thank you, great job.
