### ISSUE TITLE
Strange authentication behaviour

### ISSUE THREAD

**Issue by gardiol** [garethgeorge/backrest#174]
On latest build. 
NGINX as simple reverse proxy:
```
       location / {
                proxy_pass http://127.0.0.1:9898/;
        }

```

I can access and i have created one user with password (name: myuser)

If i enable PAM authentication:
```
auth_pam "Nginx"; 
auth_pam_service_name "nginx";
       location / {
                proxy_pass http://127.0.0.1:9898/;
        }

```
(auth works just fine on all my other services)

When i login, assuming i login as "myuser", Backrest will keep asking username/password and bail out an 
`401Unauthorized`

asking again the login boxes.

I tried to disable authentication with the default/password approach, but nothing changes.

Maybe i am not passing correctly the headers?

**Comment by gardiol** [comment]
I can confirm that even passing the Authorization header properly, it doesnt recognize it. PRobably because of bearer.

**Comment by garethgeorge** [comment]
Next release will support disabling authentication: https://github.com/garethgeorge/backrest/commit/84291746af5fc863f90bcf7ae9ba5a2d3ca26cdd .

You can do this manually in your config by simply editing it and deleting the "auth" block to reset the auth config to default (the onboarding flow will run again and you'll get prompted to add users or disable auth entirely next time you reload backrest).

**Comment by gardiol** [comment]
That will be perfect, thank you!

**Comment by trexxeon** [comment]
I too very much appreciate the ability to turn off authentication

**Comment by garethgeorge** [comment]
Auth can now be disabled (as of 0.16.0), go to the settings panel and check "disable authentication".

**Comment by gardiol** [comment]
I have disable auth, in fact i deleted the auth section in the config json and let it recreate it. It now shows:
```
  "auth":  {
    "disabled":  true
  }
```

Unfortunately when i use it with reverse proxy authentication enabled, it still ask for login credentials. I have tried both with subpath and subdomain. I also tried to remove the Authorization header, but no avail.

Here is my nginx config:
```
        location /backrest/ {
                proxy_pass http://127.0.0.1:9898/;
                proxy_set_header Connection $http_connection;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Host $host;
                proxy_set_header Authorization "";
        }
```

(this is the same if i remove the subpath and use a dedicated subdomain)

 it works **without** using Reverse Proxy Auth, but them i have literally no authentication.
My guess is somewhere you are still checking the proxy headers?

The only header i see in my response is **WWW-Authenticate = Basic realm="MyRealm"** maybe you are reading it?

**Comment by gardiol** [comment]
After some further research, in case of a 401 if authroization is disabled you should not try to handle it but defer that to the browser. This was happening also on Silverbullet.md on a similar occasion . see https://github.com/silverbulletmd/silverbullet/issues/804

**Comment by gardiol** [comment]
It seems exactly the same issue as with silvetbullet. When on a sub-path it doesn't happen if you already signed in. Only on sundomain, because its then impossible to sign in from a non backrest page.
