### ISSUE TITLE
Rclone config missing

### ISSUE THREAD

**Issue by Albertowue** [garethgeorge/backrest#176]
Congratulations on the project, it is really great!!!
I use it with docker and the latest-alpine image because I need rclone (I use a cloud drive managed precisely with rclone).
The problem is that after a few hours rclone loses its configuration and then everything breaks!
I started the docker container, with the command 
`docker exec -it container_name bash` 
I created a rclone configuration (rclone config with all the steps, and it works). From the Backrest interface I created a repo "rclone:myremote:repos" and everything works perfectly....for a few hours, then backrest goes into error because the rclone config file no longer exists.
I expect i this behavior by updating the image, but it actually happened tonight without me making any changes. 
Also, how can I handle updating the docker image without losing the rclone configuration?

**Comment by Albertowue** [comment]
I think I've solved it:
In the compose file I inserted the directive
- volume:/root/.config/rclone

This way the folder where rclone saves the configuration is mounted inside the volume and thus saved permanently.
I hope this is the correct way.

**Comment by garethgeorge** [comment]
Yep! That's the right way for rclone, glad you were able to track down the problem.
