### ISSUE TITLE
Backrest server

### ISSUE THREAD

**Issue by bubbleg5** [garethgeorge/backrest#177]
I would like to propose this idea of mine.
In my office server I have no way to run software but I can only access in ssh/sftp or SMB. I would like to be able to access this server and back up my data. Currently Backrest does not allow me to access an external server, only the local storage where it is installed. It would be interesting to add the ability to access an sftp path, as is done now for repos.

**Comment by garethgeorge** [comment]
The underlying restic binary doesn't support remote filesystems (e.g. restic must run on the same host as your data). It's an interesting idea but I'm afraid it's probably out of scope for backrest's core feature set. 

I'd also like to avoid opening up complexity of managing restic on remote hosts where backrest isn't installed. It's not easy to solve the problem of SSHing into an arbitrary machine, detecting it's platform info / where a restic binary can be found, and running it reliably / parsing the output. Version incompatibilities and other issues will abound. 

A multihost version of backrest is in future work but it will still require that backrest is installed on each host to be backed up.
