### ISSUE TITLE
SFTP URI not available while using Backrest @Docker

### ISSUE THREAD

**Issue by KC-inDomus** [garethgeorge/backrest#182]
**Describe the bug**
While creating a repo with URI:

`sftp://admin@192.168.1.50:/backup/backrest_repo`

you got error:

`Operation failed: [unknown] failed to init repo: init failed: command "/data/restic-0.16.4 init --json" failed: exit status 1 Process STDOUT: Fatal: create repository at sftp://admin@192.168.1.50:/backup/backrest_repo failed: exec: "ssh": executable file not found in $PATH`

**Desktop (please complete the following information):**
 - OS: Linux Debian 12
 - Browser: Chrome
 - Backrest: 0.15.1

**Comment by garethgeorge** [comment]
I'll go ahead and mark this as resolved for now but please feel free to ping (or maybe move this to discussion section to better document the solution) if you're still running into issues.
