### ISSUE TITLE
A Bash Script to help Linux user install and update Backrest

### ISSUE THREAD

**Issue by Nebulosa-Cat** [garethgeorge/backrest#183]
It is a bit troublesome to update under Linux every time the version is updated, I wrote a script to facilitate the update and maintenance of Backrest.
(Because I'm not sure if this is suitable for commit, I thought it might be more appropriate to put it here.)
Currently there is no problem executing under Raspberry Pi 4b. More testing is needed for other platforms.

## Function
1. Install/Update Backrest
Automatically check the core version and pull the installation package from the latest version of Github and automatically decompress it to the `/home/user/backrest` directory. After the installation is completed, the directory and the corresponding installation package will be automatically deleted.

2. Uninstall Backrest
The current method is to download the corresponding core installation package, decompress it and execute the `uninstall.sh` inside.

3. Start/Stop/Status Backrest
Simple `sudo systemctl start/stop/status backrest`

## Bash Script URL
https://raw.githubusercontent.com/Nebulosa-Cat/Backrest-Helper/main/backrest-helper.sh

## Screen Shot
![image](https://github.com/garethgeorge/backrest/assets/30948446/bab68e63-7e40-44ac-82ae-4197ca8517a1)

**Comment by garethgeorge** [comment]
Neat script, thanks for sharing! You might also post this in the discussions section for better visibility.

I'd be happy to include something along these lines in the scripts folder of the main repo. I somewhat like the idea of actually making it less-interactive (e.g. the usage might look like `curl https://raw.githubusercontent.com/Nebulosa-Cat/Backrest-Helper/main/scripts/get.sh | bash -s`) the use case being a one liner to install Backrest.

w.r.t. native vs baremetal, I think it's mostly a dependency & sandboxing question. systemd comes included by default on many linux distro's today (though there's definitely some controversy about that! it's certainly common) so it's probably the easiest way to get started with backrest on an interactive linux desktop & it just works without any port, volume, etc configuration. Docker on the other hand makes a lot of sense for any kind of NAS install where you're already managing apps with docker and it'll provide the best sandboxing as you have the opportunity to _only_ mount volumes you want backed up into the container (and optionally in a read-only mode).

**Comment by Nebulosa-Cat** [comment]
> Neat script, thanks for sharing! You might also post this in the discussions section for better visibility.
> 
> I'd be happy to include something along these lines in the scripts folder of the main repo. I somewhat like the idea of actually making it less-interactive (e.g. the usage might look like `curl https://raw.githubusercontent.com/Nebulosa-Cat/Backrest-Helper/main/scripts/get.sh | bash -s`) the use case being a one liner to install Backrest.

It's my pleasure.

> 
> w.r.t. native vs baremetal, I think it's mostly a dependency & sandboxing question. systemd comes included by default on many linux distro's today (though there's definitely some controversy about that! it's certainly common) so it's probably the easiest way to get started with backrest on an interactive linux desktop & it just works without any port, volume, etc configuration. Docker on the other hand makes a lot of sense for any kind of NAS install where you're already managing apps with docker and it'll provide the best sandboxing as you have the opportunity to _only_ mount volumes you want backed up into the container (and optionally in a read-only mode).

in my case just because I pull both restic and rclon in baremetal xD, im just so lazy to reconfig all setting and migrate to docker enviroment

**Comment by Nebulosa-Cat** [comment]
But for security reasons, maybe I commit this script to repo will more safe then just quote from my repo?

**Comment by garethgeorge** [comment]
Yes, agreed from a security perspective! If you'd like to open a PR into the scripts directly I'll happily take it & make some modifications.

And baremetal is exactly how I'm using it on most of my systems for the same reason :) there's a big convenience factor if you're already working on the device directly (and backrest is very light on dependencies relative to a lot of software... it's really only restic that it depends on and it only creates files in a very small set of directories).

**Comment by Nebulosa-Cat** [comment]
> 是的，從安全角度來看同意！如果您想直接在腳本中開啟 PR，我會很樂意接受並進行一些修改。
> 
> 出於同樣的原因，裸機正是我在大多數系統上使用它的方式:)如果您已經直接在設備上工作，那麼會有一個很大的便利因素（並且靠背相對於許多軟體的依賴性非常小） ...它實際上只是依賴restic，並且它只在一個非常小的目錄集中創建文件）。

I submitted a PR. This is the first time I have officially submitted a feature to a public project on Github. I hope that the way I submit it complies with the regulations of `Conventional Commits`.

**Comment by garethgeorge** [comment]
Thanks for contributing this! Reviewed and merged.
