### ISSUE TITLE
Cannot set retention settings to "0" hourly

### ISSUE THREAD

**Issue by ovizii** [garethgeorge/backrest#185]
**Describe the bug**
Cannot set retention settings to hourly = “0” 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to backrest
2. Edit a plan
3. Change “hourly to 0”
4. Submit settings
5. Edit the same plan and see hourly is back to 24

**Expected behaviour**
Let me chose 0 for hourly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome
 - Backrest Version 0.16.0

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/commit/7e9bf15976006c7f3ff96948d2b2c291737c9e88, will be included with the next release.
