### ISSUE TITLE
Raspberry\Armv7 Version

### ISSUE THREAD

**Issue by jaketails** [garethgeorge/backrest#192]
Could you plan to release a version that runs on Docker on Raspberry Pi? Since during installation, if the repo "garethgeorge/backrest:latest-alpine" is provided it cannot identify an ARMv7 compatible version.

**Comment by garethgeorge** [comment]
Hey, try running the garethgeorge/backrest:scratch tag

**Comment by dirk2011** [comment]
I instlalled this docker container: garethgeorge/backrest:v0.16.0 no issues.

**Comment by garethgeorge** [comment]
Thanks @dirk2011 for the confirmation re: Raspberry Pi 5 (I don't have a test device handy). I'll go ahead and mark this as resolved for now.
