### ISSUE TITLE
Consider defaulting listen address to loopback instead of all interfaces

### ISSUE THREAD

**Issue by johnmaguire** [garethgeorge/backrest#198]
**Is your feature request related to a problem? Please describe.**
When backrest is first started, it uses a trust-on-first-use model to add users. After that point, you must login to access the UI, unless you disable auth.

<img width="761" alt="Screenshot 2024-04-05 at 11 18 24 AM" src="https://github.com/garethgeorge/backrest/assets/440033/db6e1600-cb12-479f-87dd-a23e8c664f1d">

While most home routers contain a firewall that would require port forwarding to expose the service, it may be still available to other potentially malicious devices on the LAN (e.g. at a coffee shop, or due to a compromised IoT device.) Considering the high value of backups, I think it is a good idea to ensure the service is secure.

**Describe the solution you'd like**

I suspect there are two users of backrest: those who will access backrest on a remote server (possibly over a tunnel like Wireguard, or through a proxy, like oauth2-proxy, etc.) and those who are using it for local backups.

I would argue that the former is more technically savvy and able to make a change to the default configuration to allow the service to listen on the required interfaces/addresses. The latter is likely to be unfamiliar with this type of setup. For that reason, I suggest making backrest listen only on loopback (e.g. 127.0.0.1) by default.

**Additional context**

```
  -bind-address string
    	address to bind to, defaults to :9898. Use 127.0.0.1:9898 to listen only on localhost. Overrides BACKREST_PORT environment variable.
```

**Comment by garethgeorge** [comment]
This is a really good point on security.

One way to address this quite reasonably might be to do it in the installer, I can update the MacOS (launchd) and Linux (systemd) install scripts to set BACKREST_PORT by default where as it might be reasonable to expect that a dockerized install typically wants to listen on all interfaces?

WDYT?

**Comment by johnmaguire** [comment]
@garethgeorge Makes a lot of sense to me! With Docker, I believe users would have to set `network_mode: host` or add a `publish` for the port in order for it to become a concern - and the user would be opting in at that point.

The only downside to doing it in the plist/unit is that if the user writes their own service script / runs it manually through some other method, they will need to be aware and configure it manually. So I think I still have a mild preference for having the code default to localhost, and using config to expose it to all interfaces. I suspect either solution would improve the 99% case though!

**Comment by zaggash** [comment]
Fixed with https://github.com/garethgeorge/backrest/commit/eb07230cc0843643406fa44ca21c3a138baced77
