### ISSUE TITLE
Proposal: Telegram Hook

### ISSUE THREAD

**Issue by lucas27-01** [garethgeorge/backrest#205]
Hi, I would like to use Telegram as notification service, but at now it is not supported by Backrest.

I offer myself to implement this if you hear about, in Go as written in your guidelines, using a bot, as written in their [official docs](https://core.telegram.org/bots).

I'll wait any response, in hopes someone or I will can do that...

**Comment by johnmaguire** [comment]
Shoutrrr support was added in v0.16.0 and it looks like Shoutrrr may support Telegram: https://containrrr.dev/shoutrrr/v0.4/services/telegram/

Have you given it a try?

**Comment by lucas27-01** [comment]
I was using an older version of backrest so I didn't see it...
Excuse me... I certain will use it...

**Comment by lucas27-01** [comment]
I was using an older version of backrest so I didn't see it...
Excuse me... I certain will use it...
