### ISSUE TITLE
Support for timezone environment variable in docker image

### ISSUE THREAD

**Issue by thinkbig1979** [garethgeorge/backrest#207]
Having backrest be set to my local timezone would be great and make it easier to schedule backup times without worrying about the difference between local time and UTC.

**Comment by def324** [comment]
A generic solution to this on linux would be to mount the local timezone into the container with something like this in a docker-compose format:

```
volumes:
      - '/etc/localtime:/etc/localtime:ro'
```

This doesn't fix the actual request but might be good enough in a number of occasions.

**Comment by garethgeorge** [comment]
Hey, the TZ env variable is supported in the `garethgeorge/backrest:latest` image (but not in the scratch image -- please make sure you're on alpine).

Set (for example)
```
TZ=America/Los_Angeles
```
in your env variables

**Comment by thinkbig1979** [comment]
Many Thanks!
