### ISSUE TITLE
update docs to reflect that versions of Backrest >0.17.1 only listen on localhost

### ISSUE THREAD

**Issue by edersong** [garethgeorge/backrest#216]
Note: if you have a question please post in the [discussions area](https://github.com/garethgeorge/backrest/wiki).

**Describe the bug**
After upgrade to v0.17.1, backrest UI is not opening thru <IP>:9898 

**To Reproduce**
1. Upgrade Backrest
2. Try to open the UI thru a browser

**Expected behavior**
Open UI

**Desktop (please complete the following information):**
 - OS: Linux x86_64 and arm64
 - Browser: any
 - Backrest Version 0.17.1

**Additional context**
Logs shows the webserver running `INFO        starting web server 127.0.0.1:9898 `

**Comment by lzecca78** [comment]
given [this](https://github.com/garethgeorge/backrest/commit/eb07230cc0843643406fa44ca21c3a138baced77) now the default listen is to 127.0.0.1 instead of 0.0.0.0 . But you can change that env var accordingly to your needs.

**Comment by edersong** [comment]
Thanks for the feedback, @lzecca78 
But I'm saying about a Linux server install, not docker install.

**Comment by garethgeorge** [comment]
Oops, I'll update the release notes. Some got dropped as I had to do a rerun of the release with some patches last night. 

In the latest version all backrest installs using the script default to localhost for security -- I was worried that laptop users will roam wifi networks with open ports on their laptops without realizing backrest needs to be secured.

**Comment by garethgeorge** [comment]
Just went ahead and updated the release notes to include all of the relevant changes from the skipped release.

**Comment by edersong** [comment]
Hello, @garethgeorge 
Thanks for the update.
How could I run it back using  0.0.0.0:9898 instead of the new default 127.0.0.1:9898 when needed?

**Comment by zaggash** [comment]
For docker, you need to setup the env var : `BACKREST_PORT=0.0.0.0:9898` 

Or for systemd : `Environment="BACKREST_PORT=0.0.0.0:9898"`

Using the binary you need to set the argument: `-bind-address 0.0.0.0:9898`

**Comment by davide93** [comment]
> Hello, @garethgeorge Thanks for the update. How could I run it back using 0.0.0.0:9898 instead of the new default 127.0.0.1:9898 when needed?

You can edit install.sh and change line 30 to Environment="BACKREST_PORT=0.0.0.0:9898" then install it.

**Comment by garethgeorge** [comment]
Going to go ahead and close this as this has been the default behavior for a while now. Thanks all for posting workarounds on here.
