### ISSUE TITLE
install.sh  needs a  chmod u+x /usr/local/bin/backrest

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#219]
After installing by install.sh  the service is not able to start.
Tested with version 0.17.1 on linux debian bookworm

**Comment by garethgeorge** [comment]
Strange, usually `tar -xzf` is setting the executable bits on the binary file I think. Is that not happening in your case?

Either way this is a good call out, it's worth doing in the script as well to be robust.

**Comment by berti34** [comment]
Yes, I had to do that manually because the service wasn't starting.

**Comment by berti34** [comment]
So, I've tested the way 
tar -xvf backrest_Linux_arm64.tar.gz 
and it works fine.

Thank you anyway for the good tool!
