### ISSUE TITLE
Not able to connect to S3 MinIO without TLS

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#220]
I have a problem to configure a connection to a local MinIO-S3 without TLS.

I tried s3://192.168..../restic
and got an error message that the S3 answered HTTP instead of HTTPS.

Trying s3://http://192.168.../restic  gives an error that the repository is missing.

Is there an other way to do that?

Version 0.17.1 on Arm64 Debian Bookworm

**Comment by garethgeorge** [comment]
Hey, see https://github.com/restic/restic/issues/2656 for a few workarounds.

**Comment by berti34** [comment]
I made it with haproxy. Thank you anyway.
