### ISSUE TITLE
ARMv7 Docker image

### ISSUE THREAD

**Issue by KC-inDomus** [garethgeorge/backrest#222]
**Is your feature request related to a problem? Please describe.**
Looking [here](https://hub.docker.com/r/garethgeorge/backrest/tags) seems like ARMv7 version is not available.
This version may be really appreciated.

**Comment by garethgeorge** [comment]
Hey, do you have a device in mind that uses armv7 but isn't backwards compatible with armv6? My understanding is that most armv7 devices can also run armv6.

**Comment by KC-inDomus** [comment]
> Hey, do you have a device in mind that uses armv7 but isn't backwards compatible with armv6? My understanding is that most armv7 devices can also run armv6.

Sure: Sonoff iHost 👍 (indeed the one where I was trying to adopt Backrest)

**Comment by garethgeorge** [comment]
Ah, interesting. Looks like the binary is the same, but the docker containers probably still need to match the architecture. That was confusing me since restic also only publishes a single arm32 binary :).

I'll get one published for you.

**Comment by KC-inDomus** [comment]
That's GREAT. Thanks @garethgeorge, so we gonna publishi a Backrest@iHost guide @ indomus.it very soon.

**Comment by garethgeorge** [comment]
Great to hear it ! 

Added in https://github.com/garethgeorge/backrest/commit/ec39533e4cddf2f0354ec3fcb4c52ba37a9b00ec , will be available with the next release in the `garethgeorge/backrest:scratch` image.

**Comment by garethgeorge** [comment]
Should be published in the latest patch release (0.17.2), I don't have a test device so please try it out and let me know if that's working on your end!

**Comment by KC-inDomus** [comment]
Hi there, seen the latest release, 0.17.2. Still not working on Sonoff iHost, probably becouse it searches for v7 version on `[latest](https://hub.docker.com/layers/garethgeorge/backrest/latest/images/sha256-edadd40416042ae69c6908f298fa56342b8d7f458abe11696329d37c42104368?context=explore)` tagged image, which has "only" amd64 and arm64 builds. :/

**Comment by garethgeorge** [comment]
Ah, I probably should have clarified -- are you using `garethgeorge/backrest:scratch` ?

**Comment by KC-inDomus** [comment]
in a matter of fact, on iHost you can't choose which tagged image to be used. see attached image: you only can choose docker hub repository, so I assume he uses "latest" tagged one.

<img width="560" alt="Screenshot 2024-04-18 at 09 22 22" src="https://github.com/garethgeorge/backrest/assets/52242036/68d03c1b-58b2-4f81-aaa0-d3b5aa4de820">

**Comment by KC-inDomus** [comment]
hi @garethgeorge, any idea about when "latest" image will contain arm7 support? since then, iHost users won't be able to use backrest...

**Comment by garethgeorge** [comment]
Hi @KC-inDomus sorry, armv7 support isn't likely for the latest image. It's built on alpine linux and uses a number of packages that I don't guarantee support for on other architectures.

Only the scratch image (`garethgeorge/backrest:scratch`) is intended to support all docker supported architectures.

iHost needs some work around on the product's end to be able to select a docker tag (defaulting to supporting latest only isn't a good practice).
