### ISSUE TITLE
Support pkl format

### ISSUE THREAD

**Issue by asm0dey** [garethgeorge/backrest#229]
**Is your feature request related to a problem? Please describe.**

In a way. I have a lot of similar configurations, for example, I have multiple WordPress sites on one host, and the template for them is very similar. I want to make my configuration easier to write without too much duplication.

**Describe the solution you'd like**

The pkl language (https://pkl-lang.org/index.html) allows all kinds of features one may need, and it can be easily translated to json (`pkl eval -f json backup.pkl`), but also it has a native Go support (https://github.com/apple/pkl-go)

Of course, if implemented, it would be a feature for advanced users, still might be helpful.

**Comment by garethgeorge** [comment]
Hey, can you elaborate a bit on the feature request? I think pkl is supported today by generating a JSON config usable with backrest (structure is documented by https://github.com/garethgeorge/backrest/blob/main/proto/v1/config.proto). 

That should be loadable today (though you'll need to restart backrest to import any config changes on disk). You'll get into weird states if you continue to edit the config through the UI -- I could see implementing support for locking configuration in the UI if you want to manage it programatically.

**Comment by asm0dey** [comment]
Well, probably with what I mean by support is providing of a sharp library with classes with which backrest currently works. It will be like a schema which one can import into their actual pkl config for further json generation. And yes, I see how it breaks the UI editability and I'm ready to sacrifice it actually

**Comment by garethgeorge** [comment]
If there's a pkl generator for protoc I'd be happy to publish some typings for pkl , I'm not seeing any at the moment (but it sounds like a missing pkl ecosystem component if it's something you're interested in!) but I'll set it up if you can point me to one that's maintained. 

Afraid pkl typings aren't something I'm likely to keep up to date / maintain if doing it manually. Happy to point to an OSS repo in the docs / wiki if you'd like to publish one.

**Comment by asm0dey** [comment]
Thank you. I agree that supporting two type systems is cumbersome. I don't
know any protoc-> pkl and frankly I didn't know about protoc.

Please, feel free to close this feature request and I'll reopen it if find
anything usable.

**Comment by asm0dey** [comment]
What is interesting is the fact that potentially you can migrate from
protobuf to pkl without the loss of compatibility, there is an experimental
support of protobuf in pkl:
https://pkl-lang.org/package-docs/pkl/0.25.3/protobuf/Renderer.html

Maybe one day :)

**Comment by garethgeorge** [comment]
Thanks -- going ahead and closing this for now, I'll be interested if the project makes progress w/more integrations.

**Comment by asm0dey** [comment]
For those who will come here from Google:

Here is the generated pkl, obtained by proto → json schema → pkl generation:

```pkl
module ConfigSchema

/// Hook
class V1Hook {
  conditions: Listing<
      "CONDITION_UNKNOWN"
      |"CONDITION_ANY_ERROR"
      |"CONDITION_SNAPSHOT_START"
      |"CONDITION_SNAPSHOT_END"
      |"CONDITION_SNAPSHOT_ERROR">?

  /// OnError
  on_error: ("ON_ERROR_IGNORE"|"ON_ERROR_CANCEL"|"ON_ERROR_FATAL")?

  /// Command
  action_command: ActionCommand?

  /// Webhook
  action_webhook: ActionWebhook?

  /// Discord
  action_discord: ActionDiscord?

  /// Gotify
  action_gotify: ActionGotify?

  /// Slack
  action_slack: ActionSlack?

  /// Shoutrrr
  action_shoutrrr: ActionShoutrrr?
}

/// Command
class ActionCommand {
  command: String?
}

/// Webhook
class ActionWebhook {
  webhook_url: String?

  /// Method
  method: ("UNKNOWN"|"GET"|"POST")?

  template: String?
}

/// Discord
class ActionDiscord {
  webhook_url: String?

  template: String?
}

/// Gotify
class ActionGotify {
  base_url: String?

  token: String?

  template: String?

  title_template: String?
}

/// Slack
class ActionSlack {
  webhook_url: String?

  template: String?
}

/// Shoutrrr
class ActionShoutrrr {
  shoutrrr_url: String?

  template: String?
}

/// Config
class V1Config {
  modno: Int32 = 7

  version: Int32 = 1

  host: String?

  repos: Listing<V1Repo>?

  plans: Listing<V1Plan>?

  auth: V1Auth?
}

/// Repo
class V1Repo {
  id: String?

  uri: String?

  password: String?

  env: Listing<String>?

  flags: Listing<String>?

  prune_policy: V1PrunePolicy?

  hooks: Listing<V1Hook>?

  auto_unlock: Boolean?
}

/// Plan
class V1Plan {
  id: String?

  repo: String?

  disabled: Boolean?

  paths: Listing<String>?

  excludes: Listing<String>?

  iexcludes: Listing<String>?

  cron: String?

  retention: V1RetentionPolicy?

  hooks: Listing<V1Hook>?

  backup_flags: Listing<String>?
}

/// RetentionPolicy
class V1RetentionPolicy {
  max_unused_limit: String?

  keep_last_n: Int32?

  keep_hourly: Int32?

  keep_daily: Int32?

  keep_weekly: Int32?

  keep_monthly: Int32?

  keep_yearly: Int32?

  keep_within_duration: String?

  policy_keep_last_n: Int32?

  /// TimeBucketedCounts
  policy_time_bucketed: PolicyTimeBucketed?

  policy_keep_all: Boolean?
}

/// TimeBucketedCounts
class PolicyTimeBucketed {
  hourly: Int32?

  daily: Int32?

  weekly: Int32?

  monthly: Int32?

  yearly: Int32?
}

/// PrunePolicy
class V1PrunePolicy {
  max_frequency_days: Int32?

  max_unused_percent: Int32?

  max_unused_bytes: Int32?
}

/// Auth
class V1Auth {
  disabled: Boolean?

  users: Listing<V1User>?
}

/// User
class V1User {
  name: String?

  password_bcrypt: String?
}
```

Probably one will want to tune the nullability of types to their needs
