### ISSUE TITLE
Allow for 'restore latest'

### ISSUE THREAD

**Issue by zz0rk** [garethgeorge/backrest#234]
Note: if you have a question or want discussion please post in the [discussions area](https://github.com/garethgeorge/backrest/wiki).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
N/A

**Describe the solution you'd like**
restic restore allows for a full snapshot/backup restore using 'restore latest'. Could the same be implemented in Backrest?

**Additional context**
Add an option under 'Browse and Restore Files in Backup' to select and run a full 'restore latest', e.g. 'Restore Latest' [checkbox] Run.

![image](https://github.com/garethgeorge/backrest/assets/18619265/3d3eefab-fca4-4276-b1f2-0da534c8890c)

**Comment by zz0rk** [comment]
I am new to Backrest and restic for that matter, so I may be missing something.

This would restore the latest backup (all files/folders)
restic -r /mnt/backup/restic/5520/full_system/ restore latest --target /tmp/5520

In Backrest I only see the option to restore/browse individual files/folders one at a time but not restore the complee backup all at once.
![image](https://github.com/garethgeorge/backrest/assets/18619265/178db74e-348f-4ef0-96ee-4092ac6042c2)

**Comment by garethgeorge** [comment]
Ah, I see — sounds like the major problem is that there isn’t a single button to restore the whole snapshot. I’ll aim to fix this by inserting an extra directory node for the root of the backup tree `/`

**Comment by zz0rk** [comment]
> inserting an extra directory node for the root of the backup tree `/`

Excellent, thank you!

**Comment by garethgeorge** [comment]
Addressed in https://github.com/garethgeorge/backrest/commit/6045c87cdf5a68afd81203602ee5827eda5af8e7
