### ISSUE TITLE
container losing all configurations when stopping and starting

### ISSUE THREAD

**Issue by Microices** [garethgeorge/backrest#235]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/wiki).

**Describe the bug**
Losing plans and repositories when performing docker image updates.

**To Reproduce**
Stop container, 
pull new build
deploy new build

**Expected behavior**
updating the contianer should not lose any files.

**Screenshots**

**Platform Info**
- docker using portainer on dietpi

**Additional context**

**Comment by Microices** [comment]
could you tell me whats wrong with my compose file?

version: "3.2"
services:
  backrest:
    image: garethgeorge/backrest
    container_name: backrest
    hostname: pi4b_backrest #Use this to set the hostname instead of container ID to the config.json and WebUI.
    volumes:
      - /home/XXX/dockerconfig/backrest/data:/data
      - /home/XXX/dockerconfig/backrest/config:/config
      - /home/XXX/dockerconfig/backrest/cache:/cache
      - /mnt/bigdata:/bigdata
      - /mnt/smalldata:/smalldata
    environment:
      - /home/XXX/dockerconfig/backrest/data:/data # path for backrest data. restic binary and the database are placed here.
      - /home/XXX/dockerconfig/backrest/config:/config/config.json # path for the backrest config file.
      - /home/XXX/dockerconfig/backrest/cache:/cache # path for the restic cache which greatly improves performance.
    restart: unless-stopped
    ports:
      - 9898:9898

**Comment by garethgeorge** [comment]
Your environment variables for are set incorrectly, you should leave those as the defaults in the docker compose example.

**Comment by Microices** [comment]
Oh man, completely messed that up. thanks.
