### ISSUE TITLE
warning does not trigger the right hook?

### ISSUE THREAD

**Issue by lakemike** [garethgeorge/backrest#236]
Ony of my backups threw a warning "Partial backup, some files may not have been read completely". See first screenshot.

I thought it would trigger the hook with error conditions, but it did not. 
See second screenshot.

Any advice what to do? Is this a bug?
<img width="526" alt="1" src="https://github.com/garethgeorge/backrest/assets/62221234/36ee1278-aa8c-4965-b270-04fcfa3b1c3a">
<img width="384" alt="2" src="https://github.com/garethgeorge/backrest/assets/62221234/2df2db3b-6800-4bf2-8261-ed65e308d7b2">

**Comment by garethgeorge** [comment]
Thanks for the report, this is actually something I've given a bit of thought here so it's pretty interesting to hear what user expectations are

Originally this was an error, in a recent update I downgraded the warning to not trigger error notifications, but I'm weakly opinionated about what the right thing to do here is.

**Would people generally prefer a conservative (e.g. only notify on an actual error) or an aggressive (notify on warnings) approach here.**

On platforms where these warnings are uncommon, an error is probably what you want. The error typically indicates that either a file was modified while restic read it (e.g. common with database files like a sqlite db) OR that restic wasn't able to read the file for some reason (e.g. insufficient permissions). On other setups where I just want restic to "try it's best" I'd rather not get warning spam even though warnings frequently occur (e.g. on my Windows install restic often fails to read random files in app data directories -- that probably don't matter much to me in any case).

The right answer might be a new condition e.g.`CONDITION_ANY_WARNING` or such to make this fully configurable.

**Comment by lakemike** [comment]
I figured out the error relates to a file system problem. Not a small issue potentially, and I would like to be able to act on this in a timely issue when it comes up.

Hence..

..regarding your question, I would love having another condition for a warning. This would allow me to display it and ultimately act on it.

**Comment by garethgeorge** [comment]
Improved in 1.2.0 with the addition of a number of new conditions for snapshots

<img width="735" alt="image" src="https://github.com/garethgeorge/backrest/assets/7906572/2a316c59-75de-4964-9811-4bf6fb4f620d">

 * CONDITION_SNAPSHOT_END - runs after any snapshot operation irrespective of result
 * CONDITION_SNAPSHOT_WARNING - runs on a completed snapshot with a warning status
 * CONDITION_SNAPSHOT_ERROR - runs on a failed snapshot operation
 * CONDITION_SNAPSHOT_SUCCESS - runs after a successful snapshot operation
