### ISSUE TITLE
Add option to download file from web UI

### ISSUE THREAD

**Issue by wookash** [garethgeorge/backrest#237]
Would it be possible to add option to download file from the web browser as additional feature to restoring to the selected path?

**Comment by garethgeorge** [comment]
sounds reasonable, likely will implement this such that you first restore to a specific location but will enable downloading files from the restored location (e.g from a button on the restore operation in the Backrest UI).

**Comment by garethgeorge** [comment]
now implemented since 1.0.0, marking complete.

**Comment by wookash** [comment]
I confirm it works. thank you!
