### ISSUE TITLE
Paths field doesn`t support multiple paths

### ISSUE THREAD

**Issue by dm9tr0** [garethgeorge/backrest#239]
This will not be working
<img width="632" alt="image" src="https://github.com/garethgeorge/backrest/assets/17461617/8e206fe2-f59d-4de9-926c-dfcf637d7bae">

This will be working
<img width="639" alt="image" src="https://github.com/garethgeorge/backrest/assets/17461617/dabde89f-e9f5-4f8d-81fc-8b2f2feeaf6d">

Little incontinency, because by default when I run restic from CLI I can mention all paths, if I see 'Path**s**' field - I expected the same behavior 
`restic backup -v --read-concurrency 12 --no-scan --compression auto /Users/user/Documents /Users/user/Downloads /Users/user/Movies` 

Possible solution from my view:
1. Rename field
2. Add popup example to each field (probably best option overall and don`t need to update wiki)
3. Add validation by regex that if there is space - show some red warning

Also, have no idea such flags will be working or not:
<img width="634" alt="image" src="https://github.com/garethgeorge/backrest/assets/17461617/86ef362b-4b72-4b85-ad43-9749e2508be2">

Thanks a lot author for such awesome UI!

**Comment by garethgeorge** [comment]
hey, happy to take a PR if you think there are clarifications to add to the tooltips! I don't think a rename / regex would quite be correct, I think current behavior is WAI but it sounds like there's some possibility for confusion around how it's parsed

just to clarify here --

 Paths are appended directly to argv for restic (so it's safe to have spaces / symbols in your paths)
 
 Flags are handled by shlex so they receive some parsing e.g. to more closely match how they'd be handled by the CLI (and the parsed flags are then extended to argv). Logically I'd recommend using multiple entries in flags for multiple flags, but you don't explicitly need to. You can get away with one.
