### ISSUE TITLE
24 hours instead of AM / PM

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#246]
The WebUI shows date and time in 12 hours format:
2024-04-24 at 12:30:17 AM - ....
That is 0:30:17 in the morning. That confuses when in a hurry...

How can I switch to get the 24 hours format?

I'm using Backrest 0.17.2 on many different Linux and Windows systems as binary.

**Comment by berti34** [comment]
Hi again! Do you think you can add that switch to the settings e.g. in version 1.0.0 maybe? 
Greetings
Berthold

**Comment by garethgeorge** [comment]
Hey, looks like the browser provides an internationalized date time formatting API https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

I think using this in https://github.com/garethgeorge/backrest/blob/main/webui/src/lib/formatting.ts#L20-L36 should be the right approach.

**Comment by kinghat** [comment]
im not sure if this is related. if not i can open a separate issue. i have the plan schedule set to the default: `0:0` time:

![image](https://github.com/garethgeorge/backrest/assets/16073360/204df323-626d-4302-8a6a-1c2447ecb0f5)

with the config of:

```json
  "cron": "0 0 * * *",
```

but in the plans tree view it says its scheduled for `7:00:00 PM`:

![image](https://github.com/garethgeorge/backrest/assets/16073360/7d6cb7a3-13ac-47b3-bd8c-a2af5999b137)

**Comment by garethgeorge** [comment]
Are you using docker? This tends to happen when the timezone in the container is incorrect.

**Comment by kinghat** [comment]
> Are you using docker? This tends to happen when the timezone in the container is incorrect.

yep, that makes sense. i think the linuxserver containers use this in their compose but not sure if `TZ` is something special to them:

```yaml
    environment:
      - TZ=US/East
```

and the forgejo container mounts these volumes in compose:

```yaml
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

**Comment by garethgeorge** [comment]
Yep! For backrest I think just setting the TZ variable should be enough. It’s handled by the tzdata alpine package added to the docked image.

**Comment by garethgeorge** [comment]
https://github.com/garethgeorge/backrest/commit/89a49c1fa7c6cafedef30bdf695e76920e2c690c updates the time formatting to use the locale.

**Comment by berti34** [comment]
> Are you using docker? This tends to happen when the timezone in the container is incorrect.

No, just the binary version on Arm64, AMD64 and Windows 10.

**Comment by garethgeorge** [comment]
Just released 1.0.0 which will try to use the locale from your browser, let me know if that's working for you.

**Comment by modem** [comment]
For me still shows AM and PM:

![image](https://github.com/garethgeorge/backrest/assets/62859/c8e022d3-0b26-4bf0-ac0b-c357dfe2c847)

I have TZ set on the environment variables
```
    environment:
      - TZ=Europe/Lisbon
```

Is there any other change needed?

**Comment by modem** [comment]
I'm on docker.

**Comment by kinghat** [comment]
> I'm on docker.

try clearing your browser cache.

**Comment by garethgeorge** [comment]
The setting is based on your browser's locale for time formatting.

**Comment by modem** [comment]
I see it now, but it does not make sense to me. I have my browser language set to US English but there's no place to define the regional settings. And in fact this is the only software I access in the browser where I see this behavior. If we define the TZ environment variable, Backrest should stick to that instead of the browser settings.

**Comment by libeanim** [comment]
I have a similar problem, the browser locale seems sometimes inconsistent.
My system is US English, but I selected Germany as region, meaning my system shows everything in 24h:
<img width="470" alt="Screenshot 2024-05-22 at 08 34 14" src="https://github.com/garethgeorge/backrest/assets/1412303/d7c34379-f839-4df9-8d21-08d6de662e7c">
Also my broswer has German and locale Germany as preferred language for websites:
<img width="708" alt="Screenshot 2024-05-22 at 08 35 08" src="https://github.com/garethgeorge/backrest/assets/1412303/e793d432-bc6d-4039-b3bd-52ed8a076c54">

Yet on backrest its still AM and PM, it only works if I manually override the locale in the dev console. Then its in 24h.
See https://stackoverflow.com/a/69149258

I guess its a minor issue and I am not sure if this is a browser bug or with backrest.

**Comment by modem** [comment]
I use Firefox and I don't find any setting to define the region, only the language. But I prefer the language set to english than to my mother language.

**Comment by berti34** [comment]
Fore me it works as expected, so I can close this ticket.
Thanks

**Comment by XhmikosR** [comment]
In my case backrest is indeed using the browser language but not my system regional options for date and time.

<img width="2737" height="1682" alt="Image" src="https://github.com/user-attachments/assets/487a83db-4f67-4333-8f5c-ca0d1def1f9f" />

---

<img width="428" height="328" alt="Image" src="https://github.com/user-attachments/assets/1c463e41-9f62-4fba-b9d1-bb4cf8492276" />

I can live with it, I just find it inconsistent personally. @garethgeorge should I create a new issue?

**Comment by garethgeorge** [comment]
Backrest should be using whatever your browser's local preferences are for dates / times. Is your browser's locale set to match the system?

**Comment by XhmikosR** [comment]
Yeah, it's English US. But my system's regional format is Greek.

**Comment by garethgeorge** [comment]
Hmm, can you elaborate a bit on the behavior you're expecting? Backrest should be using your browser's preferences.

**Comment by MagicalCrib** [comment]
This has already been discussed last year. 
The thing is many people are not from English speaking countries, but they prefer to set the browser to English, while their OS is using English or they native language. Either way, regional settings can be changed in OS to user's preference, but not the browser. 
And this is the point here, browser seems to set clock to 12h for English while users prefer 24h.

Last year someone suggested to use the TZ environment variable (https://github.com/garethgeorge/backrest/issues/246#issuecomment-2099219835), and you confirmed tzdata would handle it (https://github.com/garethgeorge/backrest/issues/246#issuecomment-2099656798), but then you mentioned Backrest is using local from browser, which provides no customization. 
By default, Backrest can use Browser settings, but should allow users to change this setting to their like.

Using tzdata seems to be more reliable and customizable, matching what several other docker images are using, mainly the ones from linuxserver.

**Comment by XhmikosR** [comment]
Yeah, exactly as @modem described it above. I'm on Windows, so I'm unsure if this is the same on other OS'es. But it definitely looks weird (see my comment above https://github.com/garethgeorge/backrest/issues/246#issuecomment-3254049497)
