### ISSUE TITLE
Retention policy should respect hostname

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#247]
It appears that the retention policy of a plan results in the deletion of snapshots from other servers when utilizing a centralized restic rest server.

How can I configure the "forget" jobs to respect the hostname, so that snapshots from other hosts will not get removed?

**Comment by berti34** [comment]
The forget job depends on the "plan"- name. So I attached the hostname to the "plan" name - and it works as expected.
Maybe this should be documented more explicitly in the forget documentation here: 
https://garethgeorge.github.io/backrest/docs/operations#forget

**Comment by garethgeorge** [comment]
hey, actually going ahead and reopening this — sorry for not commenting earlier. Glad you found a workaround! 

As I look towards better support for multi-host management this is something I’ll want to fix, will track here.

**Comment by garethgeorge** [comment]
Will be addressed by https://github.com/garethgeorge/backrest/pull/256 , this is looking likely to be a change that requires user intervention to set a hostname for their installs. Saving it for the 1.0.0 release.
