### ISSUE TITLE
Prune operations not cleared automatically from plan history

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#248]
**Describe the bug**
The prune operations do not seem to be cleared automatically from the Plan Tree View.
Seems the retention policy is only applying to the Backup operation, and not to the other operations, so who is in charge of cleaning the other operations from the tree view?
In other plans, I also see old Restore and Forget operations...

**Expected behavior**
Old prune operations should disappear like the Backup operation do.

**Screenshots**
![image](https://github.com/garethgeorge/backrest/assets/62859/17d0a343-6829-493e-9fb6-56926fffd487)

**Platform Info**
 - Docker container under Linux
 - 0.17.2

**Comment by garethgeorge** [comment]
Hmm, these should be getting garbage collected. I'll take a look at the logic for that. They are expected to be removed from the log within 30 days.

**Comment by garethgeorge** [comment]
This should be fixed in the next release by the work I did in the task interface refactoring. Garbage collection is now a much-simplified two pass algorithm https://github.com/garethgeorge/backrest/blob/main/internal/orchestrator/tasks/taskcollectgarbage.go#L68-L109
