### ISSUE TITLE
Restore fail mkdir folder and restoring

### ISSUE THREAD

**Issue by ellebi67** [garethgeorge/backrest#249]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/wiki).

**Describe the bug**
Hello Tried on Windows Server backup on QNAP. 
Backup always perfect, 
restore a nightmare. 

"mkdir \\\\?\\d:\\restic-restore-2024-04-24T16-35-32\\D\\D:: The filename, directory name, or volume label syntax is incorrect." 
mkdir write this piece of folders and sub \\\\?\\d:\\restic-restore-2024-04-24T16-35-32\\D, then it lost the rest
and obliously the files

I'm afraid you got this error  =>   D\\D::

In my opinion there is a double root 

![BackRest](https://github.com/garethgeorge/backrest/assets/39163609/0010a1a2-85c9-4bdb-9d9b-536f368b26c3)
![BackRest](https://github.com/garethgeorge/backrest/assets/39163609/e84b7c25-bc0c-47bd-a006-4460d7187d22)

**Platform Info**
Windows Server 2022 Over QNAP 
 - Backrest Version [e.g. 0.15.1]

**Additional context**
Thank You

**Comment by garethgeorge** [comment]
Hey, what does the structure of the item you're restoring look like in the snapshot browser? Is this a backup that was created with Backrest?

The format of the path that I'm seeing passed to restic looks pretty strange, do you also see a double root while browsing the backup? Where is the `./` in `./test` coming from? Is it visible when browsing in the UI?

Backrest 0.15.1 is also quite old. You might try a more recent release.

**Comment by ellebi67** [comment]
Hello. Yes, i can See a double root browsing the backup. D without colums and D: just below, then all the structure correctly disposed. I'll give a try to the new version but I was quite sure to have download the current one from github. Ho can i make an in place update? Thank you for your support. Inviato da Outlook per Android

**Comment by garethgeorge** [comment]
Just tested on my Windows install and top level directories for snapshots created using Backrest look like 
![image](https://github.com/garethgeorge/backrest/assets/7906572/ca3e721c-9018-4fec-9ece-63cff4d2b6f7)

Did you make your snapshots with Backrest? If you did, can you provide details about how you've configured it? It might also be interesting to see the output of `restic ls` for the top few directories of your repo (make sure to anonymize this as it will contain paths from your backed up dataset).

**Comment by ellebi67** [comment]
Ok found the error

   I formerly put in PLANS the D: folder in PATHS, and it caused the double D

   Now I've changed the D: in D:\ (with shlash at the end) and it works perfectly

   both indicating the repository and recovering files

   (better to put in the KB, I suggest)

   Thank you for your support !

   Just a couple of question.

   1. Is there a method to update in place the version of backrest?

   2. Setting up the REPOS I noticed that there is Just the password

       to login and not the password. Who is the user of this passoword ?

       In another environment I've put the password of "admin" of the user

       but after few days it stopped working, stating

   Fatal: unable to open repository at //192.168.1.10/RESTIC: ReadDir: open \\?\UNC\192.168.1.10\RESTIC\keys: Nome utente o password non corretta.

   translating: username or password incorrect.

   But the UNC is correct and the also password for the admin user

   Any clue ?

   thank you





   Cordiali Saluti


   Luca Bianchedi

   ElleBi Informatica


   Sede legale Via Milano 191 - 20832 Desio (MB)

   Sede operativa Via Brescia 1 – 20814 Varedo (MB)

   Tel. e Fax 0362 1791508

   Mobile 335 6694385

   Mail

   ***@***.***

   ***@***.***

   Web

   https://www.ellebiinformatica.it

    

   La presente comunicazione Le viene trasmessa, nella sua qualità di “Interessato al trattamento dei dati personali”, ai sensi degli articoli 13 e seguenti del Regolamento UE n. 2016/679, nonché dell’art. 13 D.lgs. 30.6.2003 n. 196, in quanto applicabile. 

    

   I Suoi dati personali oggetto di trattamento sono costituiti da nome, cognome, numero di telefono, e-mail, altri recapiti di contatto e ci sono stati comunicati dallo Studio o dalla Azienda  per le finalità costituite dall’adempimento degli obblighi derivanti a ElleBi da un contratto di fornitura di servizi sottoscritto con la stessa/o.

    

   I suoi dati personali potranno essere sottoposti a trattamento sia manuale sia con utilizzo strumenti informatici adottando ogni più adeguata garanzia tecnica e organizzativa volta a tutelarne la sicurezza e la riservatezza e ad evitare usi illeciti o non corretti ed accessi non autorizzati.

    

   In quanto Interessato, Lei ha il diritto di verificare l’esistenza dei suoi dati personali nella nostra banca dati, di accedervi, di chiederne la rettifica o l’integrazione, di chiederne la cancellazione una volta esaurita la finalità del trattamento, il blocco dei dati trattati in violazione di legge, nonché di opporsi in ogni caso, per motivi legittimi, al trattamento e di presentare reclamo al Garante per la protezione dei dati personali (link    http://www.garanteprivacy.it/web/guest/home/autorita/compiti).

    

   I diritti elencati possono essere esercitati inviando una richiesta al “Titolare del trattamento” ElleBi Informatica di Luca Gabriele Bianchedi, con sede in Desio (MB), Via Milano 191, P. IVA IT12348250155, anche con comunicazione via mail all’indirizzo ***@***.***

   Per ulteriori approfondimenti, si rimanda alla Informativa completa sulla privacy policy consultabile all’indirizzo https://www.ellebiinformatica.it/joomla344/gdpr-privacy-policy.html.


   Le informazioni trasmesse possono contenere documenti confidenziali e/o materiale riservato, pertanto sono da intendere per le sole persone e/o società cui sono indirizzate. Se questo messaggio è stato trasmesso per errore ad altra persona e/o società,   prego voler contattare il mittente e cancellare queste informazioni da ogni computer.


   This message and any attachment may contain confidential and/or privileged information and is therefore intended solely for the addressee. If you have received this message by error, please notify the sender immediately and delete the message from your  system.


   Da "Gareth" ***@***.***
   A "garethgeorge/backrest" ***@***.***
   Cc "ELLEBI INFORMATICA" ***@***.***,"Author" ***@***.***
   Data Wed, 24 Apr 2024 21:12:32 -0700
   Oggetto Re: [garethgeorge/backrest] Restore fail mkdir folder and restoring (Issue #249)

   Just tested on my Windows install and top level directories for snapshots created using Backrest look like
   image.png (view on web)

   and these seem to restore correctly.

   Did you make your snapshots with Backrest? If you did, can you provide details about how you've configured it? It might also be interesting to see the output of restic ls for the top few directories of your repo (make sure to anonymize this as it will contain paths from your backed up dataset).

**Comment by garethgeorge** [comment]
Hey, I went ahead and edited your comment to snip out some email / phone number info you're leaking when replying with the email client -- please take care with how you've set that up with github as your footer is getting included in replies!

Re: the question, 

1) there is not any inplace update support for backrest on Windows at the moment, upgrades are manual. #163 is tracking possibly creating a windows updater.

2) re passwords I think you're talking about the UI password vs the repository password. The password on the UI protects access to your Backrest installation. The password on the repo is an encryption key which protects your data in storage, this key must be backed up somewhere safe for you to be able to restore your data. Make sure you have it written down :) 

3) Re: access to the repository, it looks like you're accessing a NAS mount which became unavailable? Afraid I don't have much knowledge re: how smb / nfs mounts should work on windows so this will need some debugging on your end, Backrest requires your backup locations to be accessible.
