### ISSUE TITLE
Hook executes backticks when using quotes in shell params

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#251]
Logs for operation Run Hook at 2024-04-26 at 1:57:50 PM
When testing hooks I got this error, because the backticks are executing the command "unlock"

Hook 0 Command:
Script:
mail.sh -s "Backrest" -m "{{ .ShellEscape .Summary }}"

triggering condition: CONDITION_ANY_ERROR
------- script -------
#! sh
mail.sh -s "Backrest" -m "'
Backrest Notification for Error
Task: "forget for plan "S3-XXXX_ipv6"" at 2024-04-26T13:57:50+02:00
Error: forget: get snapshots for repo S3-DTSMS: command "/root/.local/share/backrest/restic-0.16.4 forget --json --keep-hourly 24 --keep-daily 7 --keep-weekly 6 --keep-monthly 12 --keep-yearly 5 -o sftp.args=-oBatchMode=yes --tag plan:S3-XXXX_ipv6 --group-by tag" failed: exit status 1
Process STDOUT: 
unable to create lock in backend: repository is already locked by PID 3630328 on ipv6-test by root (UID 0, GID 0)
lock was created at 2024-04-26 13:20:04 (37m45.980632088s ago)
storage ID 8445f72e
the **\`unlock\`** command can be used to remove stale locks

'"
------- output -------
**sh: 1: unlock: not found**

**Comment by berti34** [comment]
It works when not using quotes:
Script:
mail.sh -s "Backrest" -m {{ .ShellEscape .Summary }}

But that is not the usual way to use parameters, but ok as long as ".ShellEscape" works reliably...

**Comment by garethgeorge** [comment]
Hey, .ShellEscape is actually adding single quotes around the value for you in addition to escaping the contents, this should be the expected behavior. I think the addition of the double quotes was causing variable substitution / subcommands / etc to evaluate.

**Comment by berti34** [comment]
Hi

Simply adding ' around is really not enough.
The output of .Summary etc. must be parsed and every ' in it must have a backslash in front. That must be done by backrest because there is no way to securely paste strings with '"` etc. as parameter. 

Greetings

**Comment by garethgeorge** [comment]
More specifically it's using https://pkg.go.dev/github.com/alessio/shellescape , one of the effects is the single quoting but it's expected to escape symbols, other quotes, etc. I think the problem was the double quotes around the shell escaped expression .
