### ISSUE TITLE
Add docker and docker-compose to backrest container

### ISSUE THREAD

**Issue by Janhouse** [garethgeorge/backrest#255]
Please consider adding additional `Dockerfile.docker` based on base backrest container, which also includes docker and docker-compose binaries. Or at least document this in the Wiki.

Then bind mounting docker socket into backrest container allows to use hooks for executing commands in other containers.

I use this to make database dumps, in addition to file backups.

![image](https://github.com/garethgeorge/backrest/assets/1036439/9f70b153-9853-479d-ba23-78f6565f37f4)

```
FROM garethgeorge/backrest:latest-alpine

RUN apk --no-cache add docker docker-compose
```

I can't be the only one who thinks this is useful.

**Comment by garethgeorge** [comment]
The docker binary on my linux workstation is pretty big, I'm a bit worried about the size impact of including it and compose in the default alpine container (executables included should be very general purpose).

But I'm definitely interested in continuing expanding the wiki, I'll aim (or would happily take a PR) to add a section discussing how to build a custom docker image either in https://garethgeorge.github.io/backrest/cookbooks/command-hook-examples or as a new wiki page in the cookbooks section.

Building custom docker images on the backrest alpine image is definitely expected for use with command hooks.

**Comment by garethgeorge** [comment]
I'll go ahead and close this as infeasible for now but I'd be happy to add any example docker files to the wiki.
