### ISSUE TITLE
Unable to edit plan if the name is too long

### ISSUE THREAD

**Issue by federicofortini** [garethgeorge/backrest#257]
**Describe the bug**
I have a bad habit of being verbose in descriptions and this led me to notice that I can't edit my "plan" because the gear icon is beyond the column size. I'll leave it up to you to choose the best way to handle this use case

**To Reproduce**
1. Create a plan with a name long at least 37 character (mine is docker-compose-and-container-configs)
2. Try to edit it using the gear icon

**Expected behavior**
I expect to be able to modify a plan

**Screenshots**
![image](https://github.com/garethgeorge/backrest/assets/114296068/2636e389-a056-4d4e-a07c-9ae9e564c0ba)

**Platform Info**
 - OS and Architecture - Docker container on Linux x64
 - Backrest Version - 0.17.2

**Comment by federicofortini** [comment]
Tried to manually increase the size of the side column from "Chrome DevTools" to 400, and now I can see the edit icon.

**Comment by modem** [comment]
In https://github.com/garethgeorge/backrest/issues/126 I suggested to move that button to the plan page, next to the other buttons. It may be a good solution for these cases.

**Comment by garethgeorge** [comment]
Hey, going ahead and addressing this in https://github.com/garethgeorge/backrest/commit/5ef890cdc44ce6b290b99891be705b01658ba73c , I've gone ahead and fixed the right-alignment of the settings icon. 

I'm conflicted re: moving the icon to the page for the repo / plan, I think it adds clicks for some flows e.g. switching between the plan config and the repo config to view the hook configuration, etc.

I think correctly right-aligning it e.g. 
![image](https://github.com/garethgeorge/backrest/assets/7906572/9ef6d6ac-9c80-4207-a495-6bf69b08cec7)

should cut down on miss-clicks.

**Comment by federicofortini** [comment]
Hi, thank you for your feedback! How can I try it? I'm using the docker image. I checked and can't find a new 'nightly' updated today. If you didn't plan to have a new docker image for this little modification, I can manually replace the two files edited by your commit.

**Comment by garethgeorge** [comment]
Hey, you can try this out by downloading a binary from https://github.com/garethgeorge/backrest/actions/runs/8960742109  and copy it into a docker image, afraid I don't have nightly releases setup yet.

A quick caveat is that this is an early version of the `1.0.0` release which includes a few config migrations.

**Comment by lakemike** [comment]
As a workaround, you can select the plan or repository name, then hit the "tab" key in your browser and it should jump to the wheel icon.

**Comment by federicofortini** [comment]
Hi, thank you for the suggestion. I didn't try your fix yet... Backrest was set up in fire and forget way, I only receive notification when something goes wrong... An I also forgot to test your patch! 😬

Yahoo Mail: cerca, organizza, prendi il controllo della tua casella di posta 
 
  Il lun, 13 mag, 2024 alle 7:33, ***@***.***> ha scritto:   


As a workaround, you can select the plan or repository name, then hit the "tab" key in your browser and it should jump to the wheel icon.

**Comment by garethgeorge** [comment]
Should be resolved in 1.0.0 , feel free to give this a ping if you're still running into issues!

**Comment by federicofortini** [comment]
Wonderful! I'll give it a try. 
Federico 

Yahoo Mail: cerca, organizza, prendi il controllo della tua casella di posta 
 
  Il lun, 20 mag, 2024 alle 4:20, ***@***.***> ha scritto:   


Should be resolved in 1.0.0 , feel free to give this a ping if you're still running into issues!

**Comment by federicofortini** [comment]
Updated fiew minute ago. Now I can edit my plan 😊
