### ISSUE TITLE
Old snapshots linger after running uninstall.sh and deleting repo (v0.17.2)

### ISSUE THREAD

**Issue by zz0rk** [garethgeorge/backrest#259]
Old snapshots linger after running uninstall.sh and deleting repo (v0.17.2)

Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/wiki).

**Describe the bug**
I've used the uninstall script 'uninstall.sh' to remove backrest and disable the service. I've deleted the repo from my hard drive. I've reinstalled backrest and restored the previous config.xml to ~/.config/backrest. My backup plans have been restored, but it also shows old snapshots that no longer exist. Where are these stored and why are these links not being deleted when uninstalling backrest.

**To Reproduce**
Backup 'config.xml'. 
Run 'uninstall.sh'. 
Delete repo from hard drive. 
Run 'install.sh'.
Restore 'config.xml' from backup.
Open :9898.
Old snapshots are shown under the tree view of the backup plan.

**Expected behavior**
Running 'uninstall.sh' should clear the tree view backup history, if the repo had been removed from the backup HD.

**Screenshots**
![image](https://github.com/garethgeorge/backrest/assets/18619265/e3e3ac79-7921-4095-9d61-12a2647b2eae)

**Platform Info**
 - OS and Architecture: Debian 12 x64
 - Backrest Version v0.17.2

**Additional context**

**Comment by garethgeorge** [comment]
Hey, these are stored in `~/.local/share/backrest` on unix systems (specifically oplog.boltdb in that folder).

**Comment by zz0rk** [comment]
Great, thank you. Would it make sense to add this to the documentation,.e.g. to back up confg.xml if needed and were to delete the snapshot history. It may be obvious to some, but it would be great to have it documented. I did check the documention for it, but maybe I missed it. Thank you very much!

**Comment by garethgeorge** [comment]
Agreed -- Backrest perhaps needs a wiki page https://garethgeorge.github.io/backrest/docs/  that covers the storage directories that it uses etc.

I can also see the argument for having `uninstall.sh` clear out this directory (perhaps still leave behind the config? I really don't want to risk obliterating a user's repo keys if they've not backed them up -- though users definitely should).

**Comment by zz0rk** [comment]
The script could be interactive, e.g. Backup backrest config.xml (n/Y), Clear repo snapshot history (y/N). A wiki page would be great. Thank you for all your work.
