### ISSUE TITLE
How to set backup flags e.g. exclude-file

### ISSUE THREAD

**Issue by grinnan** [garethgeorge/backrest#261]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/wiki).

**Describe the bug**
I am unable to user restic exclude-file flag.  The flags section only applies to restic general commands, not restic backup commands

**To Reproduce**
1. add to flags `--exclude-file=<file containing paths to be excluded from backup>`

**Expected behavior**
backup excludes paths listed in file

**Screenshots**

**Platform Info**
- ArchLinux, MacOS

**Additional context**

**Comment by garethgeorge** [comment]
Hey, are you using flags at the repo level or flags on the plan? The flags on the plan are set for the backup, flags at the repo apply to all operations.

**Comment by grinnan** [comment]
Thanks for the amazingly quick response!  I looked through your source and it worked manually add `backup_flags` to the plan section of my config json.  The "Backup Flags" showed up in the GUI. I think the docs say and if not imply that you can use flag `--one-file-system` in the place where flags can be added.  The only place in the GUI where I could see to add flags is in the repo section which will cause failure because `restic init --one-file-system` is not a thing.   I will leave this open for you to close whenever.  

I just found this program.  I have been using autorestic for years but my backup have been failing lately and it is nice to have a GUI (and the browsing and history in this one is great).  Thank you

**Comment by garethgeorge** [comment]
Glad it's working well for you! Good callout re: the `--one-file-system` flag in the docs, I'll fix that reference.
