### ISSUE TITLE
add function .FormatDuration in templates

### ISSUE THREAD

**Issue by scialo** [garethgeorge/backrest#262]
if possible add function .FormatDuration in templates when sending notification.
es.: - Total duration: 01h 23m 45s.

thanks

**Comment by garethgeorge** [comment]
Hey, can you elaborate on this? What duration value are you wanting to format?

**Comment by scialo** [comment]
when i send the notification to gotify in the summary there is Total duration: 41.3222278s with the value all in seconds. i would like this value to be formatted in hh-mm-ss. is this possible?

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/blob/e2ef66ef929c3ab116b7a58527dacc8aa15b7f2a/internal/hook/hookvars.go#L64
