### ISSUE TITLE
Retention Policy how to set hourly to zero

### ISSUE THREAD

**Issue by scialo** [garethgeorge/backrest#269]
in retention policy I set hourly to zero but when i save it sets to 24. how do I set it to zero?

**Comment by garethgeorge** [comment]
Hey, please fill out the full bug report form including Backrest version etc.

**Comment by scialo** [comment]
ver. 0.17.2

**Comment by garethgeorge** [comment]
This should be addressed fixed in the latest few versions of backrest.
