### ISSUE TITLE
ARM32 Build (reopen)

### ISSUE THREAD

**Issue by hello-world-dot-c** [garethgeorge/backrest#271]
This is a duplicate of https://github.com/garethgeorge/backrest/issues/130 which I couldn't reopen. So I added a comment a while ago which apparently didn"t show up anywhere.

I've tested the latest binaries without success, please reopen.

**Comment by garethgeorge** [comment]
This is likely related to the fix in https://github.com/garethgeorge/backrest/pull/250

**Comment by hello-world-dot-c** [comment]
Hi, I could finally try the latest build (releases/download/v0.17.2/backrest_Linux_armv6.tar.gz) on my QNAP NAS. Same thing, everything works fine until I go to _Browse and Restore Files in Backup_ and then I get the following error in the browser:

`Failed to list snapshot files: [unknown] failed to list snapshot files: failed to list snapshot files: command "/opt/bin/restic ls --json 131583dc36db17a30fc3486f79e25c805fe939f1b4e1d69d5dcc0ba6f57895fb / -o sftp.args=-oBatchMode=yes" failed: failed to parse JSON: json: cannot unmarshal number 2147484013 into Go struct field LsEntry.mode of type int`

**Comment by garethgeorge** [comment]
This should be resolved (for real this time) in the 1.0.0 release. Let me know if that works for you.

**Comment by hello-world-dot-c** [comment]
I just tested it with the 1.1.0 release and yes, this issue is finally fixed. Thanks!
