### ISSUE TITLE
latest restic for darwin arm, install process is borked.

### ISSUE THREAD

**Issue by Shiberal** [garethgeorge/backrest#272]
francesco@MacBook-Air-di-Francesco-2 Downloads % cd Backrest\ Darwin\ arm64
francesco@MacBook-Air-di-Francesco-2 Backrest Darwin arm64 % ./install.sh
Installing on Darwin
./install.sh: line 93: install_unix: command not found <-- i think is that.
Creating launchd plist at /Library/LaunchAgents/com.backrest.plist
Trying to unload any previous version of com.backrest.plist
Loading com.backrest.plist
xattr: /usr/local/bin/backrest: No such xattr: com.apple.quarantine
Logs are available at /tmp/backrest.log
Access backrest WebUI at http://localhost:9898

i was trying to update from 0.16.X to latest, i opened the WebUi and with surprise.. the version did not changed.
so i got the 0.17.1 release package, and run the install the same way, and it did update, tried again to update to latest with no change... si i think the install script is borked.

**Comment by garethgeorge** [comment]
Hey, sorry you're hitting this! https://github.com/garethgeorge/backrest/pull/260 contributed a fix here but I haven't pushed a release yet.

You should be able to download the install.sh from the repo and use that, or you may find it easier to migrate to using the homebrew tap https://github.com/garethgeorge/homebrew-backrest-tap if you have `brew` on your system.

**Comment by garethgeorge** [comment]
Just shipped 1.0.0 which includes the fixed installer.

**Comment by Shiberal** [comment]
Thanks!
