### ISSUE TITLE
restic-server: Repos are not created below the user, but in the root directory

### ISSUE THREAD

**Issue by MrksHfmn** [garethgeorge/backrest#273]
**Describe the bug**
Repos are not created below the restic server's user dir but directly in the root directory. No folder with config, keys, snapshots etc. is created, but everything is placed directly in the root directory.

**To Reproduce**

1. Add new repo
2. URI: rest:https://user:password123@restic.domain.de/user
3. Set repo name and password
4. New repo is now in the root dir without any subfolder 

**Expected behavior**
Create new repos (folders) below the user

**Platform Info**

- OS and Architecture: Linux
- Backrest Version 0.17.2

**Comment by garethgeorge** [comment]
Hey, sorry you're running into a problem here. As an additional step would you mind trying `RESTIC_REPOSITORY=<your URI> restic init` and see if you're able to reproduce the problem you're having? 

Backrest forwards the URI (without modification) by setting as the `RESTIC_REPOSITORY` environment variable to the URI value provided.

**Comment by MrksHfmn** [comment]
It's working on command line, but i need to set the absolute path + repo name on backrest to get it working:

![grafik](https://github.com/garethgeorge/backrest/assets/47270678/0f51cbf2-b681-4013-8a9e-fac646e5850e)

**Comment by garethgeorge** [comment]
I wonder if the problem was that you needed a slash at the end of your original URI? Adding the repo name at the end does not do anything special in backrest’s implementation.
