### ISSUE TITLE
Fatal repository error when starting a backup

### ISSUE THREAD

**Issue by AT181903** [garethgeorge/backrest#290]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/discussions).

**Describe the bug**
First time starting a backup. Correctly created repos and plans. When i start a backup (manually or planned) I get the error:
`error: failed to get snapshots for plan: get snapshots for plan "Test": command "/home/at181903/.local/share/backrest/restic-0.16.4 snapshots --json -o sftp.args=-oBatchMode=yes --tag plan:Test,created-by:backrest" failed: exit status 1`

Then I manually executed the command and got this error:
`Fatal: Please specify repository location (-r or --repository-file)`

**Platform Info**

- OS and Architecture: Linux x86_64
- Backrest Version 1.0.0

**Additional context**
I updated from an older version (it could be 0.14.X). Also tried to execute uninstall script and then installed again.

**Comment by garethgeorge** [comment]
Re: the first error you see, please go ahead chick "view logs" on that operation and go ahead and attach those -- that might provide a bit of visibility.

**Comment by AT181903** [comment]
I didn't see the view log button (it's really small). Now I found it and it says:

'command: /home/at181903/.local/share/backrest/restic-0.16.4 snapshots --json -o sftp.args=-oBatchMode=yes --tag plan:BackrestConfigBackup,created-by:backrest
Fatal: wrong password or no key found
command "/home/at181903/.local/share/backrest/restic-0.16.4 snapshots --json -o sftp.args=-oBatchMode=yes --tag plan:BackrestConfigBackup,created-by:backrest" failed: exit status 1'

**Comment by garethgeorge** [comment]
Did something change in your config recently e.g. can you confirm that it looks the same as it did in the last working state? 

I think your next diagnostic step should be to confirm that you can open the repo on the restic CLI and that the uri and password that works there matches what you have configured in backrest.

**Comment by AT181903** [comment]
This is the first working state, I didn't use Backrest before.

I just tried to mount my disk (used as repo) in my home folder (in order to avoid permissions problem) and it give me this error:

`command: /home/at181903/.local/share/backrest/restic-0.16.4 snapshots --json -o sftp.args=-oBatchMode=yes --tag plan:ProvolaLocal,created-by:backrest
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 606.2242ms: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 525.9763ms: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 1.385808195s: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 983.172441ms: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 1.367266481s: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 2.451989184s: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 8.413389736s: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 5.718068977s: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 16.731244448s: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Load(<key/ef73b4ba49>, 0, 0) returned error, retrying after 21.072935768s: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
Fatal: open /home/at181903/Provola/keys/ef73b4ba496264a576a5f160e1a0f854ef076742d7e6cebc7649bdd2ade8502d: stale NFS file handle
command "/home/at181903/.local/share/backrest/restic-0.16.4 snapshots --json -o sftp.args=-oBatchMode=yes --tag plan:ProvolaLocal,created-by:backrest" failed: exit status 1`

**Comment by AT181903** [comment]
Follow up:
I tried with a local repositories (a directory in my Document folder) and everything works correctly

**Comment by garethgeorge** [comment]
Very glad to hear it's working with a local repo!

From the errors you posted it looks like something is wrong with the NFS setup. Found https://unix.stackexchange.com/questions/433051/mount-nfs-stale-file-handle-error-cannot-umount talking a bit about this but it sounds like it's (probably) unrelated to Backrest -- hope that helps you diagnose.
