### ISSUE TITLE
Failed to configure repo: instance is a required

### ISSUE THREAD

**Issue by dm9tr0** [garethgeorge/backrest#291]
Since latest update (so for last 3 days) I have 0 backups, I see this error 
<img width="613" alt="image" src="https://github.com/garethgeorge/backrest/assets/17461617/100d44d6-8c65-40e1-b891-cc350fcb67f6">
I was trying to create new connection - the same error.
I have no idea what is is "instance is a required" I don't see this field
 **instance is a required field in the backrest config**
`{
  "id": "gDrive2",
  "uri": "rclone:remote:Rclone/Restic",
  "password": "mypass",
  "env": [
    "RESTIC_COMPRESSION=auto"
  ],
  "flags": [
    "-o rclone.program=/opt/homebrew/bin/rclone"
  ],
  "prunePolicy": {
    "maxUnusedPercent": 25,
    "schedule": {
      "maxFrequencyDays": 7
    }
  },
  "autoUnlock": true
}`

**Comment by dm9tr0** [comment]
How it is possible to break what was working for months - have no idea, the same I don't see UI improvements since last my tickets, no labels or hints, even error message has 0 helpful information.

**Comment by garethgeorge** [comment]
Hey, when you open the WebUI you should be getting prompted to set an "instance ID" for your host -- if you aren't please go to the settings panel and set an instance ID.

Sorry that this is failing your backups, that was an oversight when I was validating the upgrade -- this was intended to be a warning for 1.0.0 and an error down the line. I'll put out a patch release to downgrade missing instance field to a warning.

**Comment by dm9tr0** [comment]
Oh, thanks, never seen this message.

**Comment by clonejo** [comment]
Ran into this while doing a new setup on 1.9.2, i just blindly clicked past the setup screen when first opening the web UI 🙃 

Thanks a bunch for building this tool! It enables me to set up restic for my family stuck on Windows :)
