### ISSUE TITLE
'Compute Stats' button runs but does not refresh the stats tab

### ISSUE THREAD

**Issue by tylwright** [garethgeorge/backrest#300]
**Describe the bug**
'Compute Stats' button does not refresh the stats tab content.

**To Reproduce**
1. Go to a new repository, click on it.
2. Click the 'Stats' tab to select it.
3. Click the 'Compute Stats' button.

**Expected Behavior**
The stats graphs should appear once the computing has completed.

**Actual Behavior**
Stats graphs do not load.  User has to click on another tab (ex. 'Operation List') and then click back on the 'Stats' tab to bring up the graphs.

**Screenshots**
N/A

**Platform Info**
- Docker on Ubuntu 22.04 (amd64)
- Backrest v1.0.0

**Additional context**
This only happens on new repos or repos that have never had their stats computed before.  When a repo finishes its first plan, the 'Compute Stats' process should probably be triggered.  Or, when the 'Compute Stats' button is triggered for the first time, refresh the tab or reload the content so that the graphs appear.

**Comment by garethgeorge** [comment]
Good catch, fixed this and a collection of similar QOL issues in https://github.com/garethgeorge/backrest/commit/b218bc9409bf4a6c70da06e1f98760ff520afc37
