### ISSUE TITLE
Minor improvement: --exclude-caches is in cmd twice

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#304]
Hi George,

just a notice: the  --exclude-caches is always twice in the backup cmd:

command: C:\WINDOWS\SYSTEM32\restic.exe backup --json **--exclude-caches** C:\Portable C:\Privat -o sftp.args=-oBatchMode=yes **--exclude-caches** --tag plan:S3-DTSMS-Win-01 --tag created-by:DTS-LAP-028 --exclude *~ --parent ...  --exclude-file C:/Portable/BackRest/excludes-file.txt

**Comment by berti34** [comment]
Do you think you may filter out some backup flags that are OS dependent? 
For example  --one-file-system   is currently not possible on Windows and throws an error during backup start.
Maybe the configuration dialog should give a notice or warning about it, depending on the system the backrest binary is running on.

**Comment by garethgeorge** [comment]
Thanks for this report -- I think I missed updating this issue at the time but I did slip this fix in with some bundled patches. Should be fixed as of the last few versions :)
