### ISSUE TITLE
Snapshots cannot be removed when plan is missing

### ISSUE THREAD

**Issue by fortysix2ahead** [garethgeorge/backrest#312]
**Describe the bug**
A snapshot cannot be removed via **Forget** when the associated plan which was used to create that snapshot has been removed.

**To Reproduce**

1. Create a plan
2. Run a backup, resulting in snapshot 1
3. Delete the plan
4. Try to forget snapshot 1

**Expected behavior**
Snapshot 1 is removed.

**Screenshots**

**Platform Info**

- OS and Architecture [e.g. Windows 10 x64, Darwin arm64]
- Backrest Version 1.0.0, running in docker
- Raspberry Pi OS, Bookworm

**Additional context**

**Comment by garethgeorge** [comment]
Hey, would you mind including the error message you're seeing in the bug report?

**Comment by fortysix2ahead** [comment]
Sure, there's a one liner: `Failed to forget snapshot: ConnectError: [unknown] failed to get plan "test": get plan "test": plan not found`

**Comment by garethgeorge** [comment]
Fixed in 1.2.0 :)
