### ISSUE TITLE
Prune, check, and forget operations fail

### ISSUE THREAD

**Issue by gbrsni** [garethgeorge/backrest#321]
**Describe the bug**
All prune, check, and forget operations fail with exit status 1. 
Everything was working until i updated to 1.0 (currently on 1.1.0).
This only happens on a pre-existing repository, a freshly created one works flawlessly.

Below is the output of the first failed prune operation

```loading indexes...
loading all snapshots...
finding data that is still in use for 150 snapshots
[0:44] 100.00%  150 / 150 snapshots

searching used packs...
collecting packs for deletion and repacking
[0:01] 100.00%  12506 / 12506 packs processed


to repack:        244383 blobs / 182.830 MiB
this removes:       6512 blobs / 53.630 MiB
to delete:         24880 blobs / 1.819 GiB
total prune:       31392 blobs / 1.871 GiB
remaining:        733846 blobs / 178.120 GiB
unused size after prune: 7.143 GiB (4.01% of remaining size)

deleting unreferenced packs
[0:00] 100.00%  89 / 89 files deleted

repacking packs
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 509.98213ms: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 698.654091ms: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 1.16352265s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 1.174794481s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 2.288951715s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 3.338556781s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 3.828014434s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 5.085054182s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 17.557967622s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 23.483654633s: The specified key does not exist.
```

Successive manual prunes fail with exit status 1 and no output.

Manually triggering a check has it failing with exit status 1 with output

`using temporary cache in /tmp/restic-check-cache-1031205035`

Scheduled prunes after snapshots fail with exit status 1.

Snapshot operations seem to keep working as usual.

**Screenshots**

![Screenshot 2024-06-05 at 14-33-20 Backrest](https://github.com/garethgeorge/backrest/assets/72036069/e9ed1684-4237-486e-94b2-3a9dae443a95)
![Screenshot 2024-06-05 at 14-33-41 Backrest](https://github.com/garethgeorge/backrest/assets/72036069/434c09f1-54c8-4190-8547-55489218da66)

**Platform Info**

Docker compose 2.20.2 on Ubuntu 22.04

**Comment by ArthurusDent** [comment]
I think I might have had a similar problem. The repo in question is on a NAS. Restic-server and backrest are both running on the NAS. 

After I updated to backrest 1.0, it seems backrest for the first time changed the owner of some of the files in the repo. Turns out, backrest runs as root (I know, I know...) but the restic-server runs as an unprivileged user. After pruning by backrest, some files were not owned by the unprivileged user any more, but by root. That's when my backups started to fail because some files couldn't be read any more.

Changing the owner of the files in the repo back to the unprivileged user fixed the problem for the time being. But I will probably have to re-install backrest as the same unprivileged user to fix the problem.

**Comment by garethgeorge** [comment]
> After pruning by backrest, some files were not owned by the unprivileged user any more, but by root. That's when my backups started to fail because some files couldn't be read any more.

This sounds really unexpected, ultimately backrest never touches repo files -- it always coordinates through restic e.g. by running restic commands. I wonder how restic would sometimes be changing the ownership of the files if the repo should be configured to go through your rest repo (backed by restic-serve?)?

**Comment by garethgeorge** [comment]
You might try running a repair operation: https://restic.readthedocs.io/en/latest/077_troubleshooting.html#repair-the-index .

**Comment by gbrsni** [comment]
I did that and checks now pass, but prune still fails
```
loading indexes...
loading all snapshots...
finding data that is still in use for 149 snapshots
[0:11] 100.00%  149 / 149 snapshots

searching used packs...
collecting packs for deletion and repacking
[0:02] 100.00%  13822 / 13822 packs processed


to repack:        395000 blobs / 264.223 MiB
this removes:     229478 blobs / 150.156 MiB
to delete:        185410 blobs / 9.791 GiB
total prune:      414888 blobs / 9.938 GiB
remaining:        648709 blobs / 176.987 GiB
unused size after prune: 9.490 GiB (5.36% of remaining size)

repacking packs
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 615.791183ms: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 867.051225ms: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 977.05203ms: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 1.497812046s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 3.185125692s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 5.412823522s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 4.91874376s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 11.470026971s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 13.879214381s: The specified key does not exist.
Load(<data/4935444ef6>, 201818, 61426) returned error, retrying after 10.003962552s: The specified key does not exist.

```

**Comment by ArthurusDent** [comment]
> I wonder how restic would sometimes be changing the ownership of the files if the repo should be configured to go through your rest repo (backed by restic-serve?)?

I've thought about this more and realized that the repo in backrest isn't configured to be accessed through the restic-server. It is configured just like a regular repo by giving it the directory because the repo is on the same machine. But this alone doesn't explain the changed ownership because there is no plan on that machine that uses the repo in question. So what might have happened is that I had the "great" idea to run prune manually on that repo from that machine. This would most likely have executed the restic binary as the user root, which would then explain the change in ownership, right?
