### ISSUE TITLE
Cron is not honored

### ISSUE THREAD

**Issue by marcolino7** [garethgeorge/backrest#324]
Hi,
I have setup cron to run at 0,4,8,12,16,20 of every day. Accordind with crontab.guru right way is that:
https://crontab.guru/#0_*/4_*_*_*
![image](https://github.com/garethgeorge/backrest/assets/11460036/1e1285ff-52f9-4c96-99c9-5c32e8032a18)

I setup as is on backrest:
![image](https://github.com/garethgeorge/backrest/assets/11460036/afd5733d-b02b-49b7-adc7-8e9bf8c36c49)

and json confirm:
![image](https://github.com/garethgeorge/backrest/assets/11460036/fc1e0b4f-f07e-47bd-95c1-372e955cd0f9)

Now is 23:01 and I am expecting next run at 00:00, but backrest show me next backup at 2 AM. What I am doing wrong?

![image](https://github.com/garethgeorge/backrest/assets/11460036/be4564c1-9362-49c9-876f-f40b529c5e4b)

**Platform Info**

- Docker 26
- Backrest Version 1.1.0

**Comment by garethgeorge** [comment]
Is your timezone set correctly in the container? Ensure you set `TZ=` your timezone if using docker.

**Comment by marcolino7** [comment]
> Is your timezone set correctly in the container? Ensure you set `TZ=` your timezone if using docker.

Yes it is timezone issue. Perhaps there is lack of information in Dockerpage.

Many Thanks
Marco
