### ISSUE TITLE
feature: support pre-backup and post-backup command hooks per-repo

### ISSUE THREAD

**Issue by garethgeorge** [garethgeorge/backrest#34]

**Comment by garethgeorge** [comment]
Starting work in https://github.com/garethgeorge/backrest/tree/garethgeorge/hooks

**Comment by x86dev** [comment]
Excellent, can't wait to give it a test once it's ready 😀

**Comment by garethgeorge** [comment]
Initial implementation landed in https://github.com/garethgeorge/backrest/pull/60 with support for command hooks with configurable shells for execution (a small example is included on that PR). Prebuilt binaries with the feature will be available in the next release. I'd like to land auth support as another major feature in 0.11.0 .

I'll also be adding a few hooks for notification services. I'll be interested in community input on what services people most use for notifications. I'm looking at https://github.com/nikoksr/notify for the underlying notification dispatch.  Currently planned hooks types:
 
  *. command hooks (done)
  * discord webhooks
  * email
  * http webhook 
  * google chat 
  * matrix

Open to suggestions on others to add (especially if supported by a community maintained package).

**Comment by x86dev** [comment]
Another very popular choice would be [Apprise,](https://github.com/topics/apprise) which in turn also offers a lot of different notification services. However, this is Pyhon-based, but it also can be used via simple built-up URLs.

**Comment by garethgeorge** [comment]
Implemented support in https://github.com/garethgeorge/backrest/releases/tag/v0.11.0 , I've gone ahead with default support for "command" hooks which should be a good way to make use of tools in other languages like apprise, I've also implemented Discord and Gotify as builtin webhook types.
