### ISSUE TITLE
Gotify Hook: Gotify Base URL does not accept just a hostname: 0,actionGotify,baseUrl is not a valid url

### ISSUE THREAD

**Issue by mrtnbr** [garethgeorge/backrest#342]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/discussions).

**Describe the bug**
I run Backrest and Gotify in the same network, so Gotify can be found by using only the hostname. Backrest however want a full URL when entering the Gotify Base URL.

**To Reproduce**

1. Go to repository settings or plan settings
2. Go to 'Add Hook' and click Gotify
3. Enter something like 'http://gotify' in the Gotify Base URL field
4. It will not accept the input, error is: 0,actionGotify,baseUrl is not a valid url

**Expected behavior**
I expect to be able to enter a URL like 'http://gotify'. This _can_ be done when using a Shoutrrr Hook

**Screenshots**
![image](https://github.com/garethgeorge/backrest/assets/4752390/1d058830-325f-45cd-88a8-7aa34bfdb1ba)

**Platform Info**

- Docker (compose) container on Debian (tag latest)
- Backrest Version 1.1.0

**Comment by garethgeorge** [comment]
Oops, this is a good catch. Overly zealous form validation is to blame, patching this with a collection of other UI fixes for the next release (targeting a release this weekend).

**Comment by mrtnbr** [comment]
I can confirm that release 1.2.0 fixes this issue for me! Thank you!

**Comment by garethgeorge** [comment]
Great, glad that worked for you!
