### ISSUE TITLE
Support to stop and start other docker containers before and after backing up

### ISSUE THREAD

**Issue by shaaraddalvi** [garethgeorge/backrest#346]
**Is your feature request related to a problem? Please describe.**
Backrest is awesome - especially that it provides a very nice web UI and an is intuitive to set up the backups. I have most of the services running as Docker containers, and to make Backrest safely backup their data, I'd prefer if the service containers are stopped before the backup process starts, and are restarted afterwards. Something that https://github.com/djmaze/resticker?tab=readme-ov-file#execute-commands-prior-to-backup does, but it doesn't have Backrest's UI goodness and sophistication (yet!).

**Describe the solution you'd like**
If we could provide a list of docker containers to stop in a Backrest 'Plan' (or a docker container label we can specify, which Backrest can use to query all the applicable containers), and Backrest can stop them before backup runs and start them afterwards, it would be great!

**Additional context**
Pretty much what's described above.

**Comment by garethgeorge** [comment]
Backrest supports this through hooks :) https://garethgeorge.github.io/backrest/docs/hooks

You're looking for a command hook on `CONDITION_SNAPSHOT_START`.

**Comment by shaaraddalvi** [comment]
That's a record-breaking fast response! 😄 

Yeah it looks like hooks can pretty-much do it. Is there _any_ remote possibility that docker cli is added to backrest's docker image? I guess that's all that would be needed, because if `/var/run/docker.sock` is mounted, adding a hook like `docker stop mycontainer` would just work? 🙇🏽‍♂️

**Comment by garethgeorge** [comment]
Hmm, my hesitance here in the past has been that this adds ~8MB to the image size compressed and, as you say, close to 25MB unpacked and deployed on a user's system.

Philosophically I've felt in the past that Backrest should take up minimal storage and runtime overhead since at the end of the day, it's backup daemon. It should be as lightweight as possible so that backups can blend into the background and a user can use that storage for actual data.

Not quite sure what the right balance is here, I'd be interested to leave this open for a bit to see if there's a strong community desire to see this included.

**Comment by shaaraddalvi** [comment]
Makes sense, appreciate your thoughts!

Meanwhile, I have locally created a docker image (I haven't published it to Docker hub yet) which simply adds `RUN apk --no-cache add docker-cli` on top of `garethgeorge/backrest:latest` image and I'm using it. But to keep the latest image sync with backrest's latest tag, I'll set up a GitHub repository and an action that periodically publishes this image to docker hub.

Not immediately on my radar, as I'm currently busy setting up backups for my services, but I'll post here once I have the image published.

Thanks again!

**Comment by ovizii** [comment]
Is docker-cli a single binary without dependencies? If so, one could simply bind-mount it into the backrest container. I initially did so with rclone until I noticed backrest has its own.

**Comment by shaaraddalvi** [comment]
I haven't verified it yet, but it's unlikely to work, as backrest image is alpine-based, the docker-cli package, even if it is a single binary, would depend on musl. So a glibc-based binary on host, even if mounted to the container can't be executed from inside the container.

**Comment by ColonelSanderson** [comment]
One option is to add an INCLUDE_CLI env/arg to signal whether to include it in the image on build time. That or including a GitHub action for publishing the backrest-cli image.

Either way I would like to see this included 👍

**Comment by gufpewga** [comment]
Hi [shaaraddalvi](https://github.com/shaaraddalvi) did you have released your edition with docker-cli. I would also be happy if there was docker added because of possibility of stopping immich container for backup so I don't have a corrupted backup. And I think more people would enjoy it. Can you make it official with docker-cli added?

**Comment by garethgeorge** [comment]
Thanks all for the feedback, based on what I'm seeing here and some more thinking on my end I'm going to aim to add docker to the image in the next minor version release (probably a few weeks out). 

I think it's a good FR and discussing with more users I think it's a very common want for dockerized deployments.

**Comment by networkydev** [comment]
Just wanted to chip in; if you don't want to make a new docker container you could instead use [OliveTin ](https://github.com/OliveTin/OliveTin)(bind it to local host) and run scripts via the [API](https://docs.olivetin.app/api-start-action.html#api-eg-startIdUrl).

You might be able to access the hosts localhost from docker using a different networking mode like host instead of bridge

**Comment by shaaraddalvi** [comment]
> Hi [shaaraddalvi](https://github.com/shaaraddalvi) did you have released your edition with docker-cli. I would also be happy if there was docker added because of possibility of stopping immich container for backup so I don't have a corrupted backup. And I think more people would enjoy it. Can you make it official with docker-cli added?

No, I haven't gotten a chance to publish the image yet, but now with the possibility of backrest officially supporting it, I won't need to 😄

**Comment by shaaraddalvi** [comment]
@garethgeorge is there a plan to add docker-cli in any upcoming release? I was actually looking forward to having it in 1.3.0 😅

**Comment by oddysee** [comment]
@shaaraddalvi I suggest closing this since docker-cli is a part of the image

**Comment by garethgeorge** [comment]
Thanks for the ping on this, marking resolved.

**Comment by robflate** [comment]
Apologies for adding to a closed issue but can anyone provide an example of using a HOOK to stop a docker container, run the backup then start the container back up?

**Comment by lucius346346** [comment]
I'm using
`docker stop $(docker ps -qa)`
and
`docker start $(docker ps -aq)`

but for Backrest this would be better:
```
#!/bin/bash

containers=$(docker ps -q | grep -v "<backrest_container_id>")

if [ -n "$containers" ]; then
    docker stop $containers
fi
```
so it won't stop Backrest itself.

Unfortunately none of these work for me in Backrest because I'm getting this error:

> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by robflate** [comment]
I solved it by mounting the docker socket in my compose;

```
volumes:
  - /var/run/docker.sock:/var/run/docker.sock:ro
```

then I added the following hook;

<img width="721" alt="Screenshot 2024-09-09 at 14 51 19" src="https://github.com/user-attachments/assets/70ffa2c2-d14b-4d53-8acf-7f80ebe467e8">

**Comment by cyhyraethz** [comment]
Here are the scripts that I use for stopping and starting containers before and after backing up my docker volume (which I do at 3:30 and 4:30 AM to minimize disruption of services).

**Note:** I'm running backrest as bare metal on my system. If running in its own docker container then backrest should be included in `ignore_containers`.

### docker-container-stop.sh

```bash
#!/bin/bash

all_containers=$(
    docker ps --quiet |
        sort
)

ignore_containers=$(
    docker ps --quiet \
        --filter "name=element" \
        --filter "name=glances" \
        --filter "name=grafana" \
        --filter "name=homepage" \
        --filter "name=it-tools" \
        --filter "name=kiwix" \
        --filter "name=markopolis" \
        --filter "name=ntfy" \
        --filter "name=reminiflux" \
        --filter "name=thelounge" \
        --filter "name=traefik" \
        --filter "name=watchtower" \
        --filter "name=whoami" |
        sort
)

pending_containers=$(comm -23 <(echo "$all_containers") <(echo "$ignore_containers"))

# echo -e "\nall_containers:\n$(tput setaf 2)$all_containers\n$(tput sgr 0)"
# echo -e "\nignore_containers:\n$(tput setaf 2)$ignore_containers\n$(tput sgr 0)"
# echo -e "\npending_containers:\n$(tput setaf 4)$pending_containers\n$(tput sgr 0)"

echo "Stopping docker containers..."

docker stop $pending_containers
```

### docker-container-start.sh
```bash
#!/bin/bash

stopped_containers=$(
    docker ps --quiet \
        --filter "status=exited" |
        sort
)

echo "Starting docker containers..."

# shellcheck disable=2086
[[ -z $stopped_containers ]] ||
    docker start $stopped_containers
```

Those are both called by the `backrest-snapshot-start.sh` and `backrest-snapshot-stop.sh` scripts, which also send notifications to the `server-status` topic on my private [ntfy](https://github.com/binwiederhier/ntfy) instance.

### backrest-snapshot-start.sh

```bash
#!/bin/bash

ntfy publish \
    --title="Starting server backup" \
    --message="Stopping docker containers for backup. Server may be temporarily unavailable." \
    --icon="https://archlinux.org/static/favicon.png" \
    https://ntfy.domain.tld/server-status

sleep 30

/home/cyhyraeth/.local/bin/docker-container-stop.sh
```

### backrest-snapshot-stop.sh
```bash
#!/bin/bash

/home/cyhyraeth/.local/bin/docker-container-start.sh

sleep 30

ntfy publish \
    --delay=10s \
    --title="Server backup complete" \
    --message="Restarting docker containers. Server should now be available again." \
    --icon="https://archlinux.org/static/favicon.png" \
    https://ntfy.domain.tld/server-status
```

Those scripts are then triggered by these hooks on my plans for backing up docker volumes.

![image](https://github.com/user-attachments/assets/7e7ac5f2-df6d-474c-9044-12435a0f63b9)
