### ISSUE TITLE
ERROR: this element should not appear, this is a bug.

### ISSUE THREAD

**Issue by lucius346346** [garethgeorge/backrest#359]
I have this message on top level of the Tree View.
![image](https://github.com/garethgeorge/backrest/assets/43910504/fd350026-6ff0-4971-83a8-19de0cc1d959)

Backups are done outside of Backrest because I need to stop the docker containers before backup, which Backrest does not support.

**Comment by arminus** [comment]
I have the same issue with 1.2.0, didn't appear with 1.1.0

**Comment by garethgeorge** [comment]
For a bit of extra context -- is this happening in the repo view or the plan view or both?

Are both of you using externally created snapshots? Do they use any of the backrest tags e.g. `plan` or `created-by`?

I have some ideas re: why this might be popping up, will patch in the next release.

**Comment by arminus** [comment]
> For a bit of extra context -- is this happening in the repo view or the plan view or both?

for me only in the repo view, I don't use plans (yet)

![2024-07-01_202918](https://github.com/garethgeorge/backrest/assets/683680/d1b75c28-79f5-4e2d-b47c-6ea44cb3c062)

> Are both of you using externally created snapshots? Do they use any of the backrest tags e.g. `plan` or `created-by`?

external snapshots from remote hosts via sftp. Not familiar with those tags...
 
> I have some ideas re: why this might be popping up, will patch in the next release.

appreciate the work!

**Comment by garethgeorge** [comment]
Ah, thanks for the extra info. This is pretty fixable and can be backfixed for the existing imported operations:

Linking some code for my future reference -- 

bug is in https://github.com/garethgeorge/backrest/blob/main/internal/orchestrator/tasks/taskindexsnapshots.go#L185-L195 , should be setting a default instance ID e.g. `_unassociated_` for imported snapshots if none can be inferred from tags. A low-risk oplog migration can be added to backfix this for operations that were imported incorrectly e.g. https://github.com/garethgeorge/backrest/blob/main/internal/oplog/migrations.go#L114C6-L114C28 can be reapplied.

**Comment by arminus** [comment]
Seems to be gone in 1.2.1

**Comment by garethgeorge** [comment]
Missed this in my testing -- thanks for the screenshot. I think I can see this and why I missed it. I have snapshots that are unassociated by plan but not by instance ID in my test repo. This is thankfully a straightforward fix.

**Comment by NoahPeeters** [comment]
Hey there, I still get the two `_unassociated_` entries. I even tried deleting all data and restarting backrest. After indexing the snapshots again, the two entries were there again. Anything I have to do to fix this?

![Screenshot 2024-08-15 at 09 31 46](https://github.com/user-attachments/assets/b476da62-5de2-47d5-b616-30ace3a36287)

**Comment by garethgeorge** [comment]
Hey, this is how backrest now displays unassociated operations (eg created outside of backrest). The top level of the tree indicates that the operations aren’t associated with an instance (there should be a tooltip on hover with some details) and the level below that indicates that there’s no associated plan. 

If you’re just using backrest for browsing this is OK and is expected behavior.
