### ISSUE TITLE
bug shfs as well as on the description on Restic Documentation to add the password

### ISSUE THREAD

**Issue by Mattia225** [garethgeorge/backrest#360]
hi me bug is

[unknown] failed to init repo: init failed: command "/home/mattia/.local/share/backrest/restic-0.16.4 init --json -o sftp.args=-oBatchMode=yes" failed: command "/home/mattia/.local/share/backrest/restic-0.16.4 init --json -o sftp.args=-oBatchMode=yes" failed: exit status 1
Output:
subprocess ssh: mattia@100.75.187.41: Permission denied (publickey,password).
Fatal: create repository at sftp://mattia@100.75.187.41:/mnt/Storage3/file-salvati failed: unable to start the sftp session, error: error receiving version packet from server: server unexpectedly closed connection: unexpected EOF

help me pis :(

**Comment by garethgeorge** [comment]
Closing this as a duplicate, there are a number of recent issues re: SSH which seem to primarily config related.

See https://github.com/garethgeorge/backrest/discussions/341 for a guide re: a working setup or feel free to open a discussion if you're still having issues. Hope this helps.
