### ISSUE TITLE
"restic-0.16.4.exe": cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by VFansss** [garethgeorge/backrest#379]
Hi there! I know that I should not keep this into this Issue, but I want to thank you for creating such a clear GUI for what I think could be the best backup software around

**Describe the bug**
I'm on Windows 10, installed Backrest 1.3.1 the day before yesterday through installer installer .exe, I don't remember preciselly installation settings but there wasn't anything particularly weird so I think I've choosed every default option.

I've created a Repository and a Plan. Done a demo backup, everythings fine.

Then I shut down my pc.

Yesterday evening I've started it again, and Backrest gave error on both scheduled Plan backup tentative and manual click on "Backup now"  button. The error is the same:

````
error: failed to initialize repo: init failed: command "restic-0.16.4.exe init --json -o sftp.args=-oBatchMode=yes" failed: command "restic-0.16.4.exe init --json -o sftp.args=-oBatchMode=yes" failed: exec: "restic-0.16.4.exe": cannot run executable found relative to current directory
````

I can't find any reference in manual, neither in online helps. The "executable not found" seems quite self-explanatory issue, but I'm not totally sure even where the restic .exe should be.

I avoided re-installing because maybe could be useful to not do so for debugging purposes.

**To Reproduce**

1. Start the PC, let Backrest start (is autolaunched at startup)
2. "Open WebUI" from traybar
3. Check failed automatic backup plan status, or click "Backup now" and get the immediate error

**Expected behavior**
Backup starts, in both scheduled and manual way

**Screenshots**
![immagine](https://github.com/garethgeorge/backrest/assets/15073502/9bf0c5d9-c824-4cdc-aaf5-766f47a10745)

**Platform Info**

- OS and Architecture: Win10 19045 Build, X64 build
- Backrest Version 1.2.1, installed though "Backrest-setup-x86_64.exe" from Github Release page

**Additional context**
I could try to reinstall or to create another Repository/Plan to furter test what happened.

No .exe has been deleted by antiviruses or anything like that.

**Comment by garethgeorge** [comment]
I think this is covered by https://pkg.go.dev/os/exec 's documentation of ErrDot :

```
ErrDot indicates that a path lookup resolved to an executable in the current directory due to ‘.’ being in the path, either implicitly or explicitly. See the package documentation for details.

Note that functions in this package do not return ErrDot directly. Code should use errors.Is(err, ErrDot), not err == ErrDot, to test whether a returned error err is due to this condition.
```

I've not seen this on my windows system though I have seen some reports of it from other users. I agree that backrest should be robust against this & should be providing an absolute path when checking the default locations where it tries to install restic.

You can check your PATH environment variable on windows for `.` and possibly try removing it as this isn't an issue on my system. Alternatively it's possible to start backrest using BACKREST_RESTIC_COMMAND=... and explicitly providing the path to restic , but this isn't compatible with the backrest installer so you'd need to start the software manually in this case.

I'll aim to get a patch out in the near term since this seems annoying is something I imagine a lot of users are hitting.

**Comment by garethgeorge** [comment]
Actually: an easy workaround is --

Backrest scans the PATH environment variable, so you can include a folder that contains the restic dependency it's looking for at the front of your PATH. Move the restic binary from C:\Program Files\backrest\restic-x.x.x.exe to another location e.g. C\backrest\deps\... and add that to the top of your path.

Will still aim to patch this in backrest itself for the next release.

**Comment by garethgeorge** [comment]
Fixed in the latest release, let me know if that addresses the problem for you.

**Comment by VFansss** [comment]
I've waited few days to be sure that everything was right.

I've tried v1.3.1, tried to mime what I've done with the previous version and...everything works fine!

Thanks for your effort, I guess Backrest will became my backend for backupping things on both my Windows machine and my Linux NAS.

Thanks again :)
