### ISSUE TITLE
Follow semver for publish Docker tags

### ISSUE THREAD

**Issue by forabi** [garethgeorge/backrest#382]
**Is your feature request related to a problem? Please describe.**
Currently, I have to keep manually checking for releases on Docker Hub, or blindly use "latest" tag in my docker compose files, which could easily introduce breaking changes

**Describe the solution you'd like**
It would be nice if a certain minor/patch release is also published as tag `v1` (in addition to `v1.x.x` and `v1.x`) so that users can stay up-to-date without risking breaking changes with `:latest`. The actual updates/notifications of new versions can then be handled by something like https://crazymax.dev/diun/

**Comment by garethgeorge** [comment]
Done with the latest patch release.
