### ISSUE TITLE
Size of certain backups not accurate since a couple versions

### ISSUE THREAD

**Issue by forabi** [garethgeorge/backrest#386]
**Describe the bug**
The size of this backup has grown quite significantly according to Backrest, but the size on disk seems to be around 1/10 of that:

![image](https://github.com/user-attachments/assets/d4b06cab-4045-4b70-8b4b-1b403cc9acef)

```bash
❯ sudo du -hs .
31G	
```

The stats tab confirms that the size is not that large:

![image](https://github.com/user-attachments/assets/9bfab246-d5fe-4d60-8d01-c3d79d6b4c4a)

**Expected behavior**
Size of backup reported correctly

**Platform Info**

- OS and Architecture [e.g. Windows 10 x64, Darwin arm64]
Backrest v1.3.0/Podman (4.9.3) Compose (2.28.1)/Ubuntu 24.04

**Comment by garethgeorge** [comment]
Are you certain you're covering all files in your backup set / have your excludes set correctly? The version of restic which actually does the filesystem scan + backup hasn't changed recently.

**Comment by forabi** [comment]
Apologies for posting this, turns out that I had a VM data disk sneak into the backed up folder, which is kind of huge. The reported size IS accurate.
