### ISSUE TITLE
Hook - Command - How to call a bash script?

### ISSUE THREAD

**Issue by mrcsrplln** [garethgeorge/backrest#387]
Hi, firstly thank you for your effort with Backrest, I am really finding it extremely useful.
I am having an "issue", probably due to my still limited knowledge of Linux.

**Basic Info**
- Running Backrest in a Docker Compose container on Debian 12
- Trying to run a bash script when a Restic backup starts/ends
- The bash script then calls Apprise to notify my own Telegram account

**What is the "issue"?**
- I cannot figure out how to configure Backrest to properly run my bash script
- I am thinking that maybe the "issue" is with Docker, for some reason

**What have I tried so far?**
- I placed the script in docker compose volumes available to Backrest and run the script in the following way from Backrest "Hook" command, which didn't work: 
`bash /path/to/script.sh` 
- I tried explicitly executing the script from Backrest "Hook" command by writing the full script as follows, but it didn't work either:  
 ` #!/bin/bash 
apprise -vv -t 'Restic Backup - Error!' tgram://...my_telegram_identification
`

If I run the script directly from shell in Debian it works fine and I get my telegram notification.

Any suggestions would be greatly appreciated.

**Comment by stefanomarty** [comment]
I had a similar problem using a hook with Backrest running in a Docker container. The main issue was that even if you make the script available on a volume, the entire script runs inside the container. Therefore, you need to make all the resources required by the script available inside the container as well.

Since there were no dependencies between the two, I decided to use cron to schedule the operation a few minutes before the Backrest job.

**Comment by mrcsrplln** [comment]
> I had a similar problem using a hook with Backrest running in a Docker container. The main issue was that even if you make the script available on a volume, the entire script runs inside the container. Therefore, you need to make all the resources required by the script available inside the container as well.
> 
> Since there were no dependencies between the two, I decided to use cron to schedule the operation a few minutes before the Backrest job.

Thanks. Yes that is a possible solution to be informed when a backup operation starts. 
But how do you tell if a backup actually completed or if it failed with an error?

**Comment by stefanomarty** [comment]
> But how do you tell if a backup actually completed or if it failed with an error?

Well... I'd probably use a Backrest hook :-) Just kiddin...

A long time ago I would have used an rpc call, but today I find it easier and more straightforward to use a webhook. You can install the server easily from here:
https://github.com/adnanh/webhook

Then you just need to configure the hook on the host server to launch your script, passing it all the necessary parameters. You can also put a reverse proxy in front of it and discover that many interesting things can be done with webhooks!

**Comment by mrcsrplln** [comment]
> > But how do you tell if a backup actually completed or if it failed with an error?
> 
> Well... I'd probably use a Backrest hook :-) Just kiddin...
> 
> A long time ago I would have used an rpc call, but today I find it easier and more straightforward to use a webhook. You can install the server easily from here: https://github.com/adnanh/webhook
> 
> Then you just need to configure the hook on the host server to launch your script, passing it all the necessary parameters. You can also put a reverse proxy in front of it and discover that many interesting things can be done with webhooks!

Thanks for the hint!! Will surely give it a go!

**Comment by stefanomarty** [comment]
Great, if you need any hint just send me a msg here, I'll be happy to help! Ciao.

**Comment by garethgeorge** [comment]
Just dropping in to add that you can use patterns like https://garethgeorge.github.io/backrest/cookbooks/command-hook-examples#notify-a-healthcheck-service to include properties from the hook in the webhook calls you issue using curl .

Fwiw if you're trying to configure telegram you might look at Backrest's shoutrrr integration which offers telegram support https://containrrr.dev/shoutrrr/v0.8/services/telegram/

**Comment by mrcsrplln** [comment]
As suggested by @stefanomarty , to solve the issue I used webhooks. So, basically:

1. Backrest calls (via curl) a hook provided by webhook (as systemd service), also passing specific parameters (e.g. disk name, status of snapshot etc...)
2. The hook calls a bash script, passing it the parameters received via curl
3. The bash script executes Apprise, which sends me a Telegram notification with a message containing the parameters set at point 1
4. I get my notifications when my backups misbehave...

Thanks again @stefanomarty for the support, I hadn't worked with webhooks before, this opens a lot of opportunities. Also thanks again to @garethgeorge for the amazing work with backrest.

**Comment by LeonNamowitz** [comment]
Just commenting for reference in case someone else doesn't want to go the long way around using webhooks like discussed above.

I solved it simply by creating a new SSH key pair with passwordless authentication, saving the config & keys in the persistent directory and then using something like 

`ssh -F /config/ssh/config.cfg root@myHost "/pathToScript/myScript.sh"`

as a hook. Probably not the most secure but works perfectly fine for me.
