### ISSUE TITLE
Update of included restic

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#391]
Hi George,

how about updating the included restic from 0.16.4  to  0.16.5  for any platforms?

[Download page](https://github.com/restic/restic/releases/)

Greetings

**Comment by garethgeorge** [comment]
Thanks for the ping on this, will aim to put an update out with the updated dependency in the next major version release. In the last restic release there were some regressions (e.g. issues w/repo compression and corruption). My thinking is to start trailing by a month or so for the default version installed by backrest unless it fixes significant issues.
