### ISSUE TITLE
error: Failed, orchestrator killed while operation was in progress

### ISSUE THREAD

**Issue by Gt1ult** [garethgeorge/backrest#398]
I am using the last version of backrest via docker. I am doing the backup via shh from one server to another on the same network. I am doing the backup of 600gb of pictures, but the process is lasting a lot as I had so far 6 times the error "error: Failed, orchestrator killed while operation was in progress." The destination server is connected via wifi to the network using Fenvi FU-AX1800 dongle (main OS is openmediavault). At the moment I am running the command "restic repair index" before resuming backup. Is it correct? I can I avoid this annoying issue? Thanks

**Comment by jakemauer** [comment]
Just wanted to chime in that I'm running into this issue as well. Using the backrest docker container with an SFTP repo.

**Comment by ianwyatt** [comment]
I’m seeing the same error, running backrest docker on Unraid backing up to a external drive

**Comment by Gt1ult** [comment]
Any advice to avoid this issue, it seems it does not appear with restic cli

**Comment by garethgeorge** [comment]
This error indicates that backrest was shutdown unexpectedly before an operation completed typically

**Comment by Gt1ult** [comment]
it was not shot down by me for sure, neither from docker I suppose

**Comment by garethgeorge** [comment]
If possible, please upload logs from the backrest process around the time that you run into the error e.g. from `docker logs -f` or similar. In particular I'd like to see the log messages immediately before the container restart and immediately after it's next startup. 

From the behavior you all are seeing it sounds like backrest is shutting down unexpectedly (there should be either a crash or graceful but unexpected shutdown somewhere in the logs) and similarly backrest checks for and logs any partial operations it finds in the operation log on startup.

Note: on linux logs are available from the systemd unit e.g the command should be `journalctl -u backrest.service`

**Comment by garethgeorge** [comment]
I suspect this may have been related to the race condition patched out in the last release, closing for now. Please reopen if still seeing crashes.
