### ISSUE TITLE
Backrest should provide options for rescheduling and running skipped tasks

### ISSUE THREAD

**Issue by JokerQyou** [garethgeorge/backrest#401]
**Describe the bug**

I'm running BackRest 1.2.0 with docker on unRAID. I have a repo scheduled to run backup every 7 days. But I also have unRAID's AppData-backup plugin set to backup docker container data (volumes and container definitions) every week. So before BackRest started the first scheduled backup, AppData-backup restarts BackRest container, and BackRest seems to re-schedule the next backup to be 7 days ahead of its startup point. This way the scheduled backup would never trigger.

**To Reproduce**

1. Go to backrest and configure a repo to backup evrery 7 days.
2. On the 6th day, restart the backrest container.
3. Backrest re-schedule the next backup to another 7 days ahead.

**Expected behavior**

I would expect backrest to store the schedule info into database or local configuration files so it survives container restarts.

**Screenshots**

None.

**Platform Info**

- unRAID 6.12.3. But this is not relevant, any Linux with docker would do.
- Backrest Version 1.2.0.

**Additional context**

I checked changelog for newer versions of backrest and found no mentioning of changes related to plan scheduling.

**Comment by garethgeorge** [comment]
Hey, Backrest now provides a solution for scheduling tasks relative to their "last run time" in 1.5.0 which should address this. Realizing I forgot to link the bugs at the time but this report was on my radar and related to https://github.com/garethgeorge/backrest/issues/372 which I've been tracking. 

Will go ahead and resolve this, feel free to ping on that issue w/any feedback on the solution if you have questions/run into issues.
