### ISSUE TITLE
Run Command results should be tracked in the operation log for long running commands

### ISSUE THREAD

**Issue by Gt1ult** [garethgeorge/backrest#402]
I have tun the command "check --read-data" in backrest but I cannot see the result as the backup is too big. Is there any way to see the result, unfortunately the command "check --read-data 2>&1 > output.log" is not working in backrest. Thanks

**Comment by garethgeorge** [comment]
The `Run Command` UI is a restic only shell (so it doesn't allow for running commands w/bash syntax e.g. piping etc). This is somewhat for simplicity's sake and adds a little security: it's not easily possible to use it as a way to get a general shell on your system (unless there's a bug in restic...).

I've retitled the bug to track making it easy to find logs for custom commands, the output handling is pretty ephemeral right now (really only streamed to the browser in memory, commands running in the background are terminated if the stream dies e.g. by leaving the tab for too long or reloading the page).

The feature is best suited to running quick operations e.g. listing snapshots, retagging them, etc. Slower operations e.g. check, prune, and such should be run using the restic UI at the moment. 

Leaving this to track some of the improvements needed to 
 * Better expose a history of commands run in the UI (as an operation type)
 * Support long running commands (perhaps with explicit cancellation?).

**Comment by Gt1ult** [comment]
Thanks so much for taking in consideration the feedback. Your solution are even better to me:

 1)   Better expose a history of commands run in the UI
  2)  Support long running commands

**Comment by garethgeorge** [comment]
Implemented https://github.com/garethgeorge/backrest/commit/bb00afa899b17c23f6375a5ee23d3c5354f5df4d as an intermediate term improvement to make cancellation behavior more obvious.

**Comment by garethgeorge** [comment]
Released with 1.6.0
