### ISSUE TITLE
Cannot set temp variable

### ISSUE THREAD

**Issue by qubist-pixel-ux** [garethgeorge/backrest#403]
Relevant Discussion : https://github.com/garethgeorge/backrest/discussions/399

**Describe the bug**
I am trying to set the path to temporary folders using environment variables.

Here are my variables :
![image](https://github.com/user-attachments/assets/b8670cad-88f6-4d93-b5e2-2430841bf521)

Restic still uses the default temporary directory at `C:\Windows\SystemTemp`. It does not read the TMP and TMPDIR values. Running restic from command line, it does use the different temp directory.

**To Reproduce**
1. Create backrest service using nssm. Use system account.
2. Set the variables shown in the image for a repository.
3. Run check against the repository to find temp folder in the command output

**Expected behavior**
It should use the temporary directory specified in variables

**Platform Info**
- OS and Architecture : Windows 11 x64
- Backrest Version : v1.3.1

**Comment by garethgeorge** [comment]
Hey, backrest doesn't have any special handling re: env vars -- they are pretty much forwarded through to the restic process so this is probably more of a restic question. 

But off the top of my head, I'm not sure if restic respects TMP/TEMP. Take a look at https://restic.readthedocs.io/en/latest/manual_rest.html#caching, those docs cover a few other env vars you should look at.

Perhaps give `RESTIC_CACHE_DIR` a go?

**Comment by qubist-pixel-ux** [comment]
> Hey, backrest doesn't have any special handling re: env vars -- they are pretty much forwarded through to the restic process so this is probably more of a restic question.
>
> But off the top of my head, I'm not sure if restic respects TMP/TEMP. Take a look at https://restic.readthedocs.io/en/latest/manual_rest.html#caching, those docs cover a few other env vars you should look at.

I asked this question in [restic forum](https://forum.restic.net/t/restic-does-not-use-temporary-directory-specified-in-environment-variable/8065). Restic does support [temp variables](https://restic.readthedocs.io/en/latest/manual_rest.html#temporary-files).

> Perhaps give `RESTIC_CACHE_DIR` a go?
Restic will still write temporary blobs to temp folder.

I am using nssm to start backrest and was running it with the local service account. This might have been the cause of issue. Modifying the service to use my personal account fixes this issue and restic uses the specified temporary directory.

Thanks for your help and developing this awesome software !

**Comment by qubist-pixel-ux** [comment]
I am using nssm to start backrest and was running it with the local service account. This might have been the cause of issue. Modifying the service to use my personal account fixes this issue and restic uses the specified temporary directory.

Thanks for your help and developing this awesome software !

**Comment by eec-kowen** [comment]
FYI to anyone coming here after backrest installer started offering Windows service installation, the process will run as SYSTEM. In your backrest environment config, you will need to set SYSTEMTEMP=MY _DIR instead of the ones documented in restic docs. Windows internal calls return SYSTEMTEMP to go under the hood instead of TMP or TEMP when running as the SYSTEM user.
