### ISSUE TITLE
Forget banner does not close automatically

### ISSUE THREAD

**Issue by fortysix2ahead** [garethgeorge/backrest#406]
**Describe the bug**
When forgetting a snapshot, a banner appears at the top "Forget in progress for plan XXX to YYY for ZZs". The seconds are counted up, but the dialog will never disappear when forgetting is actually done. It just keeps counting the seconds up.

**To Reproduce**

1. Simply forget a snapshot and watch the banner

**Expected behavior**
Banner shall disappear when forget job is done.

**Platform Info**

- Docker on ARM
- Backrest Version 1.3.1

**Comment by garethgeorge** [comment]
Hmm, this sounds like connection to the backend process was lost. Is this something that happens for you reproducibly?

**Comment by fortysix2ahead** [comment]
Yes, it happens always. There's a small popup that says "Snapshot forgotten" and it disappears, but the dark bar never does. When forgetting multiple snapshots the text is appended to the dark bar's text field and it looks like this:
<img width="1548" alt="image" src="https://github.com/user-attachments/assets/f1882f4d-3be4-4ad1-8b2a-491bd29a88e8">

**Comment by garethgeorge** [comment]
Fixed in 1.4.0
