### ISSUE TITLE
"Read pack data %" should allow decimal values

### ISSUE THREAD

**Issue by oliver-la** [garethgeorge/backrest#413]
**Is your feature request related to a problem? Please describe.**

A value of 1-100% is great for smaller repos, not so much for repos with over 10TBs. (or when the root partition only has a couple of GBs free)
1% of 10TB is already 100GB which is quite a lot. The UI only allows for integers when setting the "Read pack data %" value.

**Describe the solution you'd like**
I'd like to be able to set values like 0.1%. Or even better: be able to set a maximum size not in percentages, but in filesize units. (K, M, G, T)
The restic CLI allows for both usecases: https://restic.readthedocs.io/en/latest/045_working_with_repos.html#checking-integrity-and-consistency

**Comment by garethgeorge** [comment]
Fixed in 1.4.0

**Comment by oliver-la** [comment]
@garethgeorge Wow that was quick, thank you so much for your work!
