### ISSUE TITLE
On 1.4.0, getting "time bucketed policy must specify a non-empty bucket" error

### ISSUE THREAD

**Issue by aangelinsf** [garethgeorge/backrest#422]
**Describe the bug**
On macOS 14.6 with Backrest 1.4.0, setting up a plan fails with the error: "time bucketed policy must specify a non-empty bucket."

![screenshot_3299](https://github.com/user-attachments/assets/b58df97b-2c59-4966-9c37-fb4f866dec48)

**To Reproduce**
1. Mount drive to OS.
2. Add new repo to /Volumes/PL-GoogleBackup through Backrest.
3. Attempt to add new plan with only three field entries: the plan name, the repository and one path. See screenshot.
4. Click Submit. Error occurs.
5. Click on Cron but make no changes. Click Submit. Error occurs.

**Expected behavior**
I'm new to Restic so maybe this isn't correct but shouldn't the Plan should be accepted with a newly initialized repo? 

**Screenshots**
![screenshot_3299](https://github.com/user-attachments/assets/b58df97b-2c59-4966-9c37-fb4f866dec48)

**Platform Info**

- arm64
- Backrest Version 1.4.0

**Comment by garethgeorge** [comment]
Hey, sorry you're running into trouble here -- not a great error message. What this is telling you is that your retention policy must specify some non-zero retention value. E.g. set hourly to 48 to keep every snapshot for 2 days (or such).

https://garethgeorge.github.io/backrest/introduction/getting-started goes over what all of the options mean in detail.

**Comment by aangelinsf** [comment]
Thank you for the guidance. That worked. Looking forward to experimenting with it. Great job so far!
