### ISSUE TITLE
Backrest representation of sizes reported by restic may be misleading

### ISSUE THREAD

**Issue by digicommons** [garethgeorge/backrest#433]
**Describe the bug**
Restic outputs sizes in units based on powers of 2 (e.g. KiB, MiB, GiB etc.). Backrest on the other hand seems to report these exact values with the unit symbol for units based on powers of 10 (e.g. KB, MB, GB etc.)

**To Reproduce**
1. View past or running backups on plan page as well as detail component of a running backup.
2. Compare reported size to size of remote (e.g. 2.33 TB on Backrest vs. 2545 GB on Backblaze)

**Expected behavior**
Backrest should either display the unit symbols that restic uses (KiB, MiB, GiB etc.) or convert the values that restic provides to units based on powers of 10 and use the corresponding unit symbols (KB, MB, GB).

**Screenshots**
<img width="301" alt="image" src="https://github.com/user-attachments/assets/95d86246-5e62-4804-a4b0-ea3736b8d11e">

**Platform Info**
- Docker on ARM64
- v1.4.0

**Additional context**
Default restic output of backup sizes ([source](https://restic.readthedocs.io/en/latest/040_backup.html)), note the unit symbols:
```
scan finished in 1.837s: 5307 files, 1.720 GiB

Files:        5307 new,     0 changed,     0 unmodified
Dirs:         1867 new,     0 changed,     0 unmodified
Added to the repository: 1.200 GiB (1.103 GiB stored)

processed 5307 files, 1.720 GiB in 0:12
```

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/commit/cc173aa7b1b9dda10cfb14ca179c9701d15f22f5

**Comment by digicommons** [comment]
Thank you for fixing it this swiftly!
