### ISSUE TITLE
Restore percentage incorrect

### ISSUE THREAD

**Issue by mitchplze** [garethgeorge/backrest#442]
**Describe the bug**
This restore is 32.4% complete, but the progress bar and right-hand percent are wrong. 

![image](https://github.com/user-attachments/assets/f8084fd7-e292-4544-8499-67ee33728535)

**To Reproduce**

Restore a backup

**Comment by garethgeorge** [comment]
Thanks for the report! Fixed in https://github.com/garethgeorge/backrest/commit/656ac9e1b2f2ce82f5afd4a20a729b710d19c541
