### ISSUE TITLE
Responsive design: job status window doesn't update in narrow browsers

### ISSUE THREAD

**Issue by NelsonMinar** [garethgeorge/backrest#458]
I'm running a long backup job and watching the status update details. It works great in a wide browser. But when I make the browser narrow the design switches to move the job status into a small subwindow. When that happens the status box stops updating. The time still updates ("running for 20m13s") but the output from the backup command like Bytes Done or Current File don't. Those updates work fine in the wide browser view.

A second bug, not sure if related: if I resize from narrow to wide the UI glitches out and I get two copies of the details status box. The wide-view one does update, the narrow one does not.

Thank you for BackRest, it's a very nicely designed product. Was a delightful surprise to find these status update windows at all, I didn't expect such a grace note.

Here's the wide browser view where job updates seem to work.

![2024-09-05 08_28_29-Backrest](https://github.com/user-attachments/assets/b4a8a3cd-e8b2-4830-8696-97fb1a601d1d)

Here's the narrow view where job updates don't.

![2024-09-05 08_35_15-Backrest](https://github.com/user-attachments/assets/c0c411e9-d457-43ae-a706-b3b8a2f9d63d)

And here's the view where resizing the browser from narrow to wide causes a display glitch:

![2024-09-05 08_29_17-Backrest](https://github.com/user-attachments/assets/b4e8c800-7e7d-448b-ad9d-81a3880cb934)

**Comment by garethgeorge** [comment]
Hey,  glad backrest is largely working well for you and thanks for the detailed report. 

Interesting that updates seem paused in the narrow view — I’ll take a look at what’s going on there. 

On the modal side of things it’s also odd that it doesn’t stay centered. Not in front of my laptop right now so I’ll aim to look at this over the weekend but I wonder if the same happens with the various add / update repo / plan UI views. 

It’s been on my todo list to standardize the modal component used by those views — this may be a good opportunity.

**Comment by garethgeorge** [comment]
Ah, makes more sense. Thanks -- I think there's 3 behaviors that deserve fixing here overall 

[ ] High priority -- modal panel should refresh when popped out -- this is broken today b/c the modal is only updated with the backup info on selection https://github.com/garethgeorge/backrest/blob/main/webui/src/components/OperationTree.tsx#L121-L133 
[ ] Modal panel should pop back into sidebar if the window is expanded again
[ ] Modal panel should responsively resize itself to main a ratio of the screen width -- I'll take a look at how well this can be addressed, this isn't a native antd (UI framework under the hood) capability but hopefully can be addressed nicely with a little bit of added JS

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/commit/0d01c5c31773de996465574e77bc90fa64586e59

**Comment by garethgeorge** [comment]
Released in 1.5.0!

**Comment by NelsonMinar** [comment]
Verified all the fixes work for me! Thank you.
