### ISSUE TITLE
 backrest[2584]: segfault on Ubuntu 24.04

### ISSUE THREAD

**Issue by reset12** [garethgeorge/backrest#464]
I installed Backrest on Ubuntu 24.04 an get a  backrest[2584]: segfault at 0 ip 000000000046b824 sp 00007ffd0bb14f90 error 4 in backrest[400000+66f000] likely on CPU 4 (core 0, socket 0).

On Ubuntu 23.10 it works perfect.

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

Installed with:
# install backrest server
cd /tmp
mkdir backrest
cd backrest
wget https://github.com/garethgeorge/backrest/releases/download/v1.4.0/backrest_Freebsd_x86_64.tar.gz
tar -xvf backrest*
cd backrest
./install.sh

**Comment by garethgeorge** [comment]
Hey — from your install command it looks like you’re pulling the FreeBSD installer — is that intentional? You most likely want backrest_Linux_x86_64

**Comment by reset12** [comment]
You are right. Its my error.
Thank you for that hint.

**Comment by reset12** [comment]
please close that issue.

**Comment by garethgeorge** [comment]
No problem
