### ISSUE TITLE
API error: reconnecting

### ISSUE THREAD

**Issue by lucius346346** [garethgeorge/backrest#468]
I'm encountering this error every few minutes, regardless of what Backrest is doing. However, the UI appears to be functioning properly, and there doesn't seem to be any actual disconnection.

**Screenshots**
![image](https://github.com/user-attachments/assets/69456cd0-d904-4d49-b10d-aab254df6eae)

**Platform Info**
- Ubuntu 24.04.1
- Backrest 1.5.0 running on Docker

**Comment by garethgeorge** [comment]
Hey, Backrest will immediately reconnect but this usually indicates that something is timing out it's http streaming requests to the backend. 

If using nginx or another reverse proxy check the request timeout settings -- these are usually to blame and should be set fairly high for backrest (e.g. 15 min or greater).

**Comment by garethgeorge** [comment]
See https://github.com/garethgeorge/backrest/issues/394 for a bit of additional context.

**Comment by lucius346346** [comment]
I do use Nginx. Increasing timeout fixed it. Thanks.
