### ISSUE TITLE
Blank screen in stats

### ISSUE THREAD

**Issue by molnarti** [garethgeorge/backrest#470]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/discussions).

**Describe the bug**
When i click on the Stats tab of a local repo i get a blank screen

**To Reproduce**

1. Open repo settings
2. Click on Stats tab
3. Get a blank screen 

**Expected behavior**
The stats tab with the charts should be shown

**Screenshots**
N/A, just a white screen

**Platform Info**

- Linux Debian 12
- Backrest Version 1.5.0

**Additional context**
Other repo (S3 backblaze) is showing the stats correctly. Calculating new stats did not help

**Comment by garethgeorge** [comment]
Thanks for the report -- next time you see this happen please check your JS console and see if any errors are reported -- sounds like a bug is killing the UI.

**Comment by marcschuler** [comment]
Happend to me on a repository where the last "check" failed.

StackTrace:

![image](https://github.com/user-attachments/assets/82480f51-c219-4a08-9fd0-070f44f0d9d7)

**Comment by garethgeorge** [comment]
Thanks -- should be fixed by https://github.com/garethgeorge/backrest/commit/d59c6fc1bed06718c49fc87bfc5bf143a10ac5ed in the next patch release :)

**Comment by garethgeorge** [comment]
Went out in the patch release, should be fixed! Let me know if you still get an error after the update.
