### ISSUE TITLE
No stats computed after Prune

### ISSUE THREAD

**Issue by Cheezzhead** [garethgeorge/backrest#475]
**Describe the bug**
It's not officially documented, but in the reply [here](https://github.com/garethgeorge/backrest/issues/166#issuecomment-2014430316) it's mentioned that stats are computed after each prune operation:

> Re: compute stats automatically, compute stats does actually run automatically after prune operations! It's quite infrequent but this is intentional as it's a pretty expensive operation in terms of API calls (which aren't free on all backends e.g. backblaze, s3, etc). The other argument for defaulting to running after prunes is that this is when the repo size is most consistent because dangling data has just been deleted by the prune operation.

This is great but it's not actually happening on my installation. I also don't see any option to enable or disable. Is there anything I'm missing?

**To Reproduce**

1. Perform or schedule a prune
2. Check 'Compute Stats' page.

**Expected behavior**
Stats should be computed after each prune operation completes.

**Platform Info**

- Ubuntu 20.04; Docker
- 1.5.0

**Additional context**

**Comment by garethgeorge** [comment]
Hey -- there's probably an improvement to be made here. The conditions for a check running are 

 1. After a prune
 2. It has been 30 days or more since the last check operation ran

This is done because stats operations are quite slow / scan a lot of the index. I wanted to default to running them relatively infrequently as not all users will frequently check the dashboard.

**Comment by garethgeorge** [comment]
Increased frequency to 1x daily in 1.6.0 (run after prune)

**Comment by Cheezzhead** [comment]
The new GUI looks amazing!

Unfortunately stats are still not being computed after a prune (or ever, really). Having used backrest for about a month now, the only time the 'compute stats' have ever run is when I started it manually.
