### ISSUE TITLE
Prune Policy does not allow decimal numbers

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#477]
When showing a plan options, the prune policy Max Unused after prune option shows as a float:
![image](https://github.com/user-attachments/assets/9d3d4c0f-b17f-4462-a296-c837bcf94db0)
but if trying to change to a decimal number, it triggers an error when trying to save:
![image](https://github.com/user-attachments/assets/7a38ec2e-6b46-4026-a353-e63ef69be143)
Seems this option is defined as int32, but I would expect it to be a float. Or at least to show the interface consistently with kind of values we can save.

**Comment by garethgeorge** [comment]
Thanks for the report! This definitely is definitely a bug, I'll patch this by converting the field to a float in the next bugfix release.

**Comment by garethgeorge** [comment]
Should be fixed in the latest release
