### ISSUE TITLE
why is a dot an "invalid symbol" for Repo Name?

### ISSUE THREAD

**Issue by GuitarBilly** [garethgeorge/backrest#48]
hello! 
FYI - I am trying out backrest on linux, deployed via docker...

When i choose **`Add Repo`** to "Add Restic Repository", the first field **`Repo Name`** will not accept a dot in the name. As my normal repository nomenclature is `myname.repo` so Backrest complained: `invalid symbol`.

Restic allows me to put dots in the name, why not Backrest?

p.s. for now I continued with `myname_repo` so it is a minor item for me.

**Comment by GuitarBilly** [comment]
upon some further usage I can answer my own question:
the `Repo Name` is not the name of the actual created repo folder. That is in the `URI` and the URI accepts a complete path with dots wtihout problem.

**Comment by garethgeorge** [comment]
fwiw this is a reasonable feature request. I'll try to relax the validation done on repo names. When I first designed this I was a bit over-cautious on validation. I think backrest is actually flexible enough that I can reasonably relax this to admit all symbols (and honestly even Unicode should be fine).

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/commit/ee6134af76c3e90f542f67b89b2571f060db5590
