### ISSUE TITLE
Windows installer is missing version and icon

### ISSUE THREAD

**Issue by auanasgheps** [garethgeorge/backrest#481]
**Describe the bug**
Windows installer is missing version and icon, showing no icon and a fake version: 00.00.00.00

**To Reproduce**
Install BackRest on Windows

**Expected behavior**
Whilst the icon is only a nice to have, having the real version displayed enables the user to know which version is installed using Settings/Control Panel, like almost all applications do.
Also, it will allow for submission to Windows Package Manager (winget)! 

**Screenshots**
![immagine](https://github.com/user-attachments/assets/0269605f-dd6e-4a91-8617-ef58fe69e37a)

**Platform Info**

- OS and Architecture: Windows 10 x64
- Backrest Version: 00.00.00.00... joking, 1.5

**Additional context**

**Comment by garethgeorge** [comment]
Hey, thanks for making an issue to help track this. Definitely something that needs fixing, my bandwidth with other refactors has been a bit sparse to get to it.

Adding a few notes on what needs to happen to fix this:

What needs to happen here is plumbing the tag that the github actions workflow is running on into the .nsis script [here](https://github.com/garethgeorge/backrest/blob/main/build/windows/install.nsi#L6).

I believe nsis variables are just env vars -- it may be as simple as fixing https://github.com/garethgeorge/backrest/blob/main/scripts/generate-installers.sh#L3-L20 to pass through an env variable to the docker container e.g. VERSION= ... 

I think the VERSION can be determined correctly in the github actions workflow by using `${{  github.ref_name }}"` as the reference.

**Comment by brokoler** [comment]
I recognized the same issue on Windows 11 at multiple locations, using backrest v1.6.1.
The issue can be reproduced only via installing backrest v1.6.1 to any Windows system.

Desktop Icons:
![grafik](https://github.com/user-attachments/assets/40cfefa9-0d73-4801-9d28-150d4826b37f)

Startmenu Icons:
![{43E37E4E-8471-4472-B3F4-3D5634D60CFB}](https://github.com/user-attachments/assets/f46eca86-d440-4a80-a25b-968e608c68cf)

**Comment by auanasgheps** [comment]
![immagine](https://github.com/user-attachments/assets/454dbcf6-af07-4864-9e31-b8007276cc28)
![immagine](https://github.com/user-attachments/assets/30cd160f-7435-4e3c-869a-cf82c3ece28f)

Finally! The issue is resolved for me
