### ISSUE TITLE
Add an option to backup Linux servers via SFTP

### ISSUE THREAD

**Issue by insinfo** [garethgeorge/backrest#489]
Add an option to backup Linux servers via SFTP, I currently need a tool that can backup several Debian Linux servers via SFTP without having to install anything on the server, I currently do this via several scripts which is not a very good solution.

**Comment by inode64** [comment]
Restic includes SFTP support as standard
https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp

**Comment by garethgeorge** [comment]
Afraid that this isn't something well supported by restic's model -- at the very least restic would need to run on the remote machines. The second technical challenge is that backrest uses env vars to propagate settings to restic which it forks. It would need a fairly different execution model to do this over SFTP (not as simple as just forwarding the command).

**Comment by inode64** [comment]
Another option is https://github.com/restic/rest-server
I use it for Windows clients

**Comment by garethgeorge** [comment]
I'm going to close this as not planned for the time being, I think the right approach here is to run backrest on each machine you'd like to backup.
