### ISSUE TITLE
add restic rest-server prune , forget and check configuration

### ISSUE THREAD

**Issue by kreutpet** [garethgeorge/backrest#493]
**Is your feature request related to a problem? Please describe.**
Backrest Webui provides possibility to configure a backup to rest-server backup
The repository definition in backrest includes settings for prune , forget and check policies.
could theses activities be delegated to the rest-server based on the configuration given in the repository configuration

**Describe the solution you'd like**
the prune, forget and check policy shall run on the reset server for the coresponding repository based on the configurations given in the repository
the activities should run on the rest-server without backrest

**Comment by garethgeorge** [comment]
iiuc rest-server is primarily a proxy for local disk storage. Does it support running prune and check?

At the moment this is a feature I have planned for multi-host management which is a long-term project on the roadmap. Looking most likely I'll get to it late this year or early next.

**Comment by garethgeorge** [comment]
Closing this with inactivity, I don't think this model is supported by the rest server. Please correct if I'm misunderstanding something .
