### ISSUE TITLE
running backrest as backup user

### ISSUE THREAD

**Issue by kreutpet** [garethgeorge/backrest#496]
**Describe the bug**
i try to backup the entire /.
i see that the systemd process starting after boot is using the user account that used during install.

i changed the user to backup in the assumption that the user is created by ubuntu to have required access permission.

```
`[Unit]
Description=Backrest Service
After=network.target

[Service]
Type=simple
User=backup
Group=backup
ExecStart=/usr/local/bin/backrest
Environment="BACKREST_PORT=127.0.0.1:9898"

[Install]
WantedBy=multi-user.target
` 
```

after i restarted the backrest i get the following error message

```
Sep 25 19:25:46 bilbo backrest[4816]: 2024-09-25T19:25:46.471+0700        ERROR        error creating logs directory "mkdir /var/backups/.local: permission denied", will only log to conso>
Sep 25 19:25:46 bilbo backrest[4816]: 2024-09-25T19:25:46.472+0700        INFO        installing restic /var/backups/.local/share/backrest/restic-0.17.1 to 0.17.1...
Sep 25 19:25:46 bilbo backrest[4816]: 2024-09-25T19:25:46.472+0700        FATAL        error finding or installing restic: install restic: mkdir /var/backups/.local: permission denied

```

**To Reproduce**

1. install backrest with sudo
2. change service file /etc/systemd/system/backrest.service and change user and group to 'backup' 
3. restart service

**Expected behavior**
service should start sucessfull as backup user

**Platform Info**
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
- Backrest Version [1.5.1]

**Additional context**
i changed user of backrest service to ensure that entire / can be backuped

**Comment by garethgeorge** [comment]
Hi, I'm afraid this is more of a linux configuration item you're asking about. Your backup user must be configured with sufficient permissions to read all directories you'd like to backup. I think this looks like expected behavior.

**Comment by kreutpet** [comment]
I was investigating the backup user in ubuntu.
It looks like this is a default user that is prepared for backup applications.  It should have no login and ssh but home folder is /var/backups.

I will run a  test  and create the required folder structure for backrest to see if the backup process starts and access is available for the required filesystem of / to be backuped .

I will come back to you

**Comment by kreutpet** [comment]
I verified to run the backrest with backup user account in ubuntu.
unfortunetly it did not work sucessfully.

first I created the required .local .config and .cache in the /var/backup folder
The backrest started sucessfuly .
When I then start the backup process manually the backup user gets a permission denied on my user home folder.
So i guess the ubuntu default backup user seems not to be a good choice .

I need to read more how the backup user is configured.
I guess it is also not a good practice to run backrest with root permissions.

**Comment by kreutpet** [comment]
i followed now the guidline from restic 
https://restic.readthedocs.io/en/stable/080_examples.html#backing-up-your-system-without-running-restic-as-root
i installed backrest in the home folder of the new restic user.
I created the required folders for backrest in restic home 
backrest starts sucessfully.

if i now start a backup of a home directory of another user i do get a persmission denied 

`[restic] {"message_type":"error","error":{"message":"openfile for readdirnames failed: open /home/peter: permission denied"},"during":"archival","item":"/home/peter"}
[tasklog] 2024-09-28T09:45:26.449+0700	warn	backup for plan "daily"	an unknown error was encountered in processing item: /home/peter`

root can access the home folder but restic not 
i need read more about user configuration in  ubuntu about the restic user getting to proper access rights

**Comment by nocivo72** [comment]
I find more simple way to backup all files, also root system files, from backrest running from normal user. 

Put this two line on ` /etc/systemd/system//backrest.service` and restart the service :

```
[service]
...
AmbientCapabilities=CAP_DAC_READ_SEARCH
CapabilityBoundingSet=CAP_DAC_READ_SEARCH
...
```
I don't know if there are security issue or any other problem. I'm not an expert but it works.

**Comment by garethgeorge** [comment]
This is a really interesting solution -- thanks for sharing it. I'm wondering if it would make sense for me to update the installer to include a prompt to set this option.

Probably not something the installer should do by default, but it's something that the installer could set if the user opts in. I think this is a painpoint for a lot of users that either 

 1. Run as root today
 2. Have to carefully manage groups and permissions to ensure that backrest has access to their files.

Making the backrest process privileged, but only in the sense that it can read the full disk is imo a nice way to go.

**Comment by nocivo72** [comment]
> This is a really interesting solution -- thanks for sharing it. I'm wondering if it would make sense for me to update the installer to include a prompt to set this option. .....
>

It would also be helpful to include the two lines commented with a brief description in the backrest.service file. If the installer prompts the user to activate this solution, it would be ideal, although not strictly necessary until potential security issues are investigated and communicate to the end users.

To find this solution, I spent a lot of time searching the internet and reading extensively before finally discovering it on the Restic GitHub:

https://github.com/restic/restic/issues/4991

Since backing up system files is a very common need, it's important to provide this option for end users.

I really like Backrest. Before I discovered it, I used Backintime for backups, but it was very slow, especially when handling large amounts of data. I've always wanted to switch to Restic, but I found it too time-consuming to learn compared to my needs. With Backrest, I found the perfect solution. Thank you so much!

**Comment by pmmontanari** [comment]
> I find more simple way to backup all files, also root system files, from backrest running from normal user.
> 
> Put this two line on ` /etc/systemd/system//backrest.service` and restart the service :
> 
> ```
> [service]
> ...
> AmbientCapabilities=CAP_DAC_READ_SEARCH
> CapabilityBoundingSet=CAP_DAC_READ_SEARCH
> ...
> ```
> 
> I don't know if there are security issue or any other problem. I'm not an expert but it works.

I know this is an old closed thread but I just wanted to say that the solution is still working for me after I got permission errors

Edit: typo
