### ISSUE TITLE
SFTP repos fail - ssh not found

### ISSUE THREAD

**Issue by reset12** [garethgeorge/backrest#50]
At start of install.sh i got the following error on a fresh Linux-Debian-Bookworm:
`++ uname -s
+ OS=Linux
+ '[' Linux = Darwin ']'
+ '[' Linux = Linux ']'
+ echo 'Installing on Linux'
Installing on Linux
+ install_unix
+ echo 'Installing backrest to /usr/local/bin'
Installing backrest to /usr/local/bin
+ sudo mkdir -p /usr/local/bin
++ ls -1 backrest
++ head -n 1
ls: Zugriff auf 'backrest' nicht möglich: Datei oder Verzeichnis nicht gefunden
+ sudo cp /usr/local/bin
cp: Fehlender Zieldatei‐Operand hinter '/usr/local/bin'
„cp --help“ liefert weitere Informationen.
+ create_systemd_service
+ '[' '!' -d /etc/systemd/system ']'
+ echo 'Creating systemd service at /etc/systemd/system/backrest.service'
Creating systemd service at /etc/systemd/system/backrest.service
+ sudo tee /etc/systemd/system/backrest.service
++ whoami
++ whoami
+ echo 'Reloading systemd daemon'
Reloading systemd daemon
+ sudo systemctl daemon-reload
+ echo 'Enabling systemd service backrest.service'
Enabling systemd service backrest.service
+ sudo systemctl enable backrest
+ sudo systemctl start backrest
`

**Comment by garethgeorge** [comment]
Looks like some files aren't being found -- it looks like it couldn't find backrest in the cwd. Can you perhaps include the command you're using when running `./install.sh`? 

It may be an error to run the command as `./extracted-folder/install.sh`, you'll need to cd into the folder and run it as `./install.sh`. Might that be your issue? 

If that is the problem, there's probably still a bug here -- ideally the installer shouldn't care about the working directory. I'll try to provide a version that isn't sensitive to this.

**Comment by reset12** [comment]
I was in the extracted directory. You can send me the update for a test. 

`@mx:~/Downloads/backrest-main
$ ls -al
insgesamt 156
drwx------ 10 t759f t759f  4096 15. Jan 23:38 .
drwxr-xr-x  3 t759f t759f  4096 15. Jan 23:51 ..
-rw-r--r--  1 t759f t759f  4019 15. Jan 23:38 backrest.go
-rw-r--r--  1 t759f t759f 26474 15. Jan 23:38 CHANGELOG.md
-rw-r--r--  1 t759f t759f   963 15. Jan 23:38 CONTRIBUTING.md
-rw-r--r--  1 t759f t759f   244 15. Jan 23:38 Dockerfile
drwx------  3 t759f t759f  4096 15. Jan 23:38 gen
drwx------  3 t759f t759f  4096 15. Jan 23:38 .github
-rw-r--r--  1 t759f t759f    37 15. Jan 23:38 .gitignore
-rw-r--r--  1 t759f t759f  1121 15. Jan 23:38 go.mod
-rw-r--r--  1 t759f t759f  1404 15. Jan 23:38 .goreleaser.yaml
-rw-r--r--  1 t759f t759f  6303 15. Jan 23:38 go.sum
-rwxr-xr-x  1 t759f t759f  2079 15. Jan 23:38 install.sh
drwx------  9 t759f t759f  4096 15. Jan 23:38 internal
-rw-r--r--  1 t759f t759f 35149 15. Jan 23:38 LICENSE
drwx------  3 t759f t759f  4096 15. Jan 23:38 pkg
drwx------  5 t759f t759f  4096 15. Jan 23:38 proto
-rw-r--r--  1 t759f t759f 11074 15. Jan 23:38 README.md
drwx------  2 t759f t759f  4096 15. Jan 23:38 scripts
drwx------  3 t759f t759f  4096 15. Jan 23:38 test
-rwxr-xr-x  1 t759f t759f  1259 15. Jan 23:38 uninstall.sh
drwx------  5 t759f t759f  4096 15. Jan 23:38 webui

@mx:~/Downloads/backrest-main
$ bash -x ./install.sh
++ uname -s
+ OS=Linux
+ '[' Linux = Darwin ']'
+ '[' Linux = Linux ']'
+ echo 'Installing on Linux'
Installing on Linux
+ install_unix
+ echo 'Installing backrest to /usr/local/bin'
Installing backrest to /usr/local/bin
+ sudo mkdir -p /usr/local/bin
++ ls -1 backrest
++ head -n 1
ls: Zugriff auf 'backrest' nicht möglich: Datei oder Verzeichnis nicht gefunden
+ sudo cp /usr/local/bin
cp: Fehlender Zieldatei‐Operand hinter '/usr/local/bin'
„cp --help“ liefert weitere Informationen.
+ create_systemd_service
+ '[' '!' -d /etc/systemd/system ']'
+ echo 'Creating systemd service at /etc/systemd/system/backrest.service'
Creating systemd service at /etc/systemd/system/backrest.service
+ sudo tee /etc/systemd/system/backrest.service
++ whoami
++ whoami
+ echo 'Reloading systemd daemon'
Reloading systemd daemon
+ sudo systemctl daemon-reload
+ echo 'Enabling systemd service backrest.service'
Enabling systemd service backrest.service
+ sudo systemctl enable backrest
+ sudo systemctl start backrest

`

**Comment by garethgeorge** [comment]
From the `ls` results there it looks like you've downloaded the source archive from the releases page, make sure you're downloading a prebuilt binary for your platform e.g. most likely [backrest_Linux_x86_64.tar.gz](https://github.com/garethgeorge/backrest/releases/download/v0.10.0/backrest_Linux_x86_64.tar.gz).

**Comment by reset12** [comment]
Youare right, it works now with the link you send.
with regards
Bruno

On Tue, 16 Jan 2024 09:53:43 -0800
Gareth ***@***.***> wrote:

> From the `ls` results there it looks like you've downloaded the source archive from the releases page, make sure you're downloading a prebuilt binary for your platform e.g. most likely [backrest_Linux_x86_64.tar.gz](https://github.com/garethgeorge/backrest/releases/download/v0.10.0/backrest_Linux_x86_64.tar.gz).
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/garethgeorge/backrest/issues/50#issuecomment-1894230873
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


--
***@***.*** ***@***.***>

**Comment by reset12** [comment]
Is it possible to make a hardcopy of the defines for build a repro with sftp like s3 ?for the manual.

with regards
Bruno

On Tue, 16 Jan 2024 09:53:43 -0800
Gareth ***@***.***> wrote:

> From the `ls` results there it looks like you've downloaded the source archive from the releases page, make sure you're downloading a prebuilt binary for your platform e.g. most likely [backrest_Linux_x86_64.tar.gz](https://github.com/garethgeorge/backrest/releases/download/v0.10.0/backrest_Linux_x86_64.tar.gz).
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/garethgeorge/backrest/issues/50#issuecomment-1894230873
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


--
***@***.*** ***@***.***>

**Comment by garethgeorge** [comment]
Great! Sounds like this unblocks you -- I've gone ahead and opened https://github.com/garethgeorge/backrest/issues/51 to track the other issue discussed w.r.t. relative paths to the installer, I'll have that fixed in the next release.

**Comment by garethgeorge** [comment]
Sorry, I missed the followup question wrt the sftp usecase. Can you elaborate a bit on the issue you're running into there?

**Comment by reset12** [comment]
I tried to create the repro and get an error:
Operation failed: [unknown] failed to init repo: init failed: command "/home/t759f/.local/share/backrest/restic-0.16.3 init --json" failed: exit status 1 Process STDOUT: Fatal: create repository at sftp://t759f@192.168.178.7/mnt/backups/restic-repo/ failed: exec: "ssh": executable file not found in $PATH 

My definitions are:
![Bildschirmfoto_2024-01-17_10-23-53](https://github.com/garethgeorge/backrest/assets/14790813/265102de-8a8b-435f-bc4f-379a8f39dbcf)

I am be able to connect passwordless with ssh to the server 192.168.178.7.

**Comment by garethgeorge** [comment]
Really interesting -- this probably is a bug in how backrest is starting restic. I'll take a look at this tonight, it looks like I'm probably setting up the PATH env variable incorrectly when spawning restic.

**Comment by garethgeorge** [comment]
This took me a bit longer to look at than I expected.

https://github.com/garethgeorge/backrest/commit/bedb302a025438a58309f26b046c9b6d49316414 should correctly provide the PATH environment variable when initializing the repo (which is why sftp wasn't being found). I'll put out a release with the fix in the next few days.

**Comment by Kruze9** [comment]
I have encountered the same problem in a Docker install when attempting to add a repository.

Operation failed: [unknown] failed to init repo: init failed: command "/data/restic-0.16.4 init --json -o sftp.args=-oBatchMode=yes" failed: exit status 1 Process STDOUT: Fatal: create repository at sftp:restic@10.0.0.3:/mnt/BACKUP/restic/srv/restic-repo failed: exec: "ssh": executable file not found in $PATH

{
  "id": "truenas",
  "uri": "sftp:restic@10.0.0.10:/mnt/BACKUPS/restic/",
  "password": "password",
  "prunePolicy": {
    "maxFrequencyDays": 7,
    "maxUnusedPercent": 25
  }
}

**Comment by brightdroid** [comment]
Same problem here, could you please add sftp/ssh to the docker image?
