### ISSUE TITLE
Adding a repo hangs on Windows

### ISSUE THREAD

**Issue by mikejsavage** [garethgeorge/backrest#502]
**Describe the bug**

Adding a repo on Windows hangs, the network inspector says it's stuck in AddRepo:

![image](https://github.com/user-attachments/assets/602a7fcc-f369-4468-aa72-c29528baa196)

The generated JSON config is

```
{
  "id": "nas",
  "uri": "sftp:root@100.64.0.4:/pool/restic",
  "password": "redacted",
  "flags": [
    "-o sftp.args=\"-i C:/id_ed25519\""
  ],
  "prunePolicy": {
    "maxUnusedPercent": 10,
    "schedule": {
      "clock": "CLOCK_LAST_RUN_TIME",
      "disabled": true
    }
  },
  "checkPolicy": {
    "readDataSubsetPercent": 0,
    "schedule": {
      "clock": "CLOCK_LAST_RUN_TIME",
      "disabled": true
    }
  },
  "autoUnlock": true
}
```

If I refresh the page the repo is not there, if I get it wrong (e.g. no sftp.args) then AddRepo returns 500 immediately and that's fine.

Unfortunately I have no debug symbols and it seems like Go can't generate them for Windows so the stack trace I can give you is limited to

![image](https://github.com/user-attachments/assets/8450d441-140f-432c-beda-ef03d74c8194)

**Platform Info**

Windows 10 IOT x64, backrest 1.5.1 from the releases page

**Comment by garethgeorge** [comment]
Hey, this usually indicates that you hit the SFTP password prompt. Backrest tries to set a batchmode option which disables prompts for sftp but it’s overridden when specifying the args flag manually. 

I talk about this a little in https://github.com/garethgeorge/backrest/issues/165#issuecomment-2166702417 and there are a few other topics related to SFTP setup in the discussions section that might help!

**Comment by mikejsavage** [comment]
It was stuck on the host key verification prompt, so setting flags to `-o ssh.args="-i blah -o BatchMode=yes -o StrictHostKeyChecking=accept-new"` worked.

Thanks!

**Comment by mikejsavage** [comment]
Btw it might be worth mentioning this in the docs, https://github.com/garethgeorge/backrest/blob/main/docs/content/1.introduction/1.getting-started.md just tells you to use `-o sftp.args="-i /path/to/key"` which is a bit of a landmine
