### ISSUE TITLE
Windows 1.5.1 not work on 32 bit

### ISSUE THREAD

**Issue by cmbcbe** [garethgeorge/backrest#520]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/discussions).

**Describe the bug**
the version 1.5.1, whenever from setup or flat .exe not work on 32 bits windows

**To Reproduce**
simply launch backrest.exe

**Expected behavior**
shouls work isn't it?

- OS and Architecture [e.g. Windows 10 x64, Darwin arm64]
Windows 10 22H2 32bits

**Comment by cmbcbe** [comment]
I have try to buil:d from source with a git clone and building on a linux to target os
```
export GOOS=windows
export GOARCH=386
(cd webui && npm i && npm run build)
(cd cmd/backrest && go build .)

```
But i get this error
../../webui/webuiwin.go:12:12: pattern dist-windows/*: no matching files found

**Comment by garethgeorge** [comment]
Sorry -- the docs you followed are out of date for windows. You'll want to run 

```
GOOS=windows go generate ./...
GOOS=windows go build <backrest bin>
```

**Comment by cmbcbe** [comment]
thanks, i have successfully build 32 bits binary for windows on a debian 12 like this:
```
<install go>
<git clone backrest>
```

```
go install github.com/goreleaser/goreleaser@latest
apt install -y protobuf-compiler nodejs npm
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install github.com/bufbuild/buf/cmd/buf@v1.27.2
go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
npm install -g @bufbuild/protoc-gen-es @connectrpc/protoc-gen-connect-es
```

```
GOOS=windows GOARCH=386 go generate ./...
GOOS=windows GOARCH=386 go build ./cmd/backrest/backrest.go
```

**Comment by garethgeorge** [comment]
Thanks for giving that a go and documenting what worked. I think for the time being, this will probably remain a project that needs building from source for 32-bit windows just because of the rarity of the deployment and given that Windows 11 will deprecate 32 bit support in the relatively near term. 

Happy to re-evaluate if enough people come back and let me know this is a problem :) .

**Comment by cmbcbe** [comment]
Hello,

this is because Backrest is a wonderfull product, light and reliable i use it on low end computers (also)...
