### ISSUE TITLE
failed to read directory /home/USERNAME/.local/share/backrest/rotatinglogs after setup

### ISSUE THREAD

**Issue by mrmorawski** [garethgeorge/backrest#523]
**Describe the bug**
I installed backrest 1.6.0 using the most recent binary and installer from releases in this repository. The install script creates a systemd service, but that service crashes and cannot be started. `systemctl status backrest` gives the following output:

```
× backrest.service - Backrest Service
     Loaded: loaded (/etc/systemd/system/backrest.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-10-20 16:33:13 CEST; 1min 20s ago
   Duration: 88ms
    Process: 2099 ExecStart=/usr/local/bin/backrest (code=exited, status=1/FAILURE)
   Main PID: 2099 (code=exited, status=1/FAILURE)
        CPU: 26ms

Okt 20 16:33:13 wopr systemd[1]: Started backrest.service - Backrest Service.
Okt 20 16:33:13 wopr backrest[2099]: 2024-10-20T16:33:13.252+0200        INFO        writing logs to: /home/USERNAME/.local/share/backrest/processlogs
Okt 20 16:33:13 wopr backrest[2099]: 2024-10-20T16:33:13.268+0200        FATAL        failed to read directory        {"dir": "/home/USERNAME/.local/share/backrest/rotatinglogs", "error": "open /home/USERNAME/.local/share/backrest/rotatinglogs: no such file or directory"}
Okt 20 16:33:13 wopr systemd[1]: backrest.service: Main process exited, code=exited, status=1/FAILURE
Okt 20 16:33:13 wopr systemd[1]: backrest.service: Failed with result 'exit-code'.

```

I manually created the `/home/USERNAME/.local/share/backrest/rotatinglogs` directory with `mkdir`, and then the service started correctly and I could open the webUI.

**To Reproduce**

1. Download the latest (as of 2024-10-20) release of backrest
2. Follow installation instructions (`mkdir backrest && tar -xzvf backrest_Linux_x86_64.tar.gz -C backrest`, `cd backrest && ./install.sh`)
3. run `systemctl status backrest` to see error.

**Expected behavior**
Installation script runs correctly and I can immediately open the webUI at `localhost:9898`.

**Platform Info**

- Ubuntu 24.04, x86_64
- Backrest Version 1.6.0

**Additional context**
It seems like the install script does not create the `rotatinglogs` directory?

**Comment by garethgeorge** [comment]
Thanks for the report — this is a bugged migration. Passes on existing installs but seems like it fails on a fresh installation because of the missing directory. 

Will put out a patch release today.

**Comment by garethgeorge** [comment]
Resolved in https://github.com/garethgeorge/backrest/releases/tag/v1.6.1

**Comment by mrmorawski** [comment]
Wow that was very fast. Thank you!
