### ISSUE TITLE
Templated error messages of jobs on a locked repository results in error 

### ISSUE THREAD

**Issue by berti34** [garethgeorge/backrest#527]
**Describe the bug**
Sending an error message results in an error
error: template rendering: execute template: template: template:1:56: executing "template" at <.Plan.Id>: nil pointer evaluating *v1.Plan.Id

Logs for operation Run Hook at 22.10.2024, 11:49

[tasklog] 11:49:10.315Z	error	run hook command hook repo/FANTEC-Rest-Server/hook/0	task failed	{"error": "template rendering: execute template: template: template:1:56: executing \"template\" at <.Plan.Id>: nil pointer evaluating *v1.Plan.Id", "duration": 0.000191294}

**Platform Info**
- OS and Architecture
Arch Linux  x64, arm64, Manjaro

- Backrest Version
1.6.1

![grafik](https://github.com/user-attachments/assets/d56bd89f-b4ac-4a06-a0f6-cd8d5441b3fb)
![grafik](https://github.com/user-attachments/assets/3b4efda7-ca49-4efd-897e-2f13771cd8ab)

**Expected behavior**
Replace or Ignore the missing plan.id

**Comment by garethgeorge** [comment]
Ouch, thanks for filing this. Looks like I’m not plumbing the template vars in correctly for one of the triggers on check operations? Do you see this for any other task types?

**Comment by berti34** [comment]
No, didn't see similar errors.

**Comment by garethgeorge** [comment]
Should be fixed by https://github.com/garethgeorge/backrest/commit/0ecebf8ce40ac05e43051c2f8961829ae7bbc52d :)
