### ISSUE TITLE
SFTP repo always rejects Host verification key

### ISSUE THREAD

**Issue by bramvdzee** [garethgeorge/backrest#535]
Note: if you have a question or need support please post in the [discussions area](https://github.com/garethgeorge/backrest/discussions).

**Describe the bug**
I can't add any SFTP endpoint as a repository uri, because the container cannot verify the host ssh key.

**Screenshots**
<img width="867" alt="image" src="https://github.com/user-attachments/assets/ad669ae7-bddc-4be2-bde2-b971a3b9ba5b">

**Platform Info**

- OS and Architecture: RPI Lite 64bit
- Backrest Version 1.6.1

**Comment by bramvdzee** [comment]
For the record, I've also tried to do this with the sftp.args, without double slashes in the sftp uri, but that gave the same result.

**Comment by garethgeorge** [comment]
Another possibility is this can very often also be an issue loading the key. Try including an argument specifying the key file explicitly in the ssh command.

**Comment by mpn01** [comment]
Had similar problem. Generate an SSH key (If you haven't earlier), and in `.ssh/config` file put:
```
Host storage-1
        HostName 192.168.1.104
        User demo
        Port 2223
        IdentityFile /path/to/your/ssh_key
```
Then in **Repository URI** put:
```
sftp:storage-1:/your/path
```

**Comment by bramvdzee** [comment]
> Had similar problem. Generate an SSH key (If you haven't earlier), and in `.ssh/config` file put:
> 
> ```
> Host storage-1
>         HostName 192.168.1.104
>         User demo
>         Port 2223
>         IdentityFile /path/to/your/ssh_key
> ```
> 
> Then in **Repository URI** put:
> 
> ```
> sftp:storage-1:/your/path
> ```

I still get the same issue when using this. I've added the config to /root/.ssh/config and placed the generated SSH key in /root/.ssh/keys.
My config file looks like this:
`Host storage-1
    HostName 192.168.1.104
    User demo
    Port 2223
    IdentityFile /root/.ssh/keys/id_rsa`

I've also tried the pub file:
`Host storage-1
    HostName 192.168.1.104
    User demo
    Port 2223
    IdentityFile /root/.ssh/keys/id_rsa.pub`

This still gives the Host Key Verification Failed error.

**Comment by mpn01** [comment]
Are you using docker container to host it?

**Comment by bramvdzee** [comment]
Yes I am. I got it working with a combination of your previous post and this one:
https://github.com/garethgeorge/backrest/discussions/341

I can now make backups through SFTP. Thanks!

**Comment by mpn01** [comment]
Glad I could help a little :)
