### ISSUE TITLE
macOS install.sh error

### ISSUE THREAD

**Issue by johnmaguire** [garethgeorge/backrest#54]
Hi there! Thanks for mentioning backrest on HN. I downloaded the version for macOS and first ran backrest via Right Click > Open. This ran the program in a foreground shell, so I realized I should run `install.sh`. I opened a terminal, ran it, and got the following output:

```
❯ ./install.sh
Installing on Darwin
Installing backrest to /usr/local/bin
Password:
Creating launchd plist at /Library/LaunchAgents/com.backrest.plist
Enabling launchd plist com.backrest.plist
Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.
```

That being said, it apperas to be running successfully. Anything I should be aware of?

**Comment by garethgeorge** [comment]
Generally just that my macOS scripting skills could be improved :) .

I think that's coming from this line https://github.com/garethgeorge/backrest/blob/main/install.sh#L66 . On updates this will unload the previous version but it looks like it prints a spurious warning when it doesn't find any! 

You can definitely ignore that, Backrest is installed correctly and running!
