### ISSUE TITLE
1.6.x doesn't start on armv6 anymore

### ISSUE THREAD

**Issue by arminus** [garethgeorge/backrest#541]
**Describe the bug**
Starting with 1.6.0, backrest doesn't work on a Pi-Zero anymore, 1.5.1 works fine

2024-11-07T20:55:41.834+0100	[34mINFO[0m	writing logs to: /root/.local/share/backrest/processlogs
unexpected fault address 0xb6c75fff
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0xb6c75fff pc=0x6822c0]

**To Reproduce**
See the attached log
[out.log](https://github.com/user-attachments/files/17668733/out.log)

**Platform Info**
Raspbian GNU/Linux 9.13 (stretch)
Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux
Backrest 1.6.1 (https://github.com/garethgeorge/backrest/releases/download/v1.6.1/backrest_Linux_armv6.tar.gz)

**Comment by garethgeorge** [comment]
Stack trace is very helpful, looks like this is related to the new dependency on sqlite introduced in 1.6.0. 

I'm wondering -- does this happen first run on a fresh install? Or is it only on subsequent runs? It looks like the failure is coming from some bug in the WAL implementation that's hitting specifically on arm.

It could be related to running a few unnecessary pragmas in the init block each time I open the database / trying to change the page size here: https://github.com/garethgeorge/backrest/blob/main/internal/oplog/sqlitestore/sqlitestore.go#L67-L68 . It could also be a fundamental issue with WAL.

If you have an ability to build the binary yourself, you might try deleting those PRAGMA lines from the init block or I can provide you with a custom build to try out. I find it very suspicious that it's a WAL related crash that's triggering WHEN the database first tries to execute a query that changes mode and page size settings.

**Comment by arminus** [comment]
Trying ...

pi@raspberrypi:~/backrest/cmd/backrest $ go build .
warning: GOPATH set to GOROOT (/home/pi/go) has no effect
../../webui/webuinix.go:15:12: pattern dist: no matching files found

Does the backend have a dependency on the webui? I'm pressed for space on that Pi-Zero, not sure if I manage to build the UI as well with all the npm dependencies...

**Comment by garethgeorge** [comment]
Ah, it does but can be “faked” by simply creating that directory it’s looking for and placing an empty file in it. Sorry you’re running into that!

**Comment by arminus** [comment]
Ok, managed to compile it with your change, still crashes:

[out2.log](https://github.com/user-attachments/files/17689272/out2.log)

**Comment by garethgeorge** [comment]
Thanks for giving this a go -- confirmed with another raspberry pi user in https://github.com/garethgeorge/backrest/issues/536 that this does work on their raspberry pi device which means the crash is inconsistent.  It's reproducible for you though and raspberry pi zero is a device that I'd expect to work. Unfortunately fixing this will be tricky as I don't have test hardware. 

I'm using https://pkg.go.dev/modernc.org/sqlite which seems to be where the crash comes from. The package is pure go and is intended to be very easy to cross compile. It's also supposedly getting mature -- but it feels like we may be hitting an edge case on a less common architecture here.

The alternative is to look at switching to https://github.com/mattn/go-sqlite3 which depends on "C" sqlite , and introduce a zig toolchain to build it a bit like what this article describes: https://zig.news/kristoff/building-sqlite-with-cgo-for-every-os-4cic

Unfortunately not an easy fix, but perhaps worthwhile if I can't trust the stability of modernc sqlite. 

In terms of remaining debugging steps, if you have the bandwidth I'd be very appreciative if you could try:

 * If you have other raspberry pi zero devices, I'd be very interested to know what hardware this does / does not reproduce on. If you're willing to fiddle with this a bit, you may also try changing.
 * If you're able to fiddle with the binary a bit more, I think it would be worth trying different ways of initializing the sqlite driver. If this is an issue specific to WAL mode, it can be disabled e.g. by fiddling with the initialization flags here https://github.com/garethgeorge/backrest/blob/main/internal/oplog/sqlitestore/sqlitestore.go#L38 . Try dropping the WAL flag and ensure that it doesn't open a -wal file when accessing the database. 

Note, if you only have bandwidth to try one more thing, I'd say try deleting the OpenWAL flag on the linked line above. I'm realizing that this is probably still causing the problem I was worried about with the pragma's I had you delete.

**Comment by garethgeorge** [comment]
Thanks for digging into this and trying on another device, appreciate the time you're spending looking at it. 

It's very encouraging that it's getting further with WAL mode disabled. Looks like that worked for the sqlite database used to store logs, you're now running into the oplog which uses the same configuration. 

Like you're already thinking, try removing OpenWAL here https://github.com/garethgeorge/backrest/blob/main/internal/oplog/sqlitestore/sqlitestore.go#L38 and also the pragma you linked on https://github.com/garethgeorge/backrest/blob/main/internal/oplog/sqlitestore/sqlitestore.go#L67. I'm fairly optimistic that'll get backrest to a place where it's starting up successfully. 

If WAL is the root cause I'll likely go ahead and open an issue on  https://pkg.go.dev/modernc.org/sqlite as well. If the fixes work and you can link me your fork, I'll also make sure I include a patch for this going forward with the next release.

**Comment by arminus** [comment]
I now removed both pragmans in L67-68 as well as the ` | sqlite.OpenWAL` in L38, no improvement:
[out3.log](https://github.com/user-attachments/files/17728211/out3.log)

**Comment by garethgeorge** [comment]
Hey, would you mind uploading your fork so I can inspect the changes and possibly PR any additional fixes that are needed to get this working in your fork? It looks like the stack trace is still coming from executing the script that contains the pragma `PRAGMA journal_mode=WAL;` block which is confusing / it looks like the DB is still trying to use WAL mode.

I've gone ahead and opened an issue with your stack trace on the underlying database driver: https://gitlab.com/cznic/sqlite/-/issues/197

**Comment by arminus** [comment]
Here you go: https://github.com/garethgeorge/backrest/compare/main...arminus:backrest:main

**Comment by garethgeorge** [comment]
Thanks for uploading that -- just PR'd another fix https://github.com/arminus/backrest/compare/main...garethgeorge:backrest:patch-1 based on some feedback I got from the sqlite driver developer in https://gitlab.com/cznic/sqlite/-/issues/197 .

I'm fairly optimistic that a libc version mismatch would explain this.

**Comment by arminus** [comment]
The downgrade fixes the problem, see https://github.com/garethgeorge/backrest/pull/559 for the full PR (WAL flag and pragma removal rollback)
