### ISSUE TITLE
Plan Retention Policy removing the wrong snapshots

### ISSUE THREAD

**Issue by dikano** [garethgeorge/backrest#556]
**Describe the bug**
The retention Policy is removing the Snapshot from yesterday on each day

**To Reproduce**

1. setup daily backups
2. setup Retention Policy By Time Period weekly X
4. The Automated Forget Function after a Snapshot is taken will remove the Snapshot from the Day befor

**Expected behavior**
when setting the Retention Policy by Time Period to 4 Weeks and running Daily Backups
it is expected that the Snapshots older than 4 Weeks will be removed

**Screenshots**
![Screenshot 2024-11-14 064207](https://github.com/user-attachments/assets/a59ca322-7993-4571-92ca-70bebcf32eae)
![Screenshot 2024-11-15 004126](https://github.com/user-attachments/assets/fc6116ce-d34e-45fb-a0e9-db2edecb7e92)
![Screenshot 2024-11-15 004356](https://github.com/user-attachments/assets/13a2d804-3254-4fc2-af35-8b369b1ab0a7)

**Platform Info**

- Docker
- Backrest Version 1.6.1

**Additional context**
this is the JSON from the Plan in the Screenshots:
{
  "id": "Docker_Pi-Backup",
  "repo": "Docker_Backup",
  "paths": [
    "/userdata/Pi_Backup"
  ],
  "excludes": [],
  "iexcludes": [],
  "schedule": {
    "clock": "CLOCK_LOCAL",
    "cron": "10 19 * * *"
  },
  "retention": {
    "policyTimeBucketed": {
      "yearly": 0,
      "monthly": 0,
      "weekly": 4,
      "daily": 0,
      "hourly": 0
    }
  }
}

this is a Json from another Plan that is also deleting the Snapshots from yesterday:

{
  "id": "Docker_VM-Backup",
  "repo": "Docker_Backup",
  "paths": [
    "/userdata"
  ],
  "excludes": [
    "/userdata/Pi_Backup"
  ],
  "iexcludes": [],
  "schedule": {
    "clock": "CLOCK_LOCAL",
    "cron": "45 23 * * *"
  },
  "retention": {
    "policyTimeBucketed": {
      "yearly": 0,
      "monthly": 0,
      "weekly": 2,
      "daily": 0,
      "hourly": 0
    }
  }
}

**Comment by garethgeorge** [comment]
Hey -- this is a misunderstanding re: how retentions work. https://restic.readthedocs.io/en/latest/060_forget.html covers this in a lot of detail but tl;dr is that a retention of 4 weeks is expected to keep 1 snapshot per week for 4 weeks. 

Backrest doesn't support a "keep the last 4 weeks" of snapshots option at the moment. 

For the behavior you're wanting you could probably get very close to the behavior you want by setting daily to "30" which will keep one snapshot per day for the last 30 days -- which is about 4 weeks if you're backing up daily.

**Comment by dikano** [comment]
setting this to number of days fixed the issue.
i thought the caption ment something else
