### ISSUE TITLE
healthchecks integration should allow for self-hosted healthchecks instances

### ISSUE THREAD

**Issue by lakemike** [garethgeorge/backrest#561]
I am using a self-hosted healthchecks instance.
It is called using a script:
`/usr/bin/curl -fsS --retry 3 https://healthchecks.mydomain.tld/ping/7e4234a...10fad`
This works actually very well. but since healthchecks.io is now supported, I would encourage to support also self-hosted instances of healthckecks.
KR

**Comment by garethgeorge** [comment]
What happens when you use the existing healthchecks.io hook is used with your self hosted instance? It should allow an arbitrary URL to be provided.

**Comment by lakemike** [comment]
My apologies! I tried again and it works very well. I must have made a mistake typing the URL the first time.
