### ISSUE TITLE
Reading password from a password command

### ISSUE THREAD

**Issue by kzshantonu** [garethgeorge/backrest#57]
Hi! Coming from the forums.

I believe the best way to implement this would be to have a "password command" field next to the password field where one could input the command. Similar to restic's own RESTIC_PASSWORD_COMMAND env. Backrest will then run that command everytime it needs the password.

For the docker container, an env variable could be used.

This way multiple repositories could have different commands/env variables.

**Comment by garethgeorge** [comment]
SGTM, makes sense to reuse restic's support for RESTIC_PASSWORD_COMMAND for this actually & we can leave running the password command to restic's existing logic for maximum compatibility (backrest will never execute it / need access to your password itself).

It looks like restic actually lets the RESTIC_PASSWORD_COMMAND env var take precedence over the RESTIC_PASSWORD env var when it is provided. (see https://github.com/restic/restic/blob/446167ae802dfd5b0730417e8f5bffb49b7fe584/cmd/restic/global.go#L296-L308).

As a workaround, try setting the password to some garbage value to satisfy that it is a required field. In the extra options for the repo you should be able to provide env var overrides which are typically used to provide access keys (e.g. for S3, B2, ...). In the extra env vars try specifying `RESTIC_PASSWORD_COMMAND=(your command)`. Backrest will forward that and the garbage password to restic as env vars, but I believe the value from RESTIC_PASSWORD_COMMAND will be the one that gets used. 

If that works, I'll need to give some thought to how this should work in the UI for repo creation. Depending on how popular of a feature it is I can see two options

 * Support it as an alternative to providing a password (e.g. explicitly make the credential type togglable)
 * Support it as a special env variable and disable the password input when it is provided. To make this more explicit I could actually display the password in the env vars section e.g. reduce the password input to a special case of adding an env var `RESTIC_PASSWORD=foo`.

The end validation logic would then just be to require that one of either: RESTIC_PASSWORD or RESTIC_PASSWORD_COMMAND or RESTIC_PASSWORD_FILE is provided in the env vars section.

**Comment by garethgeorge** [comment]
Hmm, this is an interesting point wrt the environment and setting global options. It sounds like a good unix friendly way to do this might be for me to remove the filtering that backrest applies to the env variables it sets on the restic process (e.g. to just pass through all env variables from the parent process). Originally I didn't do this b/c it seemed like bad security practice, but realistically the only binaries backrest forks are restic, rclone, and sometimes ssh for sftp clients. These are all highly trusted. Would that work for your use case?

w.r.t. forget this happens here https://github.com/garethgeorge/backrest/blob/main/internal/orchestrator/repo.go#L109-L137 and is filtered to the specific plan it applies to so snapshots that aren't tagged with a plan ID managed by restic won't be touched :)

**Comment by kzshantonu** [comment]
I believe the best way to handle env variables is to simply let the user map any existing host variable into a restic variable. Example: $LALALA on host / systemd service file / docker env maps to $AWS_ACCESS_KEY_ID (or any other variable) inside  the container / service

**Comment by garethgeorge** [comment]
In my lastest PR I went ahead and included some changes to relax password validation https://github.com/garethgeorge/backrest/blob/5323b9ffc065bc3b28171575cdccc4358b69750b/webui/src/views/AddRepoModal.tsx#L478-L483 , RESTIC_PASSWORD_COMMAND and RESTIC_PASSWORD_FILE are now accepted in the env vars as an alternative to providing a password. That'll be available in the prebuilt binaries with the next release.


w.r.t. the remaining question of how to nicely map external env vars into the env backrest uses for restic

 I like your proposed solution quite a bit. The easy way to implement this would be to interpret any env var value starting with `$` e.g. `FOO=$FOO_EXTERN` as an environment variable and to load it's value using os.Getenv . Prefixing `$$` would be a decent escape sequence. I'll get a PR out for this to include it in the next release.

Users might inadvertently hit this in some places which would be pretty confusing. Especially with the RESTIC_PASSWORD env var where $ is a pretty common symbol to inject. I think a good error message is probably sufficient notice for that though. If an env var is defined but not set an error on command will print e.g.

```
attempting to load `$VAR` but it is not defined. Did you forget to set this variable? Otherwise escape this reference as `$$VAR`
```

**Comment by kzshantonu** [comment]
Hi was this implemented?

**Comment by rdiaz02** [comment]
@kzshantonu : are you able to pass variables that you'd `export AWS_ACCESS_KEY_ID=$(get_secret)` when invoking `restic` direclty? I've tried setting the EnvVars fields as `THE_VARIABLE=$THE_VARIABLE` and `THE_VARIABLE=$THE_VARIABLE_EXTERN` or `THE_VARIABLE=(get_secret blablaba)` and several other incantations, without luck.

**Comment by kzshantonu** [comment]
@rdiaz02 try building the docker image with the secret manager binary at PATH. Or pass the secret from the docker host to the container at runtime. If you do it this way, the correct way is `X_VAR=something` (host side) passed as `VAR=${X_VAR}` (docker side), that'll give you `VAR=something` in the container.

**Comment by rdiaz02** [comment]
Thanks, @kzshantonu ; however, I am not using Docker, which (not using Docker, I mean) I would have thought should have been easier. But I haven't been able to get passwords/IDs using `secret-tool` (which I can do just fine when I call restic directly).
