### ISSUE TITLE
Windows systray doesn't honor BACKREST_PORT variable

### ISSUE THREAD

**Issue by homandr** [garethgeorge/backrest#579]
**Describe the bug**
Windows system tray icon has a menu option "Open WebUI". When BACKREST_PORT variable is set to use a different port, this menu link still points to 9898. The actual process listens on the defined port correctly.

It appears 9898 is hard-coded without checking the environment variable.
```				
if err := openBrowser("http://localhost:9898"); err != nil {
	reportError(err)
}
```

**To Reproduce**

1. Set BACKREST_PORT environment variable to 127.0.0.1:9890, for example.
2. Quit and restart Backrest.
3. Click on Backrest systray icon, then Open WebUI.
4. See the issue.

**Platform Info**
- Windows
- Backrest Version 1.6.1

**Additional context**
At the moment using a custom port results in broken WebUI shortcuts. PR #578 fixes this issue.

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/commit/c810d27375c39a9938ad4bde433dfe5997d56bfa
