### ISSUE TITLE
rclone support with macOS install script

### ISSUE THREAD

**Issue by garethgeorge** [garethgeorge/backrest#59]
rclone is ostensibly supported by repo URI's such as `rclone:name:path` but users hit an error when backrest tries to fork the rclone executable (e.g. it can not be found on the path).

Let's try to figure out why the environment isn't properly being propagated such that the executable isn't found.

**Comment by garethgeorge** [comment]
looks like rclone works on Linux but is broken by the install script on MacOS. launchd doesn't propagate any environment variables (e.g. path) to the spawned backrest process meaning that rclone can't be found in many cases.

One way to fix this might be updating the installer to add a copy of the PATH environment variable to the generated launchd plist or perhaps generating a value of the PATH env variable that includes the directories that backrest cares about. This would be:

`which ssh`
`which rclone`

**Comment by alyraecap** [comment]
I barely even know how to use the terminal, but in case any other newbs need this before it's fixed, if rclone is saved in the default location usr/local/bin (unhide hidden folders cmd + shift + . ), then add the PATH environment variable to the launchagents plist created by the install script (Library/LaunchAgents/com.backrest.plist). Insert this code within the <dict> hierarchy:
    <key>EnvironmentVariables</key>
    <dict>
           <key>PATH</key>
           <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>  

Backrest will also function without this error if you just ran the backrest executable in usr/local/bin.

**Comment by stefanodecillis** [comment]
Tried what @alyraecap suggested but it didn't resolve.  The error I get is:

`Operation failed: [unknown] failed to init repo: init failed: command "/Users/user/.local/share/backrest/restic-0.16.4 init --json -o sftp.args=-oBatchMode=yes" failed: exit status 1 Process STDOUT: Fatal: create repository at rclone:host:backrest-mac/backrest-mac failed: exec: "rclone": executable file not found in $PATH`

I'm using a fresh installation of backrest on my mac and the repo is a shared folder from my synology

**Comment by alyraecap** [comment]
@stefanodecillis Have you restarted your Mac? Or restart backrest by going to system settings - General -> Login Items -> backrest -> turn it off and on.

Does your plist look like this?
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>EnvironmentVariables</key>
    <dict>
           <key>PATH</key>
           <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>           
    <key>Label</key>
    <string>com.backrest</string>
    <key>ProgramArguments</key>
    <array>
    <string>/usr/local/bin/backrest</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/backrest.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/backrest.log</string>
</dict>
</plist>
`

**Comment by garethgeorge** [comment]
Fixed in https://github.com/garethgeorge/backrest/commit/8cf43f28921ef7182f1c655fa82470e74698d3ce
