### ISSUE TITLE
Backup to multiple repos in the same plan

### ISSUE THREAD

**Issue by jeremy-lockwood** [garethgeorge/backrest#596]
**Is your feature request related to a problem? Please describe.**
I keep a local and cloud repo for my backups. Right now, I have to maintain duplicate plans for each repo.

**Describe the solution you'd like**
I'd like to configure each of my plans to backup to both of my repos.

**Comment by garethgeorge** [comment]
This is a duplicate of https://github.com/garethgeorge/backrest/issues/508 , but you're definitely not alone in thinking that this is a place where backrest can be improved. Please feel free to +1 or add a comment over there.
