### ISSUE TITLE
Update Docker Hub instructions to reflect latest shown on GitHub

### ISSUE THREAD

**Issue by rhinot** [garethgeorge/backrest#599]
### Issue
[Instructions on Docker Hub for the backrest Compose file](https://hub.docker.com/r/garethgeorge/backrest) omit the (optional) repo location and timezone environmental params listed on [the main github page](https://github.com/garethgeorge/backrest?tab=readme-ov-file#running-with-docker-compose).

The omission of this instruction prohibits the ability for someone to backup to a NAS or other local destination.

### Request
Update Docker Hub Compose to the example listed on GitHub. 
(I'd do a pull request if Docker Hub allowed it. :)

**Comment by garethgeorge** [comment]
Went ahead and updated this to match the readme example :) 

https://hub.docker.com/repository/docker/garethgeorge/backrest/general
