### ISSUE TITLE
provide a static link to download the latest release

### ISSUE THREAD

**Issue by umrath** [garethgeorge/backrest#614]
Currently, one has to manually get the right url for the latest package to update a server.
E.g.: https://github.com/garethgeorge/backrest/releases/download/v1.6.2/backrest_Linux_arm64.tar.gz
To be able to automate updates, it would be great if there would be static urls that always point to the latest release.
E.g.: https://github.com/garethgeorge/backrest/releases/download/latest/backrest_Linux_arm64.tar.gz

**Comment by garethgeorge** [comment]
Hey, this already exists https://github.com/garethgeorge/backrest/releases/download/latest/backrest_Linux_arm64.tar.gz

**Comment by umrath** [comment]
I tried this before filing this proposal.
All I got was a "Not Found".

**Comment by garethgeorge** [comment]
Oops -- sorry accidentally copied your link instead of mine! Correct one should be https://github.com/garethgeorge/backrest/releases/latest/download/backrest_Linux_arm64.tar.gz

**Comment by umrath** [comment]
Oh, cool!
(Maybe that should be the link in the description.)
