### ISSUE TITLE
documentation: publish a wiki or expanded docs site

### ISSUE THREAD

**Issue by garethgeorge** [garethgeorge/backrest#63]
Investigate good options for generating a documentation site to elaborate in more detailes on the capability of backrest.

Areas to expand in particular are:

 * Repo configuration
 * Scheduling options and health tasks
 * Hooks and hook templates + working examples (hooks are Golang templates, this is worth an article)

**Comment by modem** [comment]
I would add to this list of documentation the following items:

- Description of the environment variables
- Description of the flags
 
![image](https://github.com/garethgeorge/backrest/assets/62859/08e73651-f022-4da9-9e52-cc602607042f)

**Comment by bagelwoof** [comment]
I would like to add one more thing to this list of documentation improvements: Upgrading!

Docker upgrades seem pretty obvious, but if the user has installed binaries, there's no explicitly stated safe way to upgrade to the latest release in the existing docs.

**Comment by garethgeorge** [comment]
This is a great point! At the moment it's intended to always be safe to rerun the `install.sh` script which will upgrade versions (you may have already found this!). I'll add it to the docs.
