### ISSUE TITLE
Command hook fails in docker image

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#64]
I added a hook to one of my backups with the following configuration:
![image](https://github.com/garethgeorge/backrest/assets/62859/235e0315-bcb2-443e-8f87-719e672fe339)

but it seems this hook is generating an error when executed:
![image](https://github.com/garethgeorge/backrest/assets/62859/34ecaad2-8f7a-4faa-ab7c-c0b5de6fbc7b)

This is the log I see in the frontend:
```
------- script -------
#! sh
echo 'Task: "backup for plan "Series"" at 2024-02-06T08:02:08Z
Event: snapshot end
Repo: Series 
Plan: Series 
Snapshot: 0e734343be9e288cafeaec9de515d473f709fb59babb6de0b30fdd6ead50c066
Overview:
- Data added: 1.001 GB
- Total files processed: 6610
- Total bytes processed: 1.001 TB

Backup Statistics:
- Files new: 4
- Files changed: 6
- Files unmodified: 6600
- Dirs new: 0
- Dirs changed: 9
- Dirs unmodified: 227
- Data blobs: 2026
- Tree blobs: 10
- Total duration: 115.67551034s

'
------- output -------
Error: exec: "sh": executable file not found in $PATH
```

I'm using the latest version 0.11.0, running on Docker.
I also can't open a shell connection to the docker container, so the shell binary is probably missing.

**Comment by modem** [comment]
Thanks for pursuing this, I'm running Backrest (as all my other containers) from a NAS, so a direct installation is not a solution that would work for me. also don't have the skills to build a custom image to add the cli tools.

In addition to the cli tools you mentioned, it might also be useful to have the following general purpose tools:
- /bin/ls
- /bin/cat
- /bin/ps
- /bin/grep
- /bin/date
- /bin/echo
- /bin/more
- /bin/rmdir
- /bin/chattr
- /bin/dd
- /bin/egrep
- /bin/mount
- /bin/sleep
- /bin/df
- /bin/sed
- /bin/touch
- /bin/chmod
- /bin/dmesg
- /bin/mkdir
- /bin/ping
- /bin/chown
- /bin/mv
- /bin/ping6
- /bin/umount
- /bin/cp
- /bin/kill
- /bin/rm

I got a list from another container and copied the ones that may seem relevant/useful.

**Comment by modem** [comment]
Regarding the command hook, if you can know you are running on docker, maybe you can hide that hook option. I don't know if it is possible.

**Comment by modem** [comment]
Thanks, this is close, I had to do some modifications. It seems docker does not allow having inline comments, so moved the comments to it's own line.
I also had an issue installing curl, it depends libcurl3 and I was getting an failure resolving archive.ubuntu.com. I added apt update command and it worked, but I'm not sure this was the issue...

A working docker file looks like this:
```
FROM garethgeorge/backrest:latest AS backrest
FROM ubuntu:14.04 AS ubuntu
# ensure that tmp dir exists
COPY --from=backrest /tmp /tmp
# ensure that SSL certs are available
COPY --from=backrest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=backrest /backrest /backrest
RUN apt update
RUN apt install -y curl bash
# and any other binaries you'd like!
ENTRYPOINT ["/backrest"]
```
Comparing your backrest binary size with the one I've built locally, mine is bigger, 19MB vs 16MB, so there's definitely something work with my build environment.

**Comment by garethgeorge** [comment]
If you're building the webui sources as well, one of the steps in the goreleaser build is to gzip them (which can accout for a significant portion of the binary size).

**Comment by garethgeorge** [comment]
Added a small blurb on this to the wiki https://github.com/garethgeorge/backrest/wiki/Hooks-and-Notifications#hooks-in-docker
