### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#66]
Hi, 

I would like to propose 3 UI improvements:

1. Add, somewhere in the frontend,  a link to the Backrest Git repository
2. Increase the text size of the backup executed additional details (I don't know exactly what to call to this, so check the image below)
![image](https://github.com/garethgeorge/backrest/assets/62859/03a84f87-7b44-4483-8116-c3f3ef29dd7c)
I find this text very difficult to read, I often have to use the browser zoom to read it.
3. There is now a logout link on the top right corner (after the host), but it's written in black with a grey background color, so it's not readable
![image](https://github.com/garethgeorge/backrest/assets/62859/0365ccb9-90e9-4da5-a952-03cb4bb566fe)

**Comment by garethgeorge** [comment]
Implemented 1 on the "Getting Started" page in the latest release and fixed 3 (logout link color).

**Comment by garethgeorge** [comment]
Going ahead and resolving this for now, remaining scaling improvements are tracked in https://github.com/garethgeorge/backrest/issues/168
