### ISSUE TITLE
Error removing hook

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#67]
Hello,

I have these 2 hooks:
![image](https://github.com/garethgeorge/backrest/assets/62859/24967d18-0c92-41a3-bec8-31d257c23f48)
If I delete Hook 0, Hook 1 will become Hook 0 and will loose it's configuration, becoming this:
![image](https://github.com/garethgeorge/backrest/assets/62859/cd947b13-fd5a-42ad-81e5-7ef4fbfd5f6f)

It is then not possible to save the configuration due to missing configuration:
![image](https://github.com/garethgeorge/backrest/assets/62859/86ea7a2c-f9e4-4f03-a702-e2a8bd0d4fdf)

Removing all Hooks and adding a new one does not work, unless we save the configuration after removing the existing hooks.

It happens in the plans and in the repositories configuration.

**Comment by garethgeorge** [comment]
Thanks for reporting this (and the other issues!) it's great to have the feedback -- and the screenshots help hugely.  I'll aim to get a patch bug fix release out this weekend.

**Comment by garethgeorge** [comment]
Improved the handling of form data in the last release, this should be fixed! Thanks for reporting it.
