### ISSUE TITLE
Error building docker container

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#70]
Hi, 

I tried to build a new docker image from the git code. Everything runs well, the image is created but when I create a container from that image it does not run, instead I get the error:
`exec /backrest: no such file or directory`

I'm using the following commands to build the image and container:
```
docker build . -t testbackrest:v1 --no-cache
```
```
docker container run -it --name=atest -p 9899:9898 -e BACKREST_DATA=/data -e BACKREST_PORT=9898 -e XDG_CACHE_HOME=/cache -v $(pwd)/.backrest/config:/.config/backrest -v $(pwd)/.backrest/data:/data -v $(pwd)/.backrest/cache:/cache  testbackrest:v1
```

If I run the built backrest executable, it runs well outside the container.

I then modified the Dockerfile to add a shell, and modified the entrypoint to launch the sheet instead of backrest. I looks as follows:
```
FROM busybox:1.35.0-uclibc as busybox

FROM golang:alpine as gobuild
RUN mkdir /tmp-orig
COPY backrest /backrest

FROM scratch
COPY --from=gobuild /tmp-orig /tmp
COPY --from=gobuild /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Now copy the static shell into base image.
COPY --from=busybox /bin/sh /bin/sh
COPY --from=busybox /bin/mkdir /bin/mkdir
COPY --from=busybox /bin/cat /bin/cat
COPY --from=busybox /bin/ls /bin/ls

ENTRYPOINT ["/bin/sh"]
#ENTRYPOINT ["/backrest"]
COPY backrest /backrest
```

Building the container from the new image now launches the shell, from where I can see the backrest executable, but launching it still throws the same error.
```
/ # ls -lsa
total 19124
     4 drwxr-xr-x    1 0        0             4096 Feb  7 18:30 .
     4 drwxr-xr-x    1 0        0             4096 Feb  7 18:30 ..
     4 -rw-------    1 0        0                8 Feb  7 18:30 .ash_history
     4 drwxr-xr-x    3 0        0             4096 Feb  7 18:30 .config
     0 -rwxr-xr-x    1 0        0                0 Feb  7 18:30 .dockerenv
 19088 -rwxr-xr-x    1 0        0         19542680 Feb  7 16:50 backrest
     4 drwxr-xr-x    1 0        0             4096 Feb  7 17:18 bin
     4 drwxr-xr-x    2 0        0             4096 Feb  7 16:53 cache
     4 drwxr-xr-x    2 0        0             4096 Feb  7 16:53 data
     0 drwxr-xr-x    5 0        0              340 Feb  7 18:30 dev
     4 drwxr-xr-x    1 0        0             4096 Feb  7 18:30 etc
     0 dr-xr-xr-x  224 0        0                0 Feb  7 18:30 proc
     0 dr-xr-xr-x   12 0        0                0 Feb  7 18:30 sys
     4 drwxr-xr-x    2 0        0             4096 Feb  7 17:18 tmp
/ # ./backrest
/bin/sh: ./backrest: not found

```
Am I doing something wrong? Why is backrest not working inside the container, but works outside?

The only problem I had when creating the development environment was running this command:
```
go install github.com/GeertJohan/go.rice@latest
```

`package github.com/GeertJohan/go.rice is not a main package`

Tried to remove the `@latest` part from the command, but it does not seem to do anything, but there's no error as well.

I get the error `package github.com/GeertJohan/go.rice is not a main package`

I then installed rice from the package manager:
```
sudo apt install -y golang-rice
```

At least I learned how to add the shell command and external cli tools.

**Comment by garethgeorge** [comment]
Just left a comment on your other issue https://github.com/garethgeorge/backrest/issues/64 wrt an approach using a multistep build based off of the `garethgeorge/backrest` image, but it's great to see you're having some success wrt building from source.

It's not obvious to me why this build setup would be failing but it looks to largely be on the right track.

**Comment by modem** [comment]
Added comments to #64 .

**Comment by garethgeorge** [comment]
Thanks! Closing this for the other issue.
