### ISSUE TITLE
Possible issue in Docker with hostname

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#73]
Hi,

I've added the `hostname` to my docker compose file, but at the top of backrest interface, the hostname shows some ID.
![image](https://github.com/garethgeorge/backrest/assets/62859/7c0b2b6c-43a1-4a1c-9731-68eb9692c17d)

I've looked at the container details, and the hostname is correctly showing there:
![image](https://github.com/garethgeorge/backrest/assets/62859/3bf197fd-c805-48f1-a41b-5f6c333e5dd6)

Then I realized the hostname was being pulled from the config.json file:
![image](https://github.com/garethgeorge/backrest/assets/62859/6fe19848-73f6-49d4-bfa3-662343495243)

This was probably the ID from the 1st time I've created the backrest container...

Is this the expected behavior? For me I would expect the hostname to be dynamic, either by reading the container hostname when opening the user interface, or updating the config file on every time the containter is started.

**Comment by modem** [comment]
I tried to delete the host from the config file and restarting the container, but then no host is visible in the UI. Seems the host config is only created on the 1st run.
Changing the host on the config file requires the container to be restarted for the change to be visible on the interface.
So far, the only place to change the host name is the config file.

**Comment by garethgeorge** [comment]
Hostname handling is mostly cosmetic at the moment. I'll leave this open to polish this up in future work but it's pretty low priority at the moment. I'm largely expecting it to be a useful feature for people running many deployments of backrest to tell at a glance which machine they've connected to.

**Comment by pdfrg** [comment]
First, I love backrest.  I tried multiple other server-client backup programs and had limited success.  Backrest/Restic 'just works.'  Thank you!!!

In particular, it works great even when the network conditions aren't -- e.g. one spoke on spotty Wi-Fi, one on ethernet over powerline.  Other programs timed out and/or failed in other ways. 

So, I'm one of the people running multiple deployments.  I had the same experience as OP.  Agree it's no urgent issue.  I have a hub-spoke setup with linux native install on the spokes.  Works perfectly there.  On my docker install, the UI says "backrest" no matter what I change the HOSTNAME var to in the docker compose file.

**Comment by garethgeorge** [comment]
Hey, backrest populates the hostname into your config.json on first run. It's on the todo list to make it configurable in the UI but hasn't been high priority yet! 

To update it, just edit the `host` property in your config and then restart backrest.

**Comment by garethgeorge** [comment]
Adding an option to configure host name in the UI in the next release (exposed in settings).
