### ISSUE TITLE
Support restic check

### ISSUE THREAD

**Issue by SiddharthManthan** [garethgeorge/backrest#75]
Add support to check the repo. 

The following checks are available :
- Repo Integrity
- Packfile Integrity
    - Full check `--read-data`
    - Specified subset of repo `--read-data-subset=n/t`
    - Random subset of repo
        - Random subset by percent `--read-data-subset=x%`
        - Random subset by size `--read-data-subset=nS`

The existing plans can be classified into backup plan and check plan. Check plan can be scheduled similar to backup plans.

This could be considered a high priority issue since repo can be corrupted due to updates or existing undiscovered bugs (eg : recent compression bug). If repo corruption is known soon, it can rectified.

**Comment by MarvinJWendt** [comment]
+1 from me.

Personally, I would like a <kbd>Check now</kbd> button, next to the <kbd>Backup now</kbd> one.

Also some repo configuration that would make sense:

- **Check schedule** (CRON like schedule for checking the repo automatically)
- **Scheduled check percentage** (applied to each scheduled check)
- **Manuel check percentage** (applied to each manual check, e.g.: click on <kbd>Check now</kbd>)

Thinking about it, maybe it would make sense to have a dropdown button next to <kbd>Backup now</kbd> with "More actions".

![image](https://github.com/garethgeorge/backrest/assets/31022056/68ab4212-a4aa-4d6c-b5ee-82b9ef69995f)

Maybe it would also make sense to move <kbd>Unlock repo</kbd> and <kbd>Prune now</kbd> there.
That way, we could also have a button <kbd>Full check now</kbd> without bloating the UI.

**Comment by garethgeorge** [comment]
Hey, thanks all for the interest. Just updating here to say that this is high on the todo list. I like the idea of a "check now" button at the very least and will aim to make automatic checks configurable. I think the right time to run them is probably right after a prune operation.

**Comment by lakemike** [comment]
Coincidentally, I just had issues with one my repositories.
- This was identified by an automated "prune" run.
- Running "check" at commandn line confirmed there is an issue.
- A combination of "repair index" and "repair snapshots --forget" was effective in fixing it.

Just looking at this case, these enhancements could be very useful
- "check now" button
- option to run checks in a scheduled fashion or, alternatively, always after prune
- "more actions" button, e.g. "repair index", "repair packs", "repair snapshots"

**Comment by garethgeorge** [comment]
Initial implementation in PR https://github.com/garethgeorge/backrest/pull/303 , a preview release with check support can be downloaded from https://github.com/garethgeorge/backrest/actions/runs/9260231928 .

**Comment by garethgeorge** [comment]
Available in version 1.1.0
