### ISSUE TITLE
How to delete backups from old plan?

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#76]
During my tests, I created 2 plans to backup to the same repository. I then deleted one of the plans, but the repository still shows the old backup.
Is there a way to remove that data without deleting the repository? I see no option for this in the interface...
![image](https://github.com/garethgeorge/backrest/assets/62859/11b55e14-cb45-430a-8d44-3f9854a8f3a7)

**Comment by garethgeorge** [comment]
You're right that backrest will retain these forever so long as the snapshots are retained in your repo (and with the plan deleted backrest is no longer managing forgets / prunes for snapshots created by that plan).

If you go ahead and delete those snapshots with the restic cli, backrest will pick this up after the next backup and will garbage collect the associated UI entries.

**Comment by garethgeorge** [comment]
use `restic forget --keep-last 1 --tag plan:yourplanID` to forget all but the most recent snapshot in that set, then find the snapshot ID of the last remaining snapshot and run `restic forget <snapshotID>` to finish cleanup.

**Comment by modem** [comment]
I can't run this on the official backrest container... We need shell support.

**Comment by garethgeorge** [comment]
https://github.com/garethgeorge/backrest/pull/72 adds a button for manually forgetting individual snapshots.
