### ISSUE TITLE
Allow modifying more settings from config file or command line parameters, settings which are currently set via environment variables

### ISSUE THREAD

**Issue by SiddharthManthan** [garethgeorge/backrest#77]
Right now, we can modify `BACKREST_PORT`, `BACKREST_DATA`, `BACKREST_RESTIC_COMMAND`, etc only through environment variables. Allow modifying them through commandline parameters or config file for easier install/usage. 

Currently the only way is to use a script or terminal to modify these settings, atleast in windows.

**Comment by garethgeorge** [comment]
SGTM, I'll add flags in the next release: 

 * `--port` will take precedence over `BACKREST_PORT`
 * `--data-dir` will take precedence over `BACKREST_DATA`
 * `--restic-cmd` will take precedence over `BACKREST_RESTIC_COMMAND`
 * `--config` will take precedence over `BACKREST_CONFIG`

**Comment by garethgeorge** [comment]
quick update -- I'm behind on adding this but it's still planned, bumping to next patch release.

**Comment by garethgeorge** [comment]
Added in https://github.com/garethgeorge/backrest/commit/41ddc8e1a9d5501a92498c8cf3c72625bd181f8a
