### ISSUE TITLE
Hooks to ping rest api GET and POST requests (eg : for cron monitoring services like healthchecks.io)

### ISSUE THREAD

**Issue by SiddharthManthan** [garethgeorge/backrest#78]
Cron monitoring services like healthchecks.io can be pinged using GET or POST requests. They can also store log information upto 100KB. 

Reference : https://healthchecks.io/docs/http_api/

Considering adding support for get and post request using hooks.

The difference between this and existing hooks is cron monitoring services can detect if backrest is not running. They need to ping regularly. If they are not pinged then they determine backrest is down.

Current webhooks will not notify if backrest itself is not running.

Adding GET and POST requests will allow many other services to be used.

**Comment by garethgeorge** [comment]
I'd recommend setting up liveness based on the start or successful end of a backup operation. Backrest has quite good test coverage, but generally backrest being running in the background shouldn't be enough to be sure your data is getting backed up. Misconfiguration, network issues, etc could prevent backups completing successfully. You should only rely on a successfully completed backup as an indicator of liveness.

If you do really want liveness for backrest, I wonder if this would be a good role for a wrapper script (e.g. a shell or PowerShell script that forks backrest and pings in the background so long as it's running). I'd be happy to document one in the wiki if there's one that meets your needs.

**Comment by garethgeorge** [comment]
Went ahead and bundled curl with the latest 'alpine' image -- I think this is a pretty good way of supporting arbitrary web api hooks. Does this work for the use case you had in mind?

**Comment by garethgeorge** [comment]
Great! Going ahead and marking this is closed with that work around in mind :)
