### ISSUE TITLE
question re: configuring S3 repositories

### ISSUE THREAD

**Issue by jcunix** [garethgeorge/backrest#82]
Hi,

Sorry for the dumb question,  but completely new to restic / backrest.  HI have an S3 bucket repo setup, and a plan.  But how do you configure a client to use backrest to push backups?  Sorry if this is a completely stupid question.

**Comment by garethgeorge** [comment]
Setting up S3 is done with env variables, you'll want to provide a URI e.g. s3:bucket/path and two environment variables:

 * AWS_ACCESS_KEY_ID=<accesss key id>
 * AWS_SECRET_ACCESS_KEY=<access key value>

For what it's worth, Amazon's pricing for storage is _very_ high. Especially download bandwidth for restore. Options I test with for backrest are 

 * minio (self hosted s3 compatible storage) 
 * b2 (cloud storage) https://www.backblaze.com/
