### ISSUE TITLE
SIdebar doesn't update status

### ISSUE THREAD

**Issue by dhilgarth** [garethgeorge/backrest#84]
The sidebar doesn't update its status when one backup finishes and another starts:

![image](https://github.com/garethgeorge/backrest/assets/1180105/b4959184-e8e9-419a-840f-bb95ca9d19c2)

As you can see, based on the sidebar, `companies` is the currently running backup. But it already finished and the currently active backup is `apps`, as correctly indicated by the header.

**Comment by garethgeorge** [comment]
Should be improved a bit by https://github.com/garethgeorge/backrest/commit/3d192fd59d98c242ed583d00eeec37e68a4a2ff5
