### ISSUE TITLE
Improve path selection on Windows

### ISSUE THREAD

**Issue by dhilgarth** [garethgeorge/backrest#85]
On Windows, the path selection is a bit strange as it displays both slash and backslash:

![2024-02-14_12-42-22](https://github.com/garethgeorge/backrest/assets/1180105/bb0d90eb-c368-4ee6-9e4c-77358f176c43)

**Comment by dhilgarth** [comment]
On my development machine where I've been implementing the PRs, I'm not seeing this.   
The difference: I created a new npm script which I used to start the UI:
```
"start-windows": "set UI_OS=windows & parcel server src/index.html"
```

Starting the UI with the existing `start` script resurfaces this error.

Only conclusion for me: The windows build on your release page didn't actually use the `build-windows` script to build the UI.

**Comment by garethgeorge** [comment]
good catch, updated the .goreleaser config for https://github.com/garethgeorge/backrest/pull/95 which should now build correctly for windows

**Comment by dhilgarth** [comment]
Did you actually test this new release on Windows? I'm now getting 404 when navigating to the web UI and see this in the log:

```
2024-02-15T09:36:18.001+0100	[33mWARN[0m	Error loading static assets, not serving UI: could not locate box "webui/dist-windows"
2024-02-15T09:36:18.002+0100	[34mINFO[0m	Starting web server :9898
```

**Comment by garethgeorge** [comment]
Erk. Sorry about this, I confirmed that the build worked but I missed that there are cases where "rice" fails to embed the web UI files silently (without an error message). I need to get E2E test coverage for this. For now I'll push out a fix tonight. For now I'm going to delist the windows builds for the latest release.

**Comment by garethgeorge** [comment]
Okay, pushed out 0.12.2 with the build issues resolved & tested on my windows box. Switched to go embed for the webui srcs. Go ahead and give that a go. Also enabled integration test coverage of the webui on github actions which should help with the reliability of future releases since I don't always have the bandwidth to explicitly test windows on my machines.
