### ISSUE TITLE
Prune kept in history

### ISSUE THREAD

**Issue by modem** [garethgeorge/backrest#89]
Hi Gareth,

I noticed the prune tasks are kept in the history:
![image](https://github.com/garethgeorge/backrest/assets/62859/4532d4f6-87ac-448c-a8bf-f6e662d5695b)

Is it normal? Does it have any impact besides the cosmetic clutter?

Is there a way to clean this?

**Comment by garethgeorge** [comment]
Hey, this is purely cosmetic. 

Operation retention in the log is determined by the constants here https://github.com/garethgeorge/backrest/blob/main/internal/orchestrator/taskcollectgarbage.go#L19-L20

This is set to the lesser of

 * 30 days
 * 1000 operations

Operations associated with a snapshot will be kept until that snapshot is forgotten (which can be forever if no retention policy is set). So in the case of the prune operations they should be cleaned from the log in about a month.

**Comment by modem** [comment]
Understood. Maybe it's worth to document this somewhere, I expect more people to have similar question in the future.

**Comment by garethgeorge** [comment]
Released https://github.com/garethgeorge/backrest/pull/95 which provides the option to click through and delete old operations.

**Comment by modem** [comment]
Thanks, I updated but had trouble to find the button to forget snapshots. It's not visible:
![image](https://github.com/garethgeorge/backrest/assets/62859/f3dd7777-1f84-48a2-a502-fa2a5a719c79)

unless we hover the mouse:
![image](https://github.com/garethgeorge/backrest/assets/62859/84a11d8b-9a71-4cca-95cb-fb1f6c11a756)

**Comment by garethgeorge** [comment]
good catch, I missed this on the light color theme. Fixed in 0.12.2.
