### ISSUE TITLE
Rclone not in PATH for Docker

### ISSUE THREAD

**Issue by ayykamp** [garethgeorge/backrest#96]
Platform: Docker
Version: 0.12.0

When adding a new repository with any rclone URI it fails with `Operation failed: [unknown] failed to init repo: init failed: command "/data/restic-0.16.4 init --json -o sftp.args=-oBatchMode=yes" failed: exit status 1 Process STDOUT: Fatal: create repository at rclone:restic failed: exec: "rclone": executable file not found in $PATH`.

My config wouldn't even need rclone as I've tried to override it with the flag `-o rclone.program="ssh host"`, for more context on that see [here](https://fluix.one/blog/hetzner-restic-append-only/). But that flag does not even appear in the command from the log. Maybe these are seperate issues.

**Comment by garethgeorge** [comment]
This is definitely on the to-fix list! I think the most likely solution is that I'll start including a version of rclone in the Docker image shipped with backrest (at the cost of some extra space for people not using rclone).

Re: the failure of the command override, flags are buggy when they take arguments. E.g. `-o` and `rclone.program="ssh host"` won't work in a single entry in the configuration. In this case you may be able to get the command to pickup correctly by adding two flags e.g. `-o` and second `rclone.program="ssh host"`.

For the time being, you can try using a custom docker image and adding rclone. Instructions here https://github.com/garethgeorge/backrest/wiki/Hooks-and-Notifications#hooks-in-docker (primarily for use with custom commands, but the idea is the same in principle). The docker file likely looks like:

```
FROM garethgeorge/backrest:latest AS backrest
FROM ubuntu:14.04 AS ubuntu
# ensure that tmp dir exists
COPY --from=backrest /tmp /tmp
# ensure that SSL certs are available
COPY --from=backrest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=backrest /backrest /backrest
RUN apt-get update
RUN apt-get install -y curl bash
RUN curl https://rclone.org/install.sh | sudo bash
# and any other binaries you'd like 
ENTRYPOINT ["/backrest"]
```

**Comment by garethgeorge** [comment]
Updated the base image to alpine linux and bundled rclone, bash, curl: https://github.com/garethgeorge/backrest/commit/cec04f8f745d4bcfd49829c43367c61cb9778174

**Comment by zeropoint46** [comment]
> Updated the base image to alpine linux and bundled rclone, bash, curl: [cec04f8](https://github.com/garethgeorge/backrest/commit/cec04f8f745d4bcfd49829c43367c61cb9778174)

Not seeing the new release in dockerhub or anywhere, and I'm also not sure how you got any of the referenced dockerfiles to work. The one in [#cec04f8f745d4bcfd49829c43367c61cb9778174 ](https://github.com/garethgeorge/backrest/commit/cec04f8f745d4bcfd49829c43367c61cb9778174) or any of the others examples in the repo. It looks like your latest container uses alpine, yet you're also trying to pull from an ubuntu image and use apt. Until the new working docker image is in docker hub, this is the docker build file that worked for me.

`FROM garethgeorge/backrest:latest AS backrest
FROM rclone/rclone:1.65 as rclone
# ensure that tmp dir exists
COPY --from=backrest /tmp /tmp
COPY --from=backrest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=backrest /backrest /backrest
COPY --from=rclone:1.65 /usr/local/bin/rclone /usr/local/bin/rclone
RUN apk --no-cache add ca-certificates bash curl openssh
# and any other binaries you'd like
ENTRYPOINT ["/backrest"]`

**Comment by garethgeorge** [comment]
The addition of images with utilities built on alpine is very recent (only in the dockerfiles and goreleaser config) no images are published yet (when they are they will be tagged with -alpine suffix) and the wiki is still written w.r.t the currently published image based on ‘scratch’. Either way, because the default base image will continue to be scratch so it’s totally fine to pull files out of it and onto Ubuntu or any other distro (e.g. rclone). 

The builds of those dockerfiles should work though, I believe they’re covered by CI. Or did you hit runtime issues with the containers?

**Comment by garethgeorge** [comment]
Released images on dockerhub: https://hub.docker.com/repository/docker/garethgeorge/backrest/tags

The images embedding rclone are the ones with the `-alpine` suffix.

**Comment by zeropoint46** [comment]
> The addition of images with utilities built on alpine is very recent (only in the dockerfiles and goreleaser config) no images are published yet (when they are they will be tagged with -alpine suffix) and the wiki is still written w.r.t the currently published image based on ‘scratch’. Either way, because the default base image will continue to be scratch so it’s totally fine to pull files out of it and onto Ubuntu or any other distro (e.g. rclone).
> 
> The builds of those dockerfiles should work though, I believe they’re covered by CI. Or did you hit runtime issues with the containers?

Well not sure what happend, but when I ran your original docker built, apt-get wasn't even in the image, so I assumed it was using alpine. Also none of the certs were copied so curl wouldn't work. Either way, you got the new image so all is good, thanks for the work.

**Comment by PaddyPat** [comment]
> Released images on dockerhub: https://hub.docker.com/repository/docker/garethgeorge/backrest/tags
> 
> The images embedding rclone are the ones with the `-alpine` suffix.

works fine, also restore:

remember dockerfile:

backrest:
image: garethgeorge/backrest:latest-alpine
container_name: backrest
volumes:
 - /root/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro

**Comment by zeropoint46** [comment]
no SSH in path however.

**Comment by garethgeorge** [comment]
Oops, `apk add openssh` is probably the missing bit, definitely worth including by default.

**Comment by garethgeorge** [comment]
Added openssh in the latest release.
